/* Generated by scripts/gen_data.py — do not edit by hand. */
import type { Dataset } from './types'

export const dataset: Dataset = {
  "org": "deepseek-ai",
  "orgName": "DeepSeek",
  "snapshot": "2026-09-11",
  "repoCount": 105,
  "releases": [
    {
      "id": "deepseek-coder-6.7b-base",
      "repo": "deepseek-ai/deepseek-coder-6.7b-base",
      "name": "DeepSeek Coder",
      "family": "Coder",
      "date": "2023-10-23",
      "tier": "minor",
      "totalParams": "6.7B",
      "activatedParams": null,
      "contextLength": "16K",
      "license": "DeepSeek License",
      "downloads": 72481,
      "likes": 711,
      "storageBytes": 133372226408,
      "storageLabel": "124.2 GB",
      "paramsB": 6.7,
      "activeB": null,
      "innovations": [
        "2T tokens 从零训练",
        "87% 代码语料",
        "16K 窗口",
        "FIM 填空补全"
      ],
      "benchmarks": [],
      "headline": null,
      "summary": "开山之作：从零在 2T tokens（87% 代码）上训练的代码模型家族，6.7B 与 33B 两个尺寸，16K 窗口加填空任务，支持项目级补全。",
      "breakthrough": null,
      "variants": [
        "deepseek-coder-6.7b-base",
        "deepseek-coder-33b-instruct"
      ]
    },
    {
      "id": "deepseek-llm-7b-base",
      "repo": "deepseek-ai/deepseek-llm-7b-base",
      "name": "DeepSeek LLM",
      "family": "LLM",
      "date": "2023-11-29",
      "tier": "minor",
      "totalParams": "7B",
      "activatedParams": null,
      "contextLength": null,
      "license": "DeepSeek License",
      "downloads": 28536,
      "likes": 353,
      "storageBytes": 269700407276,
      "storageLabel": "251.2 GB",
      "paramsB": 7.0,
      "activeB": null,
      "innovations": [
        "2T 中英 tokens",
        "稠密 Transformer",
        "7B / 67B 双尺寸"
      ],
      "benchmarks": [],
      "headline": null,
      "summary": "初代通用模型，7B 与 67B 双尺寸，2T 中英 tokens 从零训练。此时还是标准稠密 Transformer，架构上尚无独门武器。",
      "breakthrough": null,
      "variants": [
        "deepseek-llm-7b-base",
        "deepseek-llm-67b-chat"
      ]
    },
    {
      "id": "deepseek-moe-16b-base",
      "repo": "deepseek-ai/deepseek-moe-16b-base",
      "name": "DeepSeekMoE 16B",
      "family": "LLM",
      "date": "2024-01-08",
      "tier": "minor",
      "totalParams": "16B",
      "activatedParams": null,
      "contextLength": null,
      "license": "DeepSeek License",
      "downloads": 11096,
      "likes": 155,
      "storageBytes": 32752135032,
      "storageLabel": "30.5 GB",
      "paramsB": 16.0,
      "activeB": null,
      "innovations": [
        "DeepSeekMoE",
        "细粒度专家",
        "共享专家",
        "2.8B 激活"
      ],
      "benchmarks": [],
      "headline": null,
      "summary": "DeepSeekMoE 架构的首次开源落地：细粒度专家切分加共享专家隔离，用约 2.8B 激活参数逼近同规模稠密模型。",
      "breakthrough": "细粒度专家 + 共享专家，把「稀疏但有效」这条路走通，成为后续所有 DeepSeek 模型的骨架。",
      "variants": [
        "deepseek-moe-16b-base"
      ]
    },
    {
      "id": "deepseek-coder-7b-instruct-v1.5",
      "repo": "deepseek-ai/deepseek-coder-7b-instruct-v1.5",
      "name": "DeepSeek Coder v1.5",
      "family": "Coder",
      "date": "2024-01-25",
      "tier": "minor",
      "totalParams": "7B",
      "activatedParams": null,
      "contextLength": "4K",
      "license": "DeepSeek License",
      "downloads": 739009,
      "likes": 160,
      "storageBytes": 13820763168,
      "storageLabel": "12.9 GB",
      "paramsB": 7.0,
      "activeB": null,
      "innovations": [
        "继续预训练 2T",
        "指令微调 2B",
        "4K 窗口"
      ],
      "benchmarks": [],
      "headline": null,
      "summary": "把 DeepSeek-LLM 7B 继续预训练成代码模型，再叠加指令微调。仓库长期是社区最常被拉取的轻量代码模型之一。",
      "breakthrough": null,
      "variants": [
        "deepseek-coder-7b-instruct-v1.5"
      ]
    },
    {
      "id": "deepseek-math-7b-instruct",
      "repo": "deepseek-ai/deepseek-math-7b-instruct",
      "name": "DeepSeekMath",
      "family": "Math",
      "date": "2024-02-05",
      "tier": "minor",
      "totalParams": "7B",
      "activatedParams": null,
      "contextLength": null,
      "license": "DeepSeek License",
      "downloads": 5591,
      "likes": 155,
      "storageBytes": 27641588136,
      "storageLabel": "25.7 GB",
      "paramsB": 7.0,
      "activeB": null,
      "innovations": [
        "GRPO 算法",
        "CoT 数学推理",
        "DeepSeekMath-RL"
      ],
      "benchmarks": [],
      "headline": null,
      "summary": "专攻数学推理的 7B 模型，要求用思维链并把答案写进 \\boxed{}。模型本身不大，但它背后的算法改写了后来所有推理模型。",
      "breakthrough": "GRPO 首次提出：用组内相对优势替代 critic 网络，省掉与策略同规模的价值模型，成为 R1 系列的核心算法。",
      "variants": [
        "deepseek-math-7b-instruct"
      ]
    },
    {
      "id": "deepseek-vl-7b-chat",
      "repo": "deepseek-ai/deepseek-vl-7b-chat",
      "name": "DeepSeek-VL",
      "family": "VL",
      "date": "2024-03-07",
      "tier": "minor",
      "totalParams": "7B",
      "activatedParams": null,
      "contextLength": null,
      "license": "DeepSeek License",
      "downloads": 8461,
      "likes": 272,
      "storageBytes": 14688085418,
      "storageLabel": "13.7 GB",
      "paramsB": 7.0,
      "activeB": null,
      "innovations": [
        "SigLIP-L + SAM-B 混合编码",
        "1024×1024 输入",
        "约 400B 图文 token"
      ],
      "benchmarks": [],
      "headline": null,
      "summary": "首个开源视觉语言模型：SigLIP-L 加 SAM-B 混合视觉编码器，吃 1024×1024 图像，约 400B 图文 token 训练。",
      "breakthrough": null,
      "variants": [
        "deepseek-vl-7b-chat"
      ]
    },
    {
      "id": "deepseek-v2",
      "repo": "deepseek-ai/DeepSeek-V2",
      "name": "DeepSeek-V2",
      "family": "LLM",
      "date": "2024-04-22",
      "tier": "flagship",
      "totalParams": "236B",
      "activatedParams": "21B",
      "contextLength": "128K",
      "license": "DeepSeek License",
      "downloads": 63813,
      "likes": 797,
      "storageBytes": 471486512925,
      "storageLabel": "439.1 GB",
      "paramsB": 236.0,
      "activeB": 21.0,
      "innovations": [
        "MLA 潜在注意力",
        "DeepSeekMoE",
        "8.1T tokens 预训练",
        "KV cache ↓93.3%"
      ],
      "benchmarks": [
        {
          "name": "MMLU",
          "score": 78.5,
          "unit": "%",
          "note": "English，DeepSeek-V2 (MoE-236B) base"
        },
        {
          "name": "BBH",
          "score": 78.9,
          "unit": "%",
          "note": "English，base"
        },
        {
          "name": "C-Eval",
          "score": 81.7,
          "unit": "%",
          "note": "Chinese，base"
        },
        {
          "name": "CMMLU",
          "score": 84.0,
          "unit": "%",
          "note": "Chinese，base"
        },
        {
          "name": "HumanEval",
          "score": 48.8,
          "unit": "%",
          "note": "Code，base"
        },
        {
          "name": "GSM8K",
          "score": 79.2,
          "unit": "%",
          "note": "Math，base"
        }
      ],
      "headline": {
        "metric": "CMMLU",
        "score": 84.0
      },
      "summary": "236B 总参数、21B 激活的 MoE 模型。MLA 与 DeepSeekMoE 同时上线，训练成本降低 42.5%，KV cache 减少 93.3%，最大生成吞吐提升 5.76 倍。",
      "breakthrough": "MLA 多头潜在注意力：把 KV 压进低维潜空间再解压，长上下文显存与带宽成本直接降一个量级，此后成为行业标配。",
      "variants": [
        "DeepSeek-V2",
        "DeepSeek-V2-Chat"
      ]
    },
    {
      "id": "deepseek-v2-lite",
      "repo": "deepseek-ai/DeepSeek-V2-Lite",
      "name": "DeepSeek-V2-Lite",
      "family": "LLM",
      "date": "2024-05-15",
      "tier": "major",
      "totalParams": "16B",
      "activatedParams": "2.4B",
      "contextLength": "32K",
      "license": "DeepSeek License",
      "downloads": 342882,
      "likes": 187,
      "storageBytes": 31413626576,
      "storageLabel": "29.3 GB",
      "paramsB": 16.0,
      "activeB": 2.4,
      "innovations": [
        "16B / 2.4B 激活",
        "32K 上下文",
        "单卡 40G 可部署"
      ],
      "benchmarks": [
        {
          "name": "MMLU",
          "score": 58.3,
          "unit": "%",
          "note": "DeepSeek-V2-Lite (MoE-16B) base"
        },
        {
          "name": "BBH",
          "score": 44.1,
          "unit": "%",
          "note": "DeepSeek-V2-Lite (MoE-16B) base"
        },
        {
          "name": "C-Eval",
          "score": 60.3,
          "unit": "%",
          "note": "DeepSeek-V2-Lite (MoE-16B) base"
        },
        {
          "name": "CMMLU",
          "score": 64.3,
          "unit": "%",
          "note": "DeepSeek-V2-Lite (MoE-16B) base"
        },
        {
          "name": "HumanEval",
          "score": 29.9,
          "unit": "%",
          "note": "DeepSeek-V2-Lite (MoE-16B) base"
        },
        {
          "name": "MBPP",
          "score": 43.2,
          "unit": "%",
          "note": "DeepSeek-V2-Lite (MoE-16B) base"
        },
        {
          "name": "GSM8K",
          "score": 41.1,
          "unit": "%",
          "note": "DeepSeek-V2-Lite (MoE-16B) base"
        },
        {
          "name": "MATH",
          "score": 17.1,
          "unit": "%",
          "note": "DeepSeek-V2-Lite (MoE-16B) base"
        }
      ],
      "headline": {
        "metric": "CMMLU",
        "score": 64.3
      },
      "summary": "把 MLA 与 MoE 缩到 16B 总参数 / 2.4B 激活、32K 上下文，单张 40G 卡即可部署，8×80G 可微调。社区研究 MLA 的入口。",
      "breakthrough": null,
      "variants": [
        "DeepSeek-V2-Lite"
      ]
    },
    {
      "id": "deepseek-coder-v2-instruct",
      "repo": "deepseek-ai/DeepSeek-Coder-V2-Instruct",
      "name": "DeepSeek-Coder-V2",
      "family": "Coder",
      "date": "2024-06-14",
      "tier": "major",
      "totalParams": "236B",
      "activatedParams": "21B",
      "contextLength": "128K",
      "license": "DeepSeek License",
      "downloads": 10491,
      "likes": 701,
      "storageBytes": 471486512925,
      "storageLabel": "439.1 GB",
      "paramsB": 236.0,
      "activeB": 21.0,
      "innovations": [
        "6T token 继续预训练",
        "338 种编程语言",
        "128K 上下文"
      ],
      "benchmarks": [],
      "headline": null,
      "summary": "在 V2 中间 checkpoint 上继续预训练 6T token，编程语言从 86 种扩到 338 种、上下文从 16K 提到 128K，代码能力对标 GPT4-Turbo。",
      "breakthrough": null,
      "variants": [
        "DeepSeek-Coder-V2-Instruct"
      ]
    },
    {
      "id": "deepseek-v2.5",
      "repo": "deepseek-ai/DeepSeek-V2.5",
      "name": "DeepSeek-V2.5",
      "family": "LLM",
      "date": "2024-09-05",
      "tier": "major",
      "totalParams": "236B",
      "activatedParams": "21B",
      "contextLength": "128K",
      "license": "DeepSeek License",
      "downloads": 5831,
      "likes": 734,
      "storageBytes": 471486512925,
      "storageLabel": "439.1 GB",
      "paramsB": null,
      "activeB": null,
      "innovations": [
        "通用 + 代码合并",
        "函数调用",
        "JSON 输出",
        "FIM 补全"
      ],
      "benchmarks": [
        {
          "name": "AlpacaEval 2.0",
          "score": 50.5,
          "unit": "%",
          "note": "DeepSeek-V2.5"
        },
        {
          "name": "ArenaHard",
          "score": 76.2,
          "unit": "%",
          "note": "DeepSeek-V2.5"
        },
        {
          "name": "AlignBench",
          "score": 8.0,
          "unit": "%",
          "note": "DeepSeek-V2.5"
        },
        {
          "name": "MT-Bench",
          "score": 9.0,
          "unit": "%",
          "note": "DeepSeek-V2.5"
        },
        {
          "name": "HumanEval python",
          "score": 89.0,
          "unit": "%",
          "note": "DeepSeek-V2.5"
        },
        {
          "name": "HumanEval Multi",
          "score": 73.8,
          "unit": "%",
          "note": "DeepSeek-V2.5"
        },
        {
          "name": "LiveCodeBench(01-09)",
          "score": 41.8,
          "unit": "%",
          "note": "DeepSeek-V2.5"
        },
        {
          "name": "Aider",
          "score": 72.2,
          "unit": "%",
          "note": "DeepSeek-V2.5"
        },
        {
          "name": "SWE-verified",
          "score": 16.8,
          "unit": "%",
          "note": "DeepSeek-V2.5"
        },
        {
          "name": "DS-FIM-Eval",
          "score": 78.3,
          "unit": "%",
          "note": "DeepSeek-V2.5"
        },
        {
          "name": "DS-Arena-Code",
          "score": 63.1,
          "unit": "%",
          "note": "DeepSeek-V2.5"
        }
      ],
      "headline": {
        "metric": "HumanEval python",
        "score": 89.0
      },
      "summary": "把 V2-Chat 的通用能力与 Coder-V2 的代码能力合并进一个模型，补齐写作、函数调用与 JSON 输出。V2 与 V3 之间的过渡版本。",
      "breakthrough": null,
      "variants": [
        "DeepSeek-V2.5"
      ]
    },
    {
      "id": "deepseek-vl2",
      "repo": "deepseek-ai/deepseek-vl2",
      "name": "DeepSeek-VL2",
      "family": "VL",
      "date": "2024-12-13",
      "tier": "major",
      "totalParams": "27B MoE",
      "activatedParams": "4.5B",
      "contextLength": null,
      "license": "DeepSeek License",
      "downloads": 4874,
      "likes": 389,
      "storageBytes": 54961192528,
      "storageLabel": "51.2 GB",
      "paramsB": null,
      "activeB": 1.0,
      "innovations": [
        "MoE 视觉语言模型",
        "动态切图",
        "视觉定位"
      ],
      "benchmarks": [],
      "headline": null,
      "summary": "基于 DeepSeekMoE-27B 的 MoE 视觉语言模型，Tiny / Small / VL2 三档分别激活 1.0B / 2.8B / 4.5B，靠动态切图处理高分辨率。",
      "breakthrough": null,
      "variants": [
        "deepseek-vl2"
      ]
    },
    {
      "id": "deepseek-v3",
      "repo": "deepseek-ai/DeepSeek-V3",
      "name": "DeepSeek-V3",
      "family": "LLM",
      "date": "2024-12-25",
      "tier": "flagship",
      "totalParams": "671B",
      "activatedParams": "37B",
      "contextLength": "128K",
      "license": "MIT",
      "downloads": 1067540,
      "likes": 5887,
      "storageBytes": 688727648088,
      "storageLabel": "641.4 GB",
      "paramsB": 671.0,
      "activeB": 37.0,
      "innovations": [
        "FP8 混合精度训练",
        "无辅助损失负载均衡",
        "MTP 多 token 预测",
        "14.8T tokens / 2.788M H800h"
      ],
      "benchmarks": [
        {
          "name": "MMLU (Acc.)",
          "score": 87.1,
          "unit": "%",
          "note": "DeepSeek-V3 base, 5-shot"
        },
        {
          "name": "BBH (EM)",
          "score": 87.5,
          "unit": "%",
          "note": "DeepSeek-V3 base, 3-shot"
        },
        {
          "name": "MMLU-Pro (Acc.)",
          "score": 64.4,
          "unit": "%",
          "note": "DeepSeek-V3 base, 5-shot"
        },
        {
          "name": "DROP (F1)",
          "score": 89.0,
          "unit": "%",
          "note": "DeepSeek-V3 base, 3-shot"
        },
        {
          "name": "HumanEval (Pass@1)",
          "score": 65.2,
          "unit": "%",
          "note": "DeepSeek-V3 base, 0-shot"
        },
        {
          "name": "MBPP (Pass@1)",
          "score": 75.4,
          "unit": "%",
          "note": "DeepSeek-V3 base, 3-shot"
        },
        {
          "name": "GSM8K (EM)",
          "score": 89.3,
          "unit": "%",
          "note": "DeepSeek-V3 base, 8-shot"
        },
        {
          "name": "MATH (EM)",
          "score": 61.6,
          "unit": "%",
          "note": "DeepSeek-V3 base, 4-shot"
        },
        {
          "name": "MMLU (EM)",
          "score": 88.5,
          "unit": "%",
          "note": "DeepSeek-V3 chat"
        },
        {
          "name": "GPQA-Diamond (Pass@1)",
          "score": 59.1,
          "unit": "%",
          "note": "DeepSeek-V3 chat"
        },
        {
          "name": "LiveCodeBench (Pass@1-COT)",
          "score": 40.5,
          "unit": "%",
          "note": "DeepSeek-V3 chat"
        },
        {
          "name": "Codeforces (Percentile)",
          "score": 51.6,
          "unit": "%",
          "note": "DeepSeek-V3 chat"
        }
      ],
      "headline": {
        "metric": "GPQA-Diamond",
        "score": 59.1
      },
      "summary": "671B 总参数 / 37B 激活。首次在超大规模验证 FP8 混合精度训练，引入无辅助损失的负载均衡与多 token 预测，14.8T token 只花 2.788M H800 小时。",
      "breakthrough": "FP8 训练 + 无辅助损失负载均衡 + MTP：把「大模型必须用 BF16 且负载均衡要牺牲性能」这两条经验同时推翻。",
      "variants": [
        "DeepSeek-V3",
        "DeepSeek-V3-Base"
      ]
    },
    {
      "id": "deepseek-r1",
      "repo": "deepseek-ai/DeepSeek-R1",
      "name": "DeepSeek-R1",
      "family": "Reasoning",
      "date": "2025-01-20",
      "tier": "flagship",
      "totalParams": "671B",
      "activatedParams": "37B",
      "contextLength": "128K",
      "license": "MIT",
      "downloads": 1241957,
      "likes": 16194,
      "storageBytes": 688628350856,
      "storageLabel": "641.3 GB",
      "paramsB": 671.0,
      "activeB": 37.0,
      "innovations": [
        "纯 RL 无 SFT",
        "冷启动数据",
        "长思维链",
        "推理蒸馏"
      ],
      "benchmarks": [
        {
          "name": "MMLU (Pass@1)",
          "score": 90.8,
          "unit": "%",
          "note": "官方卡片口径"
        },
        {
          "name": "MMLU-Redux (EM)",
          "score": 92.9,
          "unit": "%",
          "note": "官方卡片口径"
        },
        {
          "name": "MMLU-Pro (EM)",
          "score": 84.0,
          "unit": "%",
          "note": "官方卡片口径"
        },
        {
          "name": "DROP (3-shot F1)",
          "score": 92.2,
          "unit": "%",
          "note": "官方卡片口径"
        },
        {
          "name": "GPQA-Diamond (Pass@1)",
          "score": 71.5,
          "unit": "%",
          "note": "官方卡片口径"
        },
        {
          "name": "FRAMES (Acc.)",
          "score": 82.5,
          "unit": "%",
          "note": "官方卡片口径"
        },
        {
          "name": "AlpacaEval2.0 (LC-winrate)",
          "score": 87.6,
          "unit": "%",
          "note": "官方卡片口径"
        },
        {
          "name": "ArenaHard (GPT-4-1106)",
          "score": 92.3,
          "unit": "%",
          "note": "官方卡片口径"
        },
        {
          "name": "LiveCodeBench (Pass@1-COT)",
          "score": 65.9,
          "unit": "%",
          "note": "官方卡片口径"
        },
        {
          "name": "Codeforces (Rating)",
          "score": 2029.0,
          "unit": "Rating",
          "note": "官方卡片口径"
        },
        {
          "name": "SWE Verified (Resolved)",
          "score": 49.2,
          "unit": "%",
          "note": "官方卡片口径"
        },
        {
          "name": "Aider-Polyglot (Acc.)",
          "score": 53.3,
          "unit": "%",
          "note": "官方卡片口径"
        }
      ],
      "headline": {
        "metric": "GPQA-Diamond",
        "score": 71.5
      },
      "summary": "首个公开验证「纯强化学习即可激发推理能力」的模型系列：R1-Zero 跳过 SFT 直接大规模 RL，R1 加入冷启动数据与两阶段 RL / SFT，并把推理能力蒸馏到 6 个稠密小模型。",
      "breakthrough": "无 SFT 的大规模 RL：自验证、反思与长思维链自发涌现，MIT 协议开放权重，把推理能力变成可复制的开源资产。",
      "variants": [
        "DeepSeek-R1",
        "DeepSeek-R1-Zero",
        "DeepSeek-R1-Distill-Qwen-32B"
      ]
    },
    {
      "id": "janus-pro-7b",
      "repo": "deepseek-ai/Janus-Pro-7B",
      "name": "Janus-Pro",
      "family": "Janus",
      "date": "2025-01-26",
      "tier": "major",
      "totalParams": "7B",
      "activatedParams": null,
      "contextLength": null,
      "license": "MIT (code) / Model License",
      "downloads": 10897,
      "likes": 3658,
      "storageBytes": 29695390113,
      "storageLabel": "27.7 GB",
      "paramsB": null,
      "activeB": null,
      "innovations": [
        "视觉编码解耦",
        "统一 Transformer",
        "理解 + 生成同塔"
      ],
      "benchmarks": [],
      "headline": null,
      "summary": "统一多模态模型：把视觉编码按「理解」与「生成」解耦成两条独立路径，但保留单一自回归 Transformer，缓解同一编码器在两类任务间的冲突。",
      "breakthrough": "解耦视觉编码 + 单塔自回归，让一个模型同时做好图像理解与图像生成。",
      "variants": [
        "Janus-Pro-7B"
      ]
    },
    {
      "id": "deepseek-v3-0324",
      "repo": "deepseek-ai/DeepSeek-V3-0324",
      "name": "DeepSeek-V3-0324",
      "family": "LLM",
      "date": "2025-03-24",
      "tier": "major",
      "totalParams": "671B",
      "activatedParams": "37B",
      "contextLength": "128K",
      "license": "MIT",
      "downloads": 934873,
      "likes": 3169,
      "storageBytes": 688592341287,
      "storageLabel": "641.3 GB",
      "paramsB": null,
      "activeB": null,
      "innovations": [
        "结构零改动",
        "后训练涨点",
        "前端代码生成",
        "函数调用优化"
      ],
      "benchmarks": [
        {
          "name": "MMLU-Pro",
          "score": 81.2,
          "unit": "%",
          "note": "up from 75.9 (+5.3)"
        },
        {
          "name": "GPQA",
          "score": 68.4,
          "unit": "%",
          "note": "up from 59.1 (+9.3)"
        },
        {
          "name": "AIME",
          "score": 59.4,
          "unit": "%",
          "note": "up from 39.6 (+19.8)"
        },
        {
          "name": "LiveCodeBench",
          "score": 49.2,
          "unit": "%",
          "note": "up from 39.2 (+10.0)"
        }
      ],
      "headline": {
        "metric": "GPQA-Diamond",
        "score": 68.4
      },
      "summary": "结构完全不变的小版本升级，靠后训练把推理、前端页面生成、中文写作与函数调用拉起来：MMLU-Pro、GPQA、AIME、LiveCodeBench 分别 +5.3 / +9.3 / +19.8 / +10.0。",
      "breakthrough": "同一套权重、不加参数，只靠后训练就能涨十几分 AIME，证明后训练算力的回报尚未见顶。",
      "variants": [
        "DeepSeek-V3-0324"
      ]
    },
    {
      "id": "deepseek-prover-v2-671b",
      "repo": "deepseek-ai/DeepSeek-Prover-V2-671B",
      "name": "DeepSeek-Prover-V2",
      "family": "Prover",
      "date": "2025-04-30",
      "tier": "major",
      "totalParams": "671B",
      "activatedParams": null,
      "contextLength": null,
      "license": "DeepSeek License",
      "downloads": 746,
      "likes": 831,
      "storageBytes": 688586727753,
      "storageLabel": "641.3 GB",
      "paramsB": 671.0,
      "activeB": null,
      "innovations": [
        "Lean 4 形式化证明",
        "子目标递归分解",
        "二元反馈 RL",
        "MiniF2F 88.9%"
      ],
      "benchmarks": [
        {
          "name": "MiniF2F-test (pass ratio)",
          "score": 88.9,
          "unit": "%",
          "note": "state-of-the-art in neural theorem proving"
        }
      ],
      "headline": {
        "metric": "MiniF2F-test (pass ratio)",
        "score": 88.9
      },
      "summary": "面向 Lean 4 的形式化定理证明：用 V3 递归拆解子目标，把形式化证明与思维链合成为冷启动数据，再用对错二元反馈做 RL。MiniF2F-test 通过率 88.9%，PutnamBench 解出 658 题中的 49 题。",
      "breakthrough": "神经定理证明首次做出可用的递归分解 + RL 闭环，形式化数学开始进入大模型射程。",
      "variants": [
        "DeepSeek-Prover-V2-671B"
      ]
    },
    {
      "id": "deepseek-r1-0528",
      "repo": "deepseek-ai/DeepSeek-R1-0528",
      "name": "DeepSeek-R1-0528",
      "family": "Reasoning",
      "date": "2025-05-28",
      "tier": "major",
      "totalParams": "671B",
      "activatedParams": "37B",
      "contextLength": "128K",
      "license": "MIT",
      "downloads": 225134,
      "likes": 2460,
      "storageBytes": 688588119234,
      "storageLabel": "641.3 GB",
      "paramsB": null,
      "activeB": null,
      "innovations": [
        "思考长度 12K→23K",
        "AIME 2025 87.5%",
        "幻觉率下降",
        "支持 system prompt"
      ],
      "benchmarks": [
        {
          "name": "MMLU-Redux (EM)",
          "score": 93.4,
          "unit": "%",
          "note": "DeepSeek R1: 92.9"
        },
        {
          "name": "MMLU-Pro (EM)",
          "score": 85.0,
          "unit": "%",
          "note": "DeepSeek R1: 84.0"
        },
        {
          "name": "GPQA-Diamond (Pass@1)",
          "score": 81.0,
          "unit": "%",
          "note": "DeepSeek R1: 71.5"
        },
        {
          "name": "SimpleQA (Correct)",
          "score": 27.8,
          "unit": "%",
          "note": "DeepSeek R1: 30.1"
        },
        {
          "name": "FRAMES (Acc.)",
          "score": 83.0,
          "unit": "%",
          "note": "DeepSeek R1: 82.5"
        },
        {
          "name": "Humanity's Last Exam (Pass@1)",
          "score": 17.7,
          "unit": "%",
          "note": "DeepSeek R1: 8.5; text-only subset"
        },
        {
          "name": "LiveCodeBench (2408-2505) (Pass@1)",
          "score": 73.3,
          "unit": "%",
          "note": "DeepSeek R1: 63.5"
        },
        {
          "name": "Codeforces-Div1 (Rating)",
          "score": 1930.0,
          "unit": "Rating",
          "note": "DeepSeek R1: 1530"
        },
        {
          "name": "SWE Verified (Resolved)",
          "score": 57.6,
          "unit": "%",
          "note": "DeepSeek R1: 49.2; Agentless framework"
        },
        {
          "name": "Aider-Polyglot (Acc.)",
          "score": 71.6,
          "unit": "%",
          "note": "DeepSeek R1: 53.3"
        },
        {
          "name": "AIME 2024 (Pass@1)",
          "score": 91.4,
          "unit": "%",
          "note": "DeepSeek R1: 79.8"
        },
        {
          "name": "AIME 2025 (Pass@1)",
          "score": 87.5,
          "unit": "%",
          "note": "DeepSeek R1: 70.0"
        }
      ],
      "headline": {
        "metric": "GPQA-Diamond",
        "score": 81.0
      },
      "summary": "R1 的小版本升级：后训练算力加码，AIME 2025 从 70% 升至 87.5%，单题平均思考 token 从 12K 涨到 23K，同时降低幻觉并支持 system prompt。",
      "breakthrough": "用「想得更久」换分数：思考长度翻倍直接换来 17.5 个 AIME 点，推理强度的可扩展性被明确量化。",
      "variants": [
        "DeepSeek-R1-0528"
      ]
    },
    {
      "id": "deepseek-v3.1",
      "repo": "deepseek-ai/DeepSeek-V3.1",
      "name": "DeepSeek-V3.1",
      "family": "LLM",
      "date": "2025-08-21",
      "tier": "major",
      "totalParams": "671B",
      "activatedParams": "37B",
      "contextLength": "128K",
      "license": "MIT",
      "downloads": 233589,
      "likes": 830,
      "storageBytes": 688595361908,
      "storageLabel": "641.3 GB",
      "paramsB": 671.0,
      "activeB": 37.0,
      "innovations": [
        "混合推理双模式",
        "UE8M0 FP8 scale",
        "两阶段长上下文扩展",
        "Agent 能力增强"
      ],
      "benchmarks": [
        {
          "name": "MMLU-Redux (EM)",
          "score": 93.7,
          "unit": "%",
          "note": "V3.1-Thinking; NonThinking 91.8, V3-0324 90.5, R1-0528 93.4"
        },
        {
          "name": "MMLU-Pro (EM)",
          "score": 84.8,
          "unit": "%",
          "note": "V3.1-Thinking; NonThinking 83.7, V3-0324 81.2, R1-0528 85.0"
        },
        {
          "name": "GPQA-Diamond (Pass@1)",
          "score": 80.1,
          "unit": "%",
          "note": "V3.1-Thinking; NonThinking 74.9, V3-0324 68.4, R1-0528 81.0"
        },
        {
          "name": "Humanity's Last Exam (Pass@1)",
          "score": 15.9,
          "unit": "%",
          "note": "V3.1-Thinking; R1-0528 17.7"
        },
        {
          "name": "BrowseComp",
          "score": 30.0,
          "unit": "%",
          "note": "V3.1-Thinking; R1-0528 8.9; internal search framework"
        },
        {
          "name": "BrowseComp_zh",
          "score": 49.2,
          "unit": "%",
          "note": "V3.1-Thinking; R1-0528 35.7"
        },
        {
          "name": "Humanity's Last Exam (Python + Search)",
          "score": 29.8,
          "unit": "%",
          "note": "V3.1-Thinking; R1-0528 24.8"
        },
        {
          "name": "SimpleQA",
          "score": 93.4,
          "unit": "%",
          "note": "V3.1-Thinking; R1-0528 92.3"
        },
        {
          "name": "LiveCodeBench (2408-2505) (Pass@1)",
          "score": 74.8,
          "unit": "%",
          "note": "V3.1-Thinking; NonThinking 56.4, V3-0324 43.0, R1-0528 73.3"
        },
        {
          "name": "Codeforces-Div1 (Rating)",
          "score": 2091.0,
          "unit": "Rating",
          "note": "V3.1-Thinking; R1-0528 1930"
        },
        {
          "name": "Aider-Polyglot (Acc.)",
          "score": 76.3,
          "unit": "%",
          "note": "V3.1-Thinking; NonThinking 68.4, V3-0324 55.1, R1-0528 71.6"
        },
        {
          "name": "SWE Verified (Agent mode)",
          "score": 66.0,
          "unit": "%",
          "note": "V3.1-NonThinking; V3-0324 45.4, R1-0528 44.6; internal code agent framework"
        }
      ],
      "headline": {
        "metric": "GPQA-Diamond",
        "score": 80.1
      },
      "summary": "混合推理版本：同一份权重靠切换 chat template 就能在 thinking 与 non-thinking 两档之间切换，工具调用与 agent 能力显著增强，并用 UE8M0 FP8 scale 格式训练权重与激活。",
      "breakthrough": "一份权重两种模式 + UE8M0 FP8：推理成本与国产芯片适配性同时解决，为后续 Agent 化铺路。",
      "variants": [
        "DeepSeek-V3.1"
      ]
    },
    {
      "id": "deepseek-v3.1-terminus",
      "repo": "deepseek-ai/DeepSeek-V3.1-Terminus",
      "name": "DeepSeek-V3.1-Terminus",
      "family": "LLM",
      "date": "2025-09-22",
      "tier": "major",
      "totalParams": "671B",
      "activatedParams": "37B",
      "contextLength": "128K",
      "license": "MIT",
      "downloads": 19156,
      "likes": 366,
      "storageBytes": 688588816461,
      "storageLabel": "641.3 GB",
      "paramsB": null,
      "activeB": null,
      "innovations": [
        "语言一致性修复",
        "Code / Search Agent 优化",
        "搜索工具集更新"
      ],
      "benchmarks": [
        {
          "name": "MMLU-Pro",
          "score": 85.0,
          "unit": "%",
          "note": "DeepSeek-V3.1: 84.8"
        },
        {
          "name": "GPQA-Diamond",
          "score": 80.7,
          "unit": "%",
          "note": "DeepSeek-V3.1: 80.1"
        },
        {
          "name": "Humanity's Last Exam",
          "score": 21.7,
          "unit": "%",
          "note": "DeepSeek-V3.1: 15.9"
        },
        {
          "name": "LiveCodeBench",
          "score": 74.9,
          "unit": "%",
          "note": "DeepSeek-V3.1: 74.8"
        },
        {
          "name": "Codeforces",
          "score": 2046.0,
          "unit": "Rating",
          "note": "DeepSeek-V3.1: 2091"
        },
        {
          "name": "Aider-Polyglot",
          "score": 76.1,
          "unit": "%",
          "note": "DeepSeek-V3.1: 76.3"
        },
        {
          "name": "BrowseComp",
          "score": 38.5,
          "unit": "%",
          "note": "DeepSeek-V3.1: 30.0"
        },
        {
          "name": "BrowseComp-zh",
          "score": 45.0,
          "unit": "%",
          "note": "DeepSeek-V3.1: 49.2"
        },
        {
          "name": "SimpleQA",
          "score": 96.8,
          "unit": "%",
          "note": "DeepSeek-V3.1: 93.4"
        },
        {
          "name": "SWE Verified",
          "score": 68.4,
          "unit": "%",
          "note": "DeepSeek-V3.1: 66.0"
        },
        {
          "name": "SWE-bench Multilingual",
          "score": 57.8,
          "unit": "%",
          "note": "DeepSeek-V3.1: 54.5"
        },
        {
          "name": "Terminal-bench",
          "score": 36.7,
          "unit": "%",
          "note": "DeepSeek-V3.1: 31.3"
        }
      ],
      "headline": {
        "metric": "GPQA-Diamond",
        "score": 80.7
      },
      "summary": "按用户反馈出的修复版：减少中英混输与异常字符，重点优化 Code Agent 与 Search Agent（HLE 15.9→21.7、BrowseComp 30.0→38.5、SimpleQA 93.4→96.8）。",
      "breakthrough": null,
      "variants": [
        "DeepSeek-V3.1-Terminus"
      ]
    },
    {
      "id": "deepseek-v3.2-exp",
      "repo": "deepseek-ai/DeepSeek-V3.2-Exp",
      "name": "DeepSeek-V3.2-Exp",
      "family": "LLM",
      "date": "2025-09-29",
      "tier": "flagship",
      "totalParams": "671B",
      "activatedParams": "37B",
      "contextLength": "128K",
      "license": "MIT",
      "downloads": 60359,
      "likes": 1000,
      "storageBytes": 689483151335,
      "storageLabel": "642.1 GB",
      "paramsB": null,
      "activeB": null,
      "innovations": [
        "DSA 细粒度稀疏注意力",
        "Lightning Indexer",
        "训练配置对齐 V3.1",
        "长文本效率"
      ],
      "benchmarks": [
        {
          "name": "MMLU-Pro",
          "score": 85.0,
          "unit": "%",
          "note": "V3.1-Terminus: 85.0"
        },
        {
          "name": "GPQA-Diamond",
          "score": 79.9,
          "unit": "%",
          "note": "V3.1-Terminus: 80.7"
        },
        {
          "name": "Humanity's Last Exam",
          "score": 19.8,
          "unit": "%",
          "note": "V3.1-Terminus: 21.7"
        },
        {
          "name": "LiveCodeBench",
          "score": 74.1,
          "unit": "%",
          "note": "V3.1-Terminus: 74.9"
        },
        {
          "name": "AIME 2025",
          "score": 89.3,
          "unit": "%",
          "note": "V3.1-Terminus: 88.4"
        },
        {
          "name": "HMMT 2025",
          "score": 83.6,
          "unit": "%",
          "note": "V3.1-Terminus: 86.1"
        },
        {
          "name": "Codeforces",
          "score": 2121.0,
          "unit": "Rating",
          "note": "V3.1-Terminus: 2046"
        },
        {
          "name": "Aider-Polyglot",
          "score": 74.5,
          "unit": "%",
          "note": "V3.1-Terminus: 76.1"
        },
        {
          "name": "BrowseComp",
          "score": 40.1,
          "unit": "%",
          "note": "V3.1-Terminus: 38.5"
        },
        {
          "name": "BrowseComp-zh",
          "score": 47.9,
          "unit": "%",
          "note": "V3.1-Terminus: 45.0"
        },
        {
          "name": "SimpleQA",
          "score": 97.1,
          "unit": "%",
          "note": "V3.1-Terminus: 96.8"
        },
        {
          "name": "SWE Verified",
          "score": 67.8,
          "unit": "%",
          "note": "V3.1-Terminus: 68.4"
        }
      ],
      "headline": {
        "metric": "GPQA-Diamond",
        "score": 79.9
      },
      "summary": "通往下一代架构的实验版：首次引入 DeepSeek Sparse Attention（DSA）做细粒度稀疏注意力。为了公平归因，训练配置刻意与 V3.1-Terminus 对齐，各基准基本持平。",
      "breakthrough": "DSA 稀疏注意力：把长文本注意力从「全连接」改成「先选后算」，长上下文训练与推理成本大幅下降而质量几乎不掉。",
      "variants": [
        "DeepSeek-V3.2-Exp"
      ]
    },
    {
      "id": "deepseek-ocr",
      "repo": "deepseek-ai/DeepSeek-OCR",
      "name": "DeepSeek-OCR",
      "family": "OCR",
      "date": "2025-10-17",
      "tier": "major",
      "totalParams": null,
      "activatedParams": null,
      "contextLength": null,
      "license": "MIT",
      "downloads": 2394300,
      "likes": 3351,
      "storageBytes": 6711407201,
      "storageLabel": "6.3 GB",
      "paramsB": null,
      "activeB": null,
      "innovations": [
        "Contexts Optical Compression",
        "grounding 转 Markdown",
        "多档分辨率",
        "vLLM 官方支持"
      ],
      "benchmarks": [],
      "headline": null,
      "summary": "提出「上下文光学压缩」：把文本上下文压成视觉 token 再解码，探索视觉通道能装下多少文字。支持 grounding 转 Markdown 与多档分辨率，官方 vLLM 直接支持。",
      "breakthrough": "上下文光学压缩：用视觉 token 承载文本，为「不靠拉长 token 序列也能扩上下文」打开一条新路。",
      "variants": [
        "DeepSeek-OCR"
      ]
    },
    {
      "id": "deepseek-math-v2",
      "repo": "deepseek-ai/DeepSeek-Math-V2",
      "name": "DeepSeek-Math-V2",
      "family": "Math",
      "date": "2025-11-27",
      "tier": "major",
      "totalParams": "671B",
      "activatedParams": "37B",
      "contextLength": "128K",
      "license": "Apache-2.0",
      "downloads": 682,
      "likes": 707,
      "storageBytes": 689483049129,
      "storageLabel": "642.1 GB",
      "paramsB": null,
      "activeB": null,
      "innovations": [
        "自验证数学推理",
        "LLM 验证器作奖励",
        "扩展验证算力",
        "IMO 2025 金牌"
      ],
      "benchmarks": [
        {
          "name": "Putnam 2024",
          "score": 118.0,
          "unit": "/120",
          "note": "near-perfect score with scaled test-time compute"
        }
      ],
      "headline": null,
      "summary": "可自验证的数学推理路线：用 LLM 验证器作奖励去训练证明生成器，并靠扩展验证算力自动标注难核验的证明。IMO 2025 与 CMO 2024 达金牌水平，Putnam 2024 拿到 118/120。",
      "breakthrough": "生成器与验证器分离并互相放大：把「答案对不对」变成可扩展的监督信号，数学能力随之越过金牌线。",
      "variants": [
        "DeepSeek-Math-V2"
      ]
    },
    {
      "id": "deepseek-v3.2",
      "repo": "deepseek-ai/DeepSeek-V3.2",
      "name": "DeepSeek-V3.2",
      "family": "LLM",
      "date": "2025-12-01",
      "tier": "major",
      "totalParams": "671B",
      "activatedParams": "37B",
      "contextLength": "1M",
      "license": "MIT",
      "downloads": 1664551,
      "likes": 1476,
      "storageBytes": 689484423011,
      "storageLabel": "642.1 GB",
      "paramsB": null,
      "activeB": null,
      "innovations": [
        "DSA 稀疏注意力",
        "可扩展 RL 框架",
        "Agentic 任务合成",
        "Speciale 高算力变体"
      ],
      "benchmarks": [],
      "headline": null,
      "summary": "DSA 稀疏注意力转正，配合可扩展 RL 框架与大规模 Agentic 任务合成管道，主打高效推理与智能体能力；高算力变体 Speciale 称在 IMO / IOI 2025 拿到金牌表现。",
      "breakthrough": "大规模 Agentic 数据合成 + 可扩展 RL：把训练信号从「对话」搬到「真实任务环境」，智能体能力成为主线。",
      "variants": [
        "DeepSeek-V3.2"
      ]
    },
    {
      "id": "deepseek-ocr-2",
      "repo": "deepseek-ai/DeepSeek-OCR-2",
      "name": "DeepSeek-OCR 2",
      "family": "OCR",
      "date": "2026-01-27",
      "tier": "major",
      "totalParams": null,
      "activatedParams": null,
      "contextLength": null,
      "license": "Apache-2.0",
      "downloads": 942892,
      "likes": 1089,
      "storageBytes": 6779402071,
      "storageLabel": "6.3 GB",
      "paramsB": null,
      "activeB": null,
      "innovations": [
        "Visual Causal Flow",
        "动态分辨率",
        "视觉上下文压缩"
      ],
      "benchmarks": [],
      "headline": null,
      "summary": "延续光学压缩路线，以 Visual Causal Flow 为核心探索更接近人类的视觉编码方式，支持动态分辨率。",
      "breakthrough": "Visual Causal Flow：让视觉编码按因果顺序而非固定栅格推进，向人类阅读方式靠近。",
      "variants": [
        "DeepSeek-OCR-2"
      ]
    },
    {
      "id": "deepseek-v4-flash",
      "repo": "deepseek-ai/DeepSeek-V4-Flash",
      "name": "DeepSeek-V4-Flash",
      "family": "LLM",
      "date": "2026-04-22",
      "tier": "major",
      "totalParams": "284B",
      "activatedParams": "13B",
      "contextLength": "1M",
      "license": "MIT",
      "downloads": 1776693,
      "likes": 2211,
      "storageBytes": 159641337663,
      "storageLabel": "148.7 GB",
      "paramsB": 284.0,
      "activeB": 13.0,
      "innovations": [
        "CSA + HCA 混合注意力",
        "mHC 流形约束超连接",
        "Muon 优化器",
        "1M 上下文",
        "27% FLOPs / 10% KV"
      ],
      "benchmarks": [
        {
          "name": "MMLU",
          "score": 88.7,
          "unit": "%",
          "note": "DeepSeek-V4-Flash-Base, EM, 5-shot"
        },
        {
          "name": "MMLU-Pro",
          "score": 68.3,
          "unit": "%",
          "note": "DeepSeek-V4-Flash-Base, EM, 5-shot"
        },
        {
          "name": "Simple-QA verified",
          "score": 30.1,
          "unit": "%",
          "note": "DeepSeek-V4-Flash-Base, EM, 25-shot"
        },
        {
          "name": "AGIEval",
          "score": 82.6,
          "unit": "%",
          "note": "DeepSeek-V4-Flash-Base, EM, 0-shot"
        },
        {
          "name": "HumanEval",
          "score": 69.5,
          "unit": "%",
          "note": "DeepSeek-V4-Flash-Base, Pass@1, 0-shot"
        },
        {
          "name": "LongBench-V2",
          "score": 44.7,
          "unit": "%",
          "note": "DeepSeek-V4-Flash-Base, EM, 1-shot"
        },
        {
          "name": "SimpleQA-Verified",
          "score": 34.1,
          "unit": "%",
          "note": "V4-Flash Max (instruct), Pass@1"
        },
        {
          "name": "GPQA Diamond",
          "score": 88.1,
          "unit": "%",
          "note": "V4-Flash Max (instruct), Pass@1"
        },
        {
          "name": "HLE",
          "score": 34.8,
          "unit": "%",
          "note": "V4-Flash Max (instruct), Pass@1"
        },
        {
          "name": "LiveCodeBench",
          "score": 91.6,
          "unit": "%",
          "note": "V4-Flash Max (instruct), Pass@1"
        },
        {
          "name": "Codeforces",
          "score": 3052.0,
          "unit": "Rating",
          "note": "V4-Flash Max (instruct), Rating"
        },
        {
          "name": "HMMT 2026 Feb",
          "score": 94.8,
          "unit": "%",
          "note": "V4-Flash Max (instruct), Pass@1"
        }
      ],
      "headline": {
        "metric": "GPQA-Diamond",
        "score": 88.1
      },
      "summary": "V4 预览版 Flash 型：284B 总参数 / 13B 激活，百万 token 上下文。引入 CSA+HCA 混合注意力、mHC 流形约束超连接与 Muon 优化器。",
      "breakthrough": "CSA + HCA 混合注意力与 mHC：1M 上下文下只需 V3.2 的 27% 单 token 推理 FLOPs 与 10% KV cache。",
      "variants": [
        "DeepSeek-V4-Flash"
      ]
    },
    {
      "id": "deepseek-v4-pro",
      "repo": "deepseek-ai/DeepSeek-V4-Pro",
      "name": "DeepSeek-V4-Pro",
      "family": "LLM",
      "date": "2026-04-22",
      "tier": "flagship",
      "totalParams": "1.6T",
      "activatedParams": "49B",
      "contextLength": "1M",
      "license": "MIT",
      "downloads": 612515,
      "likes": 5522,
      "storageBytes": 864761623612,
      "storageLabel": "805.4 GB",
      "paramsB": 1600.0,
      "activeB": 49.0,
      "innovations": [
        "1.6T 总参数 / 49B 激活",
        "CSA + HCA",
        "mHC",
        "Muon 优化器",
        "1M 上下文"
      ],
      "benchmarks": [
        {
          "name": "MMLU",
          "score": 90.1,
          "unit": "%",
          "note": "DeepSeek-V4-Pro-Base, EM, 5-shot"
        },
        {
          "name": "MMLU-Pro",
          "score": 73.5,
          "unit": "%",
          "note": "DeepSeek-V4-Pro-Base, EM, 5-shot"
        },
        {
          "name": "Simple-QA verified",
          "score": 55.2,
          "unit": "%",
          "note": "DeepSeek-V4-Pro-Base, EM, 25-shot"
        },
        {
          "name": "AGIEval",
          "score": 83.1,
          "unit": "%",
          "note": "DeepSeek-V4-Pro-Base, EM, 0-shot"
        },
        {
          "name": "HumanEval",
          "score": 76.8,
          "unit": "%",
          "note": "DeepSeek-V4-Pro-Base, Pass@1, 0-shot"
        },
        {
          "name": "LongBench-V2",
          "score": 51.5,
          "unit": "%",
          "note": "DeepSeek-V4-Pro-Base, EM, 1-shot"
        },
        {
          "name": "SimpleQA-Verified",
          "score": 57.9,
          "unit": "%",
          "note": "DS-V4-Pro Max, Pass@1"
        },
        {
          "name": "Chinese-SimpleQA",
          "score": 84.4,
          "unit": "%",
          "note": "DS-V4-Pro Max, Pass@1"
        },
        {
          "name": "GPQA Diamond",
          "score": 90.1,
          "unit": "%",
          "note": "DS-V4-Pro Max, Pass@1"
        },
        {
          "name": "HLE",
          "score": 37.7,
          "unit": "%",
          "note": "DS-V4-Pro Max, Pass@1"
        },
        {
          "name": "LiveCodeBench",
          "score": 93.5,
          "unit": "%",
          "note": "DS-V4-Pro Max, Pass@1"
        },
        {
          "name": "Codeforces",
          "score": 3206.0,
          "unit": "Rating",
          "note": "DS-V4-Pro Max, Rating"
        }
      ],
      "headline": {
        "metric": "GPQA-Diamond",
        "score": 90.1
      },
      "summary": "V4 预览版 Pro 型：1.6T 总参数 / 49B 激活，百万 token 上下文，与 Flash 共用同一套架构改动，Pro-Max 模式称当时最强开源模型。",
      "breakthrough": null,
      "variants": [
        "DeepSeek-V4-Pro"
      ]
    },
    {
      "id": "deepseek-v4-flash-dspark",
      "repo": "deepseek-ai/DeepSeek-V4-Flash-DSpark",
      "name": "DeepSeek-V4-Flash-DSpark",
      "family": "LLM",
      "date": "2026-06-27",
      "tier": "major",
      "totalParams": "284B",
      "activatedParams": "13B",
      "contextLength": "1M",
      "license": "MIT",
      "downloads": 697663,
      "likes": 271,
      "storageBytes": 166886535336,
      "storageLabel": "155.4 GB",
      "paramsB": 284.0,
      "activeB": 13.0,
      "innovations": [
        "DSpark 投机解码",
        "同权重即插即用",
        "vLLM / SGLang 单参数"
      ],
      "benchmarks": [
        {
          "name": "MMLU",
          "score": 88.7,
          "unit": "%",
          "note": "DeepSeek-V4-Flash-Base column of this card's shared V4 table, EM, 5-shot"
        },
        {
          "name": "MMLU-Pro",
          "score": 68.3,
          "unit": "%",
          "note": "DeepSeek-V4-Flash-Base column, EM, 5-shot"
        },
        {
          "name": "Simple-QA verified",
          "score": 30.1,
          "unit": "%",
          "note": "DeepSeek-V4-Flash-Base column, EM, 25-shot"
        },
        {
          "name": "LongBench-V2",
          "score": 44.7,
          "unit": "%",
          "note": "DeepSeek-V4-Flash-Base column, EM, 1-shot"
        },
        {
          "name": "SimpleQA-Verified",
          "score": 34.1,
          "unit": "%",
          "note": "V4-Flash Max column, Pass@1"
        },
        {
          "name": "GPQA Diamond",
          "score": 88.1,
          "unit": "%",
          "note": "V4-Flash Max column, Pass@1"
        },
        {
          "name": "HLE",
          "score": 34.8,
          "unit": "%",
          "note": "V4-Flash Max column, Pass@1"
        },
        {
          "name": "LiveCodeBench",
          "score": 91.6,
          "unit": "%",
          "note": "V4-Flash Max column, Pass@1"
        },
        {
          "name": "Codeforces",
          "score": 3052.0,
          "unit": "Rating",
          "note": "V4-Flash Max column, Rating"
        },
        {
          "name": "Terminal Bench 2.0",
          "score": 56.9,
          "unit": "%",
          "note": "V4-Flash Max column, Acc"
        },
        {
          "name": "SWE Verified",
          "score": 79.0,
          "unit": "%",
          "note": "V4-Flash Max column, Resolved"
        },
        {
          "name": "BrowseComp",
          "score": 73.2,
          "unit": "%",
          "note": "V4-Flash Max column, Pass@1"
        }
      ],
      "headline": {
        "metric": "GPQA-Diamond",
        "score": 88.1
      },
      "summary": "不是新模型，而是给 V4-Flash 同一份权重挂上 DSpark 投机解码模块，vLLM 加 --speculative-config、SGLang 加一个参数即可开启。",
      "breakthrough": "DSpark 投机解码模块化：改一个启动参数就能换解码吞吐，推理加速不再绑定权重格式。",
      "variants": [
        "DeepSeek-V4-Flash-DSpark"
      ]
    },
    {
      "id": "deepseek-v4-flash-0731",
      "repo": "deepseek-ai/DeepSeek-V4-Flash-0731",
      "name": "DeepSeek-V4-Flash-0731",
      "family": "LLM",
      "date": "2026-07-31",
      "tier": "major",
      "totalParams": "284B",
      "activatedParams": "13B",
      "contextLength": "1M",
      "license": "MIT",
      "downloads": 4393881,
      "likes": 3931,
      "storageBytes": 166888735421,
      "storageLabel": "155.4 GB",
      "paramsB": null,
      "activeB": null,
      "innovations": [
        "正式版取代预览",
        "Agentic 能力大幅提升",
        "DSpark 内置",
        "reasoning_effort 三档"
      ],
      "benchmarks": [
        {
          "name": "Terminal Bench 2.1",
          "score": 82.7,
          "unit": "%",
          "note": "DeepSeek-V4-Flash-0731 column"
        },
        {
          "name": "NL2Repo",
          "score": 54.2,
          "unit": "%",
          "note": "DeepSeek-V4-Flash-0731 column"
        },
        {
          "name": "Cybergym",
          "score": 76.7,
          "unit": "%",
          "note": "DeepSeek-V4-Flash-0731 column"
        },
        {
          "name": "DeepSWE",
          "score": 54.4,
          "unit": "%",
          "note": "DeepSeek-V4-Flash-0731 column"
        },
        {
          "name": "Toolathlon-Verified",
          "score": 70.3,
          "unit": "%",
          "note": "DeepSeek-V4-Flash-0731 column"
        },
        {
          "name": "Agents' Last Exam",
          "score": 25.2,
          "unit": "%",
          "note": "DeepSeek-V4-Flash-0731 column"
        },
        {
          "name": "AutomationBench Public",
          "score": 25.1,
          "unit": "%",
          "note": "DeepSeek-V4-Flash-0731 column"
        },
        {
          "name": "DSBench-FullStack",
          "score": 68.7,
          "unit": "%",
          "note": "internal full-stack development test set"
        },
        {
          "name": "DSBench-Hard",
          "score": 59.6,
          "unit": "%",
          "note": "internal test set of difficult coding-agent problems"
        }
      ],
      "headline": {
        "metric": "Terminal Bench 2.1",
        "score": 82.7
      },
      "summary": "Flash 的正式发布版，取代预览版：Agentic 能力大幅提升，并内置 DSpark 投机解码。Terminal Bench 2.1（82.7）与 DeepSWE（54.4）已超过 V4-Pro 预览版，尽管激活参数远小于它。",
      "breakthrough": "小激活参数反超上一档：13B 激活的 Flash 正式版在终端类 Agent 任务上压过 Pro 预览版。",
      "variants": [
        "DeepSeek-V4-Flash-0731"
      ]
    },
    {
      "id": "deepseek-v4-pro-0813",
      "repo": "deepseek-ai/DeepSeek-V4-Pro-0813",
      "name": "DeepSeek-V4-Pro-0813",
      "family": "LLM",
      "date": "2026-08-13",
      "tier": "flagship",
      "totalParams": "1.6T",
      "activatedParams": "49B",
      "contextLength": "1M",
      "license": "MIT",
      "downloads": 171782,
      "likes": 815,
      "storageBytes": 1781787608346,
      "storageLabel": "1.62 TB",
      "paramsB": null,
      "activeB": null,
      "innovations": [
        "正式版取代预览",
        "生产环境强化",
        "DSpark 内置",
        "HLE 带工具 60.0"
      ],
      "benchmarks": [
        {
          "name": "HLE (wo / w tools)",
          "score": 42.7,
          "unit": "/60",
          "note": "DeepSeek-V4-Pro-0813 column"
        },
        {
          "name": "Terminal Bench 2.1",
          "score": 87.9,
          "unit": "%",
          "note": "DeepSeek-V4-Pro-0813 column"
        },
        {
          "name": "NL2Repo",
          "score": 61.5,
          "unit": "%",
          "note": "DeepSeek-V4-Pro-0813 column"
        },
        {
          "name": "Cybergym",
          "score": 83.3,
          "unit": "%",
          "note": "DeepSeek-V4-Pro-0813 column"
        },
        {
          "name": "DeepSWE",
          "score": 62.7,
          "unit": "%",
          "note": "DeepSeek-V4-Pro-0813 column"
        },
        {
          "name": "Toolathlon-Verified",
          "score": 74.1,
          "unit": "%",
          "note": "DeepSeek-V4-Pro-0813 column"
        },
        {
          "name": "Agents' Last Exam",
          "score": 25.7,
          "unit": "%",
          "note": "DeepSeek-V4-Pro-0813 column"
        },
        {
          "name": "AutomationBench (Public)",
          "score": 31.8,
          "unit": "%",
          "note": "DeepSeek-V4-Pro-0813 column"
        },
        {
          "name": "DSBench-FullStack",
          "score": 71.1,
          "unit": "%",
          "note": "internal full-stack development test set"
        },
        {
          "name": "DSBench-Hard",
          "score": 67.2,
          "unit": "%",
          "note": "internal test set of difficult coding-agent problems"
        }
      ],
      "headline": {
        "metric": "Terminal Bench 2.1",
        "score": 87.9
      },
      "summary": "Pro 的正式发布版，取代预览版，Agentic 能力与生产环境表现显著提升，同样挂载 DSpark。所列基准全面超过 Pro 预览版，Terminal Bench 2.1 达 87.9、HLE 带工具 60.0。",
      "breakthrough": null,
      "variants": [
        "DeepSeek-V4-Pro-0813"
      ]
    },
    {
      "id": "deepseek-v4-flash-vision-exp",
      "repo": "deepseek-ai/DeepSeek-V4-Flash-Vision-Exp",
      "name": "DeepSeek-V4-Flash-Vision-Exp",
      "family": "VL",
      "date": "2026-08-31",
      "tier": "major",
      "totalParams": "284B",
      "activatedParams": "13B",
      "contextLength": "1M",
      "license": "MIT",
      "downloads": 400892,
      "likes": 862,
      "storageBytes": 167819616863,
      "storageLabel": "156.3 GB",
      "paramsB": null,
      "activeB": null,
      "innovations": [
        "视觉模块 + 继续训练",
        "DFlash 注意力",
        "Hyper-Connections",
        "DSpark 前向"
      ],
      "benchmarks": [
        {
          "name": "Terminal Bench 2.1",
          "score": 83.9,
          "unit": "%",
          "note": "text agent capability"
        },
        {
          "name": "NL2Repo",
          "score": 57.7,
          "unit": "%",
          "note": "text agent capability"
        },
        {
          "name": "Cybergym",
          "score": 75.3,
          "unit": "%",
          "note": "text agent capability"
        },
        {
          "name": "DeepSWE",
          "score": 59.3,
          "unit": "%",
          "note": "text agent capability"
        },
        {
          "name": "Toolathlon-Verified",
          "score": 75.9,
          "unit": "%",
          "note": "text agent capability"
        },
        {
          "name": "DSBench-Hard",
          "score": 63.6,
          "unit": "%",
          "note": "text agent capability"
        },
        {
          "name": "AutomationBench (Public)",
          "score": 25.7,
          "unit": "%",
          "note": "text agent capability"
        },
        {
          "name": "ApexBench (Pass@1)",
          "score": 36.5,
          "unit": "%",
          "note": "multimodal agent capability"
        },
        {
          "name": "Agents' Last Exam",
          "score": 27.3,
          "unit": "%",
          "note": "multimodal agent capability"
        },
        {
          "name": "Chartography",
          "score": 64.3,
          "unit": "%",
          "note": "multimodal agent capability"
        },
        {
          "name": "ZeroBench (Pass@5)",
          "score": 35.0,
          "unit": "%",
          "note": "multimodal agent capability"
        }
      ],
      "headline": {
        "metric": "Terminal Bench 2.1",
        "score": 83.9
      },
      "summary": "V4 家族首个实验性多模态模型：在 V4-Flash 架构上加视觉模块继续训练，多模态 Agent 能力明显提升，纯文本 Agent 任务基本持平。",
      "breakthrough": null,
      "variants": [
        "DeepSeek-V4-Flash-Vision-Exp"
      ]
    },
    {
      "id": "deepseek-v4.1-flash",
      "repo": "deepseek-ai/DeepSeek-V4.1-Flash",
      "name": "DeepSeek-V4.1-Flash",
      "family": "LLM",
      "date": "2026-09-10",
      "tier": "flagship",
      "totalParams": "552B + 196B Engram",
      "activatedParams": "8B prefill / 16B decode",
      "contextLength": "1M",
      "license": "MIT",
      "downloads": 6,
      "likes": 1537,
      "storageBytes": 510302811119,
      "storageLabel": "475.3 GB",
      "paramsB": 552.0,
      "activeB": 8.0,
      "innovations": [
        "CED 因果编码器-解码器",
        "CSA2 跨层共享 KV",
        "FP4 main KV cache",
        "SWA Bounded Replay",
        "Engram 条件记忆",
        "1M 上下文 / effort 1-100"
      ],
      "benchmarks": [
        {
          "name": "MMLU-Pro",
          "score": 74.1,
          "unit": "%",
          "note": "DeepSeek-V4.1-Flash-Base, EM, 5-shot"
        },
        {
          "name": "AGIEval",
          "score": 83.4,
          "unit": "%",
          "note": "DeepSeek-V4.1-Flash-Base, EM, 3-5-shot"
        },
        {
          "name": "C-Eval",
          "score": 92.1,
          "unit": "%",
          "note": "DeepSeek-V4.1-Flash-Base, EM, 5-shot"
        },
        {
          "name": "SimpleQA-Verified",
          "score": 42.3,
          "unit": "%",
          "note": "DeepSeek-V4.1-Flash-Base, EM, 25-shot"
        },
        {
          "name": "HumanEval",
          "score": 79.4,
          "unit": "%",
          "note": "DeepSeek-V4.1-Flash-Base, Pass@1, 0-shot"
        },
        {
          "name": "GSM8K",
          "score": 93.0,
          "unit": "%",
          "note": "DeepSeek-V4.1-Flash-Base, EM, 8-shot"
        },
        {
          "name": "LongBench-V2",
          "score": 45.2,
          "unit": "%",
          "note": "DeepSeek-V4.1-Flash-Base, EM, 1-shot"
        },
        {
          "name": "MMMU-Pro",
          "score": 56.5,
          "unit": "%",
          "note": "DeepSeek-V4.1-Flash-Base, EM, 4-shot"
        },
        {
          "name": "DocVQA",
          "score": 95.6,
          "unit": "%",
          "note": "DeepSeek-V4.1-Flash-Base, LLM-Judge, 4-shot"
        },
        {
          "name": "RefCOCO-avg",
          "score": 86.0,
          "unit": "%",
          "note": "DeepSeek-V4.1-Flash-Base, Acc@0.5, 0-shot"
        },
        {
          "name": "GPQA Diamond",
          "score": 90.9,
          "unit": "%",
          "note": "DS-V4.1-Flash, Pass@1"
        },
        {
          "name": "Codeforces",
          "score": 3471.0,
          "unit": "Rating",
          "note": "DS-V4.1-Flash, Rating"
        }
      ],
      "headline": {
        "metric": "GPQA-Diamond",
        "score": 90.9
      },
      "summary": "多模态 MoE：CED 因果编码器-解码器架构，prefill / decode 分别只激活 8B / 16B。CSA2 加 FP4 main KV cache 把全局 KV 压到约 890 bytes/token，约为 V4-Flash 的四分之一；再叠加 196B Engram 条件记忆与 DSpark。",
      "breakthrough": "CED + CSA2 + FP4 main KV + SWA Bounded Replay：四层同时压缩，全局 KV cache 只剩 890 bytes/token，已是初代模型的 1/437。",
      "variants": [
        "DeepSeek-V4.1-Flash"
      ]
    }
  ],
  "breakthroughs": [
    {
      "id": "deepseekmoe",
      "date": "2024-01-08",
      "label": "DeepSeekMoE",
      "name": "细粒度专家 + 共享专家",
      "releaseId": "deepseek-moe-16b-base",
      "lane": "架构",
      "mechanism": "把 FFN 切成更多更小的专家，再额外留出始终激活的共享专家隔离通用知识，路由器只需在细碎专家间做选择。",
      "impact": "同样算力下专家组合空间更大、通用知识又不被稀释，成为之后所有 DeepSeek 模型的骨架。",
      "magnitude": "16B 总参数 / 2.8B 激活"
    },
    {
      "id": "grpo",
      "date": "2024-02-05",
      "label": "GRPO",
      "name": "组相对策略优化",
      "releaseId": "deepseek-math-7b-instruct",
      "lane": "训练",
      "mechanism": "对同一问题采样一组回答，用组内相对得分当优势，直接丢掉与策略同规模的价值网络。",
      "impact": "RL 训练显存与工程复杂度大降，后来成为 R1 系列在超大规模上做推理 RL 的核心算法。",
      "magnitude": "去掉 critic 网络，RL 成本约减半"
    },
    {
      "id": "mla",
      "date": "2024-04-22",
      "label": "MLA",
      "name": "多头潜在注意力",
      "releaseId": "deepseek-v2",
      "lane": "架构",
      "mechanism": "把 K/V 投影到低维潜向量缓存，推理时再解压成多头，缓存的是压缩后的潜变量而不是完整 KV。",
      "impact": "长上下文推理的显存与带宽开销直接降一个量级，此后被各大开源模型广泛采用。",
      "magnitude": "KV cache ↓93.3%，吞吐 ×5.76"
    },
    {
      "id": "aux-loss-free",
      "date": "2024-12-25",
      "label": "Aux-loss-free",
      "name": "无辅助损失负载均衡",
      "releaseId": "deepseek-v3",
      "lane": "训练",
      "mechanism": "用可学习的偏置项调节专家路由概率来均衡负载，而不是在损失里加一项惩罚。",
      "impact": "负载均衡不再以牺牲模型质量为代价，MoE 训练少了一个长期存在的两难。",
      "magnitude": "均衡与性能不再互斥"
    },
    {
      "id": "fp8-training",
      "date": "2024-12-25",
      "label": "FP8",
      "name": "超大规模 FP8 混合精度训练",
      "releaseId": "deepseek-v3",
      "lane": "训练",
      "mechanism": "矩阵乘法用 FP8、累积与关键算子保持高精度，配合细粒度量化与在线 scale 更新稳定训练。",
      "impact": "首个在 671B 规模跑通的 FP8 训练，把单位 token 的训练成本压下来，也让后来 UE8M0 路线成为可能。",
      "magnitude": "14.8T token / 2.788M H800 小时"
    },
    {
      "id": "mtp",
      "date": "2024-12-25",
      "label": "MTP",
      "name": "多 token 预测",
      "releaseId": "deepseek-v3",
      "lane": "推理",
      "mechanism": "训练时让模型一次预测多个未来 token，推理时把这些头改造成投机解码的草稿器。",
      "impact": "既提升训练信号密度，又白送一个推理加速器，是「训练设计即推理优化」的典型例子。",
      "magnitude": "V3 论文报告解码吞吐约 ×1.8"
    },
    {
      "id": "pure-rl",
      "date": "2025-01-20",
      "label": "RL w/o SFT",
      "name": "纯强化学习激发推理",
      "releaseId": "deepseek-r1",
      "lane": "后训练",
      "mechanism": "直接在基座模型上做大规模 RL，不先做 SFT，只靠可验证答案的对错作奖励。",
      "impact": "自验证、反思、长思维链自发涌现，首次证明推理能力可以「训出来」而不是「教出来」。",
      "magnitude": "推理能力由 RL 自发涌现"
    },
    {
      "id": "reasoning-distill",
      "date": "2025-01-20",
      "label": "Distill",
      "name": "推理能力蒸馏到稠密模型",
      "releaseId": "deepseek-r1",
      "lane": "后训练",
      "mechanism": "用大模型生成的 80 万条推理数据去微调 Qwen / Llama 稠密模型，让小模型继承长链推理。",
      "impact": "推理能力不再是大模型的专属，32B 稠密模型即可对标当时的闭源推理小模型。",
      "magnitude": "32B 蒸馏模型 AIME 2024 pass@1 72.6%"
    },
    {
      "id": "hybrid-thinking",
      "date": "2025-08-21",
      "label": "Hybrid Think",
      "name": "混合推理双模式",
      "releaseId": "deepseek-v3.1",
      "lane": "推理",
      "mechanism": "同一份权重通过 chat template 切换 thinking / non-thinking，配合 UE8M0 FP8 scale 训练权重与激活。",
      "impact": "成本与质量变成同一条连续带上的选择，同时为国产芯片的 microscaling 格式预留了接口。",
      "magnitude": "一份权重两档模式"
    },
    {
      "id": "dsa",
      "date": "2025-09-29",
      "label": "DSA",
      "name": "细粒度稀疏注意力",
      "releaseId": "deepseek-v3.2-exp",
      "lane": "架构",
      "mechanism": "用 lightning indexer 先给每个 query 选出最相关的 top-k token，注意力只在被选中的部分计算。",
      "impact": "长文本注意力从全连接改成「先选后算」，训练与推理的长上下文成本大幅下降而质量基本不掉。",
      "magnitude": "长文本效率跃升，基准与 V3.1 持平"
    },
    {
      "id": "optical-compression",
      "date": "2025-10-17",
      "label": "OCR Context",
      "name": "上下文光学压缩",
      "releaseId": "deepseek-ocr",
      "lane": "多模态",
      "mechanism": "把文字渲染成图再编码成视觉 token，用远少于文本 token 的数量承载同样的信息。",
      "impact": "为「上下文不是越长越好、而是换一种表示」打开新路，OCR 从工具变成上下文压缩器。",
      "magnitude": "等量文本用更少的视觉 token"
    },
    {
      "id": "self-verifiable-math",
      "date": "2025-11-27",
      "label": "Verifier",
      "name": "可自验证数学推理",
      "releaseId": "deepseek-math-v2",
      "lane": "后训练",
      "mechanism": "证明生成器与 LLM 验证器分开训练，验证器当奖励模型，并靠扩展验证算力自动标注难核验的证明。",
      "impact": "把「答案对不对」变成可扩展的监督信号，数学能力随之越过竞赛金牌线。",
      "magnitude": "IMO 2025 金牌，Putnam 2024 118/120"
    },
    {
      "id": "agentic-synthesis",
      "date": "2025-12-01",
      "label": "Agentic RL",
      "name": "大规模 Agentic 任务合成",
      "releaseId": "deepseek-v3.2",
      "lane": "后训练",
      "mechanism": "自动合成大批可验证的智能体任务环境，配合可扩展 RL 框架做大规模训练。",
      "impact": "训练信号从对话搬到真实任务环境，智能体能力成为主线，也为后来的沙箱集群铺路。",
      "magnitude": "IMO / IOI 2025 金牌表现（Speciale）"
    },
    {
      "id": "visual-causal-flow",
      "date": "2026-01-27",
      "label": "VCF",
      "name": "Visual Causal Flow",
      "releaseId": "deepseek-ocr-2",
      "lane": "多模态",
      "mechanism": "让视觉编码按因果阅读顺序推进，而不是按固定栅格扫描，并保留动态分辨率。",
      "impact": "视觉编码开始向人类的阅读方式靠拢，文档理解与后续多模态模型共享同一条路线。",
      "magnitude": "动态分辨率 + 光学压缩"
    },
    {
      "id": "csa-hca",
      "date": "2026-04-22",
      "label": "CSA + HCA",
      "name": "混合压缩注意力 + mHC",
      "releaseId": "deepseek-v4-flash",
      "lane": "架构",
      "mechanism": "压缩稀疏注意力与重压缩注意力并行，配合流形约束超连接（mHC）与 Muon 优化器。",
      "impact": "百万上下文第一次不需要为长度付出线性代价，KV 与 FLOPs 同时掉一个数量级。",
      "magnitude": "1M 上下文：27% FLOPs、10% KV"
    },
    {
      "id": "dspark",
      "date": "2026-06-27",
      "label": "DSpark",
      "name": "模块化投机解码",
      "releaseId": "deepseek-v4-flash-dspark",
      "lane": "推理",
      "mechanism": "不改权重，只在同一 checkpoint 上挂一个投机解码模块，启动时加一个参数即可启用。",
      "impact": "解码加速从「重训模型」变成「换启动参数」，推理优化与模型发布彻底解耦。",
      "magnitude": "vLLM / SGLang 单参数开启"
    },
    {
      "id": "ced",
      "date": "2026-09-10",
      "label": "CED",
      "name": "因果编码器-解码器架构",
      "releaseId": "deepseek-v4.1-flash",
      "lane": "架构",
      "mechanism": "把网络拆成 20 层编码器与 20 层解码器，decoder 的全局 KV 由第 20 层 hidden state 投影而来，prefill 只激活 8B、decode 只激活 16B。",
      "impact": "预填充与解码被解耦成两种工作负载，各自只激活需要的部分，prefill 计算量约减半。",
      "magnitude": "prefill 8B / decode 16B 激活"
    },
    {
      "id": "csa2",
      "date": "2026-09-10",
      "label": "CSA2",
      "name": "跨层共享 KV 与索引",
      "releaseId": "deepseek-v4.1-flash",
      "lane": "架构",
      "mechanism": "跨层共享 main KV 与 indexer K，复用 Top-K 索引；每层可选 Full / Reindex / Reuse 三种模式，深层由分层稀疏索引器接管。",
      "impact": "索引成本从随上下文线性增长变成常数，跨层复用让深层的稀疏注意力几乎免费。",
      "magnitude": "indexer 成本线性 → 常数"
    },
    {
      "id": "fp4-kv",
      "date": "2026-09-10",
      "label": "FP4 KV",
      "name": "FP4 主 KV 缓存",
      "releaseId": "deepseek-v4.1-flash",
      "lane": "推理",
      "mechanism": "main KV 用 MXFP4（E2M1）加每 16 通道一个 E4M3 scale，省掉二级 global scale，在 RoPE 之后量化；SWA 部分仍保持 FP8。",
      "impact": "KV 存储再砍一半，且精度损失可控，长上下文推理的显存天花板被再次抬高。",
      "magnitude": "main KV 存储近减半"
    },
    {
      "id": "swb-replay",
      "date": "2026-09-10",
      "label": "SWB Replay",
      "name": "有界回放的滑窗 KV",
      "releaseId": "deepseek-v4.1-flash",
      "lane": "推理",
      "mechanism": "滑窗 KV 放进各机器 10% 的 host DRAM 组成分布式池，未命中时只回放最近一个窗口的 token。",
      "impact": "用便宜的宿主内存承接长上下文的冷 KV，整机显存不再是唯一约束。",
      "magnitude": "全局 KV 890 bytes/token，约 V4-Flash 的 1/4"
    },
    {
      "id": "engram",
      "date": "2026-09-10",
      "label": "Engram",
      "name": "条件记忆模块",
      "releaseId": "deepseek-v4.1-flash",
      "lane": "架构",
      "mechanism": "用 n-gram（2/3/4）查表式的条件记忆挂在第 1 与第 14 层，8 个 hash head，196B 参数以 FP8 存放。",
      "impact": "把「记住常见片段」这件事从注意力里外包出去，注意力可以专注在真正需要推理的位置。",
      "magnitude": "196B 参数的条件记忆"
    },
    {
      "id": "single-pass-mhc",
      "date": "2026-09-10",
      "label": "mHC",
      "name": "单遍残差混流",
      "releaseId": "deepseek-v4.1-flash",
      "lane": "训练",
      "mechanism": "把残差更新、输入混合与系数预测融合成一次单遍计算，残差读写降到理论下界 (2n+2)d。",
      "impact": "激活值的内存流量减半，长序列训练的带宽瓶颈被松开，训练与推理都直接受益。",
      "magnitude": "残差读写 (3n+2)d → (2n+2)d"
    },
    {
      "id": "effort-dial",
      "date": "2026-09-10",
      "label": "Effort 1-100",
      "name": "可控推理强度",
      "releaseId": "deepseek-v4.1-flash",
      "lane": "推理",
      "mechanism": "推理强度做成 1 到 100 的标量，公开 API 对应 low=50 / high=75 / max=100。",
      "impact": "同一模型按任务价值分配算力：effort 从 25 提到 100，8 项推理基准均分从 67.1% 涨到 76.3%。",
      "magnitude": "effort 25→100：67.1% → 76.3%"
    },
    {
      "id": "dsec",
      "date": "2026-09-10",
      "label": "DSec",
      "name": "百万级并发沙箱",
      "releaseId": "deepseek-v4.1-flash",
      "lane": "后训练",
      "mechanism": "自研安全沙箱，用 AppArmor 与 eBPF 做隔离，单机容器密度从 1,000 提到 2,500 以上。",
      "impact": "Agentic RL 的数据瓶颈从「任务不够」变成「环境不够」，这一步把环境供给做成了基础设施。",
      "magnitude": "单机密度 1k → 2,500+"
    }
  ]
} as Dataset
