/* Generated by scripts/gen_orgs.py — do not edit by hand. */
import type { Dataset, OrgMeta } from './types'
import { dataset as deepseek } from './deepseek'
import { dataset as zai } from './zai'
import { dataset as kimi } from './kimi'

/** Labs the chronicle tracks, in switch order. */
export const ORGS: OrgMeta[] = [
  {
    "id": "deepseek-ai",
    "name": "DeepSeek",
    "short": "DeepSeek",
    "blurb": "从 7B 稠密模型到 671B 稀疏专家，MLA / GRPO / V4 系列的开源路线",
    "hue": 190
  },
  {
    "id": "zai-org",
    "name": "智谱 GLM",
    "short": "GLM",
    "blurb": "GLM 系列：从 ChatGLM 到 GLM-5.3，全栈开源（语言 / 视觉 / 代码 / 视频 / 语音）",
    "hue": 265
  },
  {
    "id": "moonshotai",
    "name": "月之暗面 Kimi",
    "short": "Kimi",
    "blurb": "Kimi 系列：Muon 优化器与超稀疏 MoE 路线的开源权重",
    "hue": 42
  }
]

export const DATASETS: Dataset[] = [deepseek, zai, kimi]

/** Merge the selected labs into one dataset so every view can render them
 *  side by side; per-lab colour still comes from the release's org badge. */
export function buildDataset(active: Set<string>): Dataset {
  const list = DATASETS.filter((d) => active.has(d.org))
  if (list.length === 1) return list[0]
  const releases = list.flatMap((d) => d.releases.map((r) => ({ ...r, org: d.org })))
  const breakthroughs = list.flatMap((d) =>
    d.breakthroughs.map((b) => ({ ...b, id: `${d.org}-${b.id}` })),
  )
  releases.sort((a, b) => a.date.localeCompare(b.date))
  breakthroughs.sort((a, b) => a.date.localeCompare(b.date))
  return {
    org: 'combined',
    orgName: list.map((d) => d.orgName).join(' · '),
    snapshot: list[0].snapshot,
    repoCount: list.reduce((n, d) => n + d.repoCount, 0),
    releases,
    breakthroughs,
  }
}
