/* Generated by scripts/gen_orgs.py — do not edit by hand. */
import type { Dataset } from './types'

export const dataset: Dataset = {
  "org": "moonshotai",
  "orgName": "月之暗面 Kimi",
  "snapshot": "2026-09-13",
  "repoCount": 19,
  "releases": [
    {
      "id": "moonlight-16b-a3b-instruct",
      "repo": "moonshotai/Moonlight-16B-A3B-Instruct",
      "org": "moonshotai",
      "name": "Moonlight-16B-A3B-Instruct",
      "family": "LLM",
      "date": "2025-02-22",
      "tier": "flagship",
      "totalParams": "16B",
      "paramsSource": "card",
      "activatedParams": "3B",
      "contextLength": "8K",
      "license": "mit",
      "downloads": 58542,
      "likes": 204,
      "storageBytes": 31923674742,
      "storageLabel": "31.9 GB",
      "paramsB": 16.0,
      "activeB": 3.0,
      "innovations": [
        "Muon 优化器",
        "权重衰减(Weight Decay)",
        "一致 RMS 更新",
        "ZeRO-1 分布式 Muon",
        "3B/16B MoE"
      ],
      "benchmarks": [
        {
          "name": "MMLU",
          "score": 70.0,
          "unit": "%",
          "note": ""
        },
        {
          "name": "MMLU-pro",
          "score": 42.4,
          "unit": "%",
          "note": ""
        },
        {
          "name": "BBH",
          "score": 65.2,
          "unit": "%",
          "note": ""
        },
        {
          "name": "TriviaQA",
          "score": 66.3,
          "unit": "%",
          "note": "full set"
        },
        {
          "name": "HumanEval",
          "score": 48.1,
          "unit": "%",
          "note": ""
        },
        {
          "name": "MBPP",
          "score": 63.8,
          "unit": "%",
          "note": ""
        },
        {
          "name": "GSM8K",
          "score": 77.4,
          "unit": "%",
          "note": ""
        },
        {
          "name": "MATH",
          "score": 45.3,
          "unit": "%",
          "note": ""
        },
        {
          "name": "CMath",
          "score": 81.1,
          "unit": "%",
          "note": ""
        },
        {
          "name": "C-Eval",
          "score": 77.2,
          "unit": "%",
          "note": ""
        },
        {
          "name": "CMMLU",
          "score": 78.2,
          "unit": "%",
          "note": ""
        }
      ],
      "headline": {
        "metric": "CMath",
        "score": 81.1
      },
      "summary": "用 Muon 优化器训练的 3B/16B MoE 模型，5.7T token 预训练，验证了 Muon 在大规模训练上的可扩展性。",
      "breakthrough": "首次证明 Muon 优化器可用于大规模 LLM 训练：约 2x 样本效率、约 52% 训练 FLOPs 达到 AdamW 同等性能",
      "variants": [
        "Moonlight-16B-A3B"
      ]
    },
    {
      "id": "kimi-vl-a3b-instruct",
      "repo": "moonshotai/Kimi-VL-A3B-Instruct",
      "org": "moonshotai",
      "name": "Kimi-VL-A3B-Instruct",
      "family": "VL",
      "date": "2025-04-09",
      "tier": "flagship",
      "totalParams": "16B",
      "paramsSource": "card",
      "activatedParams": "3B",
      "contextLength": "128K",
      "license": "mit",
      "downloads": 162717,
      "likes": 283,
      "storageBytes": 32822309117,
      "storageLabel": "32.8 GB",
      "paramsB": 16.0,
      "activeB": 3.0,
      "innovations": [
        "MoE 视觉语言模型",
        "MoonViT 原生分辨率视觉编码器",
        "MLP 投影器",
        "128K 长上下文",
        "GUI/OS Agent 能力"
      ],
      "benchmarks": [
        {
          "name": "MMMU-Val",
          "score": 57.0,
          "unit": "%",
          "note": "Pass@1"
        },
        {
          "name": "VideoMMMU",
          "score": 52.6,
          "unit": "%",
          "note": "Pass@1"
        },
        {
          "name": "MMVU-Val",
          "score": 52.2,
          "unit": "%",
          "note": "Pass@1"
        },
        {
          "name": "MMBench-EN-v1.1",
          "score": 83.1,
          "unit": "%",
          "note": "Acc"
        },
        {
          "name": "MMStar",
          "score": 61.3,
          "unit": "%",
          "note": "Acc"
        },
        {
          "name": "MMVet",
          "score": 66.7,
          "unit": "%",
          "note": "Pass@1"
        },
        {
          "name": "RealWorldQA",
          "score": 68.1,
          "unit": "%",
          "note": "Acc"
        },
        {
          "name": "AI2D",
          "score": 84.9,
          "unit": "%",
          "note": "Acc"
        },
        {
          "name": "BLINK",
          "score": 57.3,
          "unit": "%",
          "note": "Acc"
        },
        {
          "name": "MathVista",
          "score": 68.7,
          "unit": "%",
          "note": "Pass@1"
        },
        {
          "name": "MathVision",
          "score": 21.4,
          "unit": "%",
          "note": "Pass@1"
        },
        {
          "name": "InfoVQA",
          "score": 83.2,
          "unit": "%",
          "note": "Acc"
        },
        {
          "name": "OCRBench",
          "score": 867.0,
          "unit": "%",
          "note": "Acc"
        },
        {
          "name": "ScreenSpot-V2",
          "score": 92.8,
          "unit": "%",
          "note": "Acc"
        },
        {
          "name": "ScreenSpot-Pro",
          "score": 34.5,
          "unit": "%",
          "note": "Acc"
        },
        {
          "name": "OSWorld",
          "score": 8.22,
          "unit": "%",
          "note": "Pass@1"
        },
        {
          "name": "WindowsAgentArena",
          "score": 10.4,
          "unit": "%",
          "note": "Pass@1"
        },
        {
          "name": "MMLongBench-Doc",
          "score": 35.1,
          "unit": "%",
          "note": "Acc"
        },
        {
          "name": "Video-MME",
          "score": 67.8,
          "unit": "%",
          "note": "w/o sub."
        },
        {
          "name": "Video-MME",
          "score": 72.6,
          "unit": "%",
          "note": "w/ sub."
        },
        {
          "name": "MLVU-MCQ",
          "score": 74.2,
          "unit": "%",
          "note": "Acc"
        },
        {
          "name": "LongVideoBench",
          "score": 64.5,
          "unit": "%",
          "note": "val"
        },
        {
          "name": "EgoSchema",
          "score": 78.5,
          "unit": "%",
          "note": "full"
        },
        {
          "name": "VSI-Bench",
          "score": 37.4,
          "unit": "%",
          "note": ""
        },
        {
          "name": "TOMATO",
          "score": 31.7,
          "unit": "%",
          "note": ""
        }
      ],
      "headline": {
        "metric": "OCRBench",
        "score": 867.0
      },
      "summary": "激活仅 2.8B 参数的高效 MoE VLM（16B 总参/3B 激活），128K 上下文，具备长视频/长文档与 OS Agent 能力。",
      "breakthrough": "以 2.8B+0.4B 激活参数在 ScreenSpot-V2(92.8)、OSWorld(8.22) 等 GUI Agent 任务上超过 GPT-4o",
      "variants": [
        "Kimi-VL-A3B-Thinking",
        "Kimi-VL-A3B-Thinking-2506"
      ]
    },
    {
      "id": "kimi-vl-a3b-thinking",
      "repo": "moonshotai/Kimi-VL-A3B-Thinking",
      "org": "moonshotai",
      "name": "Kimi-VL-A3B-Thinking",
      "family": "VL",
      "date": "2025-04-09",
      "tier": "minor",
      "totalParams": "16B",
      "paramsSource": "card",
      "activatedParams": "3B",
      "contextLength": "128K",
      "license": "mit",
      "downloads": 16242,
      "likes": 454,
      "storageBytes": 32820262484,
      "storageLabel": "32.8 GB",
      "paramsB": 16.0,
      "activeB": 3.0,
      "innovations": [
        "长思维链(CoT) SFT",
        "强化学习(RL)",
        "MoE 视觉语言模型",
        "2.8B 激活 LLM"
      ],
      "benchmarks": [
        {
          "name": "MMMU",
          "score": 61.7,
          "unit": "%",
          "note": "val, Pass@1"
        },
        {
          "name": "MathVision",
          "score": 36.8,
          "unit": "%",
          "note": "full, Pass@1"
        },
        {
          "name": "MathVista",
          "score": 71.3,
          "unit": "%",
          "note": "mini, Pass@1"
        }
      ],
      "headline": {
        "metric": "MathVista",
        "score": 71.3
      },
      "summary": "Kimi-VL 的长思考变体，经长 CoT SFT + RL 训练，在 2.8B 激活参数下取得强多模态推理能力。",
      "breakthrough": "以 2.8B 激活参数在多模态数学推理上匹配 30B/70B 级开源 VLM（MathVision 36.8）",
      "variants": [
        "Kimi-VL-A3B-Instruct",
        "Kimi-VL-A3B-Thinking-2506"
      ]
    },
    {
      "id": "moonvit-so-400m",
      "repo": "moonshotai/MoonViT-SO-400M",
      "org": "moonshotai",
      "name": "MoonViT-SO-400M",
      "family": "VL",
      "date": "2025-04-10",
      "tier": "major",
      "totalParams": null,
      "paramsSource": null,
      "activatedParams": null,
      "contextLength": null,
      "license": "mit",
      "downloads": 2784,
      "likes": 95,
      "storageBytes": 834303795,
      "storageLabel": "834.3 MB",
      "paramsB": null,
      "activeB": null,
      "innovations": [
        "原生分辨率视觉编码器",
        "由 SigLIP-SO-400M 初始化并继续预训练",
        "与 Kimi-VL 解耦独立发布"
      ],
      "benchmarks": [],
      "headline": null,
      "summary": "从 Kimi-VL-A3B-Instruct 中拆出的原生分辨率视觉编码器，初始化自 SigLIP-SO-400M；模型卡未印参数量，故参数字段为 null。",
      "breakthrough": null,
      "variants": []
    },
    {
      "id": "kimi-audio-7b-instruct",
      "repo": "moonshotai/Kimi-Audio-7B-Instruct",
      "org": "moonshotai",
      "name": "Kimi-Audio-7B-Instruct",
      "family": "Audio",
      "date": "2025-04-25",
      "tier": "major",
      "totalParams": null,
      "paramsSource": null,
      "activatedParams": null,
      "contextLength": null,
      "license": "mit",
      "downloads": 12991,
      "likes": 417,
      "storageBytes": 42595842074,
      "storageLabel": "42.6 GB",
      "paramsB": null,
      "activeB": null,
      "innovations": [
        "混合音频输入（连续声学+离散语义 token）",
        "并行文本/音频输出头",
        "flow matching 流式检测器",
        "1300万小时音频预训练"
      ],
      "benchmarks": [],
      "headline": null,
      "summary": "统一的音频基础模型，覆盖 ASR/AQA/AAC/SER/SEC 与端到端语音对话；模型卡未印参数量（仅模型名含 7B），故参数字段为 null。",
      "breakthrough": null,
      "variants": [
        "Kimi-Audio-7B"
      ]
    },
    {
      "id": "kimi-dev-72b",
      "repo": "moonshotai/Kimi-Dev-72B",
      "org": "moonshotai",
      "name": "Kimi-Dev-72B",
      "family": "Coder",
      "date": "2025-06-16",
      "tier": "major",
      "totalParams": null,
      "paramsSource": null,
      "activatedParams": null,
      "contextLength": null,
      "license": "mit",
      "downloads": 3628,
      "likes": 393,
      "storageBytes": 145427084148,
      "storageLabel": "145.4 GB",
      "paramsB": null,
      "activeB": null,
      "innovations": [
        "大规模强化学习",
        "Docker 中真实仓库打补丁",
        "全测试套件通过才给奖励"
      ],
      "benchmarks": [
        {
          "name": "SWE-bench Verified",
          "score": 60.4,
          "unit": "%",
          "note": "开源模型 SOTA"
        }
      ],
      "headline": {
        "metric": "SWE-bench Verified",
        "score": 60.4
      },
      "summary": "面向软件工程问题解决的编码 LLM（base_model 为 Qwen/Qwen2.5-72B）；模型卡未印参数量，故参数字段为 null。",
      "breakthrough": "SWE-bench Verified 达 60.4%，刷新开源模型 SOTA",
      "variants": []
    },
    {
      "id": "kimi-vl-a3b-thinking-2506",
      "repo": "moonshotai/Kimi-VL-A3B-Thinking-2506",
      "org": "moonshotai",
      "name": "Kimi-VL-A3B-Thinking-2506",
      "family": "VL",
      "date": "2025-06-21",
      "tier": "major",
      "totalParams": "16B",
      "paramsSource": "inferred",
      "activatedParams": "3B",
      "contextLength": "128K",
      "license": "mit",
      "downloads": 29685,
      "likes": 383,
      "storageBytes": 32821079324,
      "storageLabel": "32.8 GB",
      "paramsB": 16.0,
      "activeB": 3.0,
      "innovations": [
        "更少 think token(+准确率)",
        "单图 3.2M 像素高分辨率",
        "视频推理增强",
        "MoE 视觉语言模型"
      ],
      "benchmarks": [
        {
          "name": "MMBench-EN-v1.1",
          "score": 84.4,
          "unit": "%",
          "note": "Acc"
        },
        {
          "name": "RealWorldQA",
          "score": 70.0,
          "unit": "%",
          "note": "Acc"
        },
        {
          "name": "OCRBench",
          "score": 869.0,
          "unit": "%",
          "note": "Acc"
        },
        {
          "name": "MMStar",
          "score": 70.4,
          "unit": "%",
          "note": "Acc"
        },
        {
          "name": "MMVet",
          "score": 78.1,
          "unit": "%",
          "note": "Acc"
        },
        {
          "name": "MMMU",
          "score": 64.0,
          "unit": "%",
          "note": "val, Pass@1"
        },
        {
          "name": "MMMU-Pro",
          "score": 46.3,
          "unit": "%",
          "note": "Pass@1"
        },
        {
          "name": "MATH-Vision",
          "score": 56.9,
          "unit": "%",
          "note": "Pass@1"
        },
        {
          "name": "MathVista_MINI",
          "score": 80.1,
          "unit": "%",
          "note": "Pass@1"
        },
        {
          "name": "VideoMMMU",
          "score": 65.2,
          "unit": "%",
          "note": "Pass@1"
        },
        {
          "name": "MMVU",
          "score": 57.5,
          "unit": "%",
          "note": "Pass@1"
        },
        {
          "name": "Video-MME",
          "score": 71.9,
          "unit": "%",
          "note": "w/ sub."
        },
        {
          "name": "ScreenSpot-Pro",
          "score": 52.8,
          "unit": "%",
          "note": "Acc"
        },
        {
          "name": "ScreenSpot-V2",
          "score": 91.4,
          "unit": "%",
          "note": "Acc"
        },
        {
          "name": "OSWorld-G",
          "score": 52.5,
          "unit": "%",
          "note": "Acc"
        },
        {
          "name": "MMLongBench-DOC",
          "score": 42.1,
          "unit": "%",
          "note": "Acc"
        },
        {
          "name": "V* Benchmark",
          "score": 83.2,
          "unit": "%",
          "note": "w/o extra tools"
        },
        {
          "name": "MMLU",
          "score": 82.0,
          "unit": "%",
          "note": ""
        },
        {
          "name": "MMLU-Pro",
          "score": 68.5,
          "unit": "%",
          "note": ""
        },
        {
          "name": "MATH",
          "score": 91.8,
          "unit": "%",
          "note": ""
        },
        {
          "name": "GPQA-Diamond",
          "score": 42.3,
          "unit": "%",
          "note": ""
        }
      ],
      "headline": {
        "metric": "OCRBench",
        "score": 869.0
      },
      "summary": "Kimi-VL-A3B-Thinking 的升级版：base_model 指向 Kimi-VL-A3B-Instruct（同代 16B 总参/3B 激活），上下文长度按卡内 VLLM 示例 max_model_len=131072(=128K) 记为 128K；本卡未印参数量表，参数与上下文档为同代推断。",
      "breakthrough": "多模态推理大幅提升并降低 20% 思维长度：MathVision 36.8→56.9，单图支持 3.2M 像素（4x）",
      "variants": [
        "Kimi-VL-A3B-Instruct",
        "Kimi-VL-A3B-Thinking"
      ]
    },
    {
      "id": "kimi-k2-base",
      "repo": "moonshotai/Kimi-K2-Base",
      "org": "moonshotai",
      "name": "Kimi-K2-Base",
      "family": "LLM",
      "date": "2025-07-03",
      "tier": "major",
      "totalParams": "1T",
      "paramsSource": "card",
      "activatedParams": "32B",
      "contextLength": "128K",
      "license": "modified-mit",
      "downloads": 12671,
      "likes": 306,
      "storageBytes": 2058417158863,
      "storageLabel": "2.1 TB",
      "paramsB": 1000.0,
      "activeB": 32.0,
      "innovations": [
        "MuonClip 优化器",
        "MoE 1T 总参/32B 激活",
        "MLA 注意力",
        "384 专家选 8",
        "15.5T token 预训练零不稳定"
      ],
      "benchmarks": [
        {
          "name": "MMLU",
          "score": 87.8,
          "unit": "%",
          "note": "EM, 5-shot"
        },
        {
          "name": "MMLU-pro",
          "score": 69.2,
          "unit": "%",
          "note": "EM, 5-shot"
        },
        {
          "name": "MMLU-redux-2.0",
          "score": 90.2,
          "unit": "%",
          "note": "EM, 5-shot"
        },
        {
          "name": "SimpleQA",
          "score": 35.3,
          "unit": "%",
          "note": "Correct, 5-shot"
        },
        {
          "name": "TriviaQA",
          "score": 85.1,
          "unit": "%",
          "note": "EM, 5-shot"
        },
        {
          "name": "GPQA-Diamond",
          "score": 48.1,
          "unit": "%",
          "note": "Avg@8, 5-shot"
        },
        {
          "name": "SuperGPQA",
          "score": 44.7,
          "unit": "%",
          "note": "EM, 5-shot"
        },
        {
          "name": "LiveCodeBench v6",
          "score": 26.3,
          "unit": "%",
          "note": "Pass@1, 1-shot"
        },
        {
          "name": "EvalPlus",
          "score": 80.3,
          "unit": "%",
          "note": "Pass@1"
        },
        {
          "name": "MATH",
          "score": 70.2,
          "unit": "%",
          "note": "EM, 4-shot"
        },
        {
          "name": "GSM8k",
          "score": 92.1,
          "unit": "%",
          "note": "EM, 8-shot"
        },
        {
          "name": "C-Eval",
          "score": 92.5,
          "unit": "%",
          "note": "EM, 5-shot"
        },
        {
          "name": "CSimpleQA",
          "score": 77.6,
          "unit": "%",
          "note": "Correct, 5-shot"
        }
      ],
      "headline": {
        "metric": "C-Eval",
        "score": 92.5
      },
      "summary": "Kimi K2 的基座模型：1T 总参/32B 激活的 MoE，用 Muon 优化器在 15.5T token 上预训练且训练全程无失稳。",
      "breakthrough": "MuonClip 优化器把 Muon 首次扩展到 1T 参数 MoE 规模，实现 15.5T token 零训练不稳定",
      "variants": [
        "Kimi-K2-Instruct",
        "Kimi-K2-Instruct-0905"
      ]
    },
    {
      "id": "kimi-k2-instruct",
      "repo": "moonshotai/Kimi-K2-Instruct",
      "org": "moonshotai",
      "name": "Kimi-K2-Instruct",
      "family": "LLM",
      "date": "2025-07-11",
      "tier": "flagship",
      "totalParams": "1T",
      "paramsSource": "card",
      "activatedParams": "32B",
      "contextLength": "128K",
      "license": "modified-mit",
      "downloads": 184577,
      "likes": 2377,
      "storageBytes": 1029226387740,
      "storageLabel": "1.0 TB",
      "paramsB": 1000.0,
      "activeB": 32.0,
      "innovations": [
        "MuonClip 优化器",
        "MoE 1T 总参/32B 激活",
        "MLA 注意力",
        "Agentic 工具调用",
        "block-fp8 权重"
      ],
      "benchmarks": [
        {
          "name": "SWE-bench Verified",
          "score": 51.8,
          "unit": "%",
          "note": "Agentless, Single Patch w/o Test"
        },
        {
          "name": "SWE-bench Verified",
          "score": 65.8,
          "unit": "%",
          "note": "Agentic, single attempt"
        },
        {
          "name": "SWE-bench Verified",
          "score": 71.6,
          "unit": "%",
          "note": "Agentic, multiple attempts"
        },
        {
          "name": "SWE-bench Multilingual",
          "score": 47.3,
          "unit": "%",
          "note": "Agentic, single attempt"
        },
        {
          "name": "LiveCodeBench v6",
          "score": 53.7,
          "unit": "%",
          "note": "Pass@1"
        },
        {
          "name": "OJBench",
          "score": 27.1,
          "unit": "%",
          "note": "Pass@1"
        },
        {
          "name": "MultiPL-E",
          "score": 85.7,
          "unit": "%",
          "note": "Pass@1"
        },
        {
          "name": "TerminalBench",
          "score": 30.0,
          "unit": "%",
          "note": "Inhouse Framework, Acc"
        },
        {
          "name": "TerminalBench",
          "score": 25.0,
          "unit": "%",
          "note": "Terminus, Acc"
        },
        {
          "name": "Aider-Polyglot",
          "score": 60.0,
          "unit": "%",
          "note": "Acc"
        },
        {
          "name": "Tau2 retail",
          "score": 70.6,
          "unit": "%",
          "note": "Avg@4"
        },
        {
          "name": "Tau2 airline",
          "score": 56.5,
          "unit": "%",
          "note": "Avg@4"
        },
        {
          "name": "Tau2 telecom",
          "score": 65.8,
          "unit": "%",
          "note": "Avg@4"
        },
        {
          "name": "AceBench",
          "score": 76.5,
          "unit": "%",
          "note": "Acc"
        },
        {
          "name": "AIME 2024",
          "score": 69.6,
          "unit": "%",
          "note": "Avg@64"
        },
        {
          "name": "AIME 2025",
          "score": 49.5,
          "unit": "%",
          "note": "Avg@64"
        },
        {
          "name": "MATH-500",
          "score": 97.4,
          "unit": "%",
          "note": "Acc"
        },
        {
          "name": "HMMT 2025",
          "score": 38.8,
          "unit": "%",
          "note": "Avg@32"
        },
        {
          "name": "CNMO 2024",
          "score": 74.3,
          "unit": "%",
          "note": "Avg@16"
        },
        {
          "name": "PolyMath-en",
          "score": 65.1,
          "unit": "%",
          "note": "Avg@4"
        },
        {
          "name": "ZebraLogic",
          "score": 89.0,
          "unit": "%",
          "note": "Acc"
        },
        {
          "name": "AutoLogi",
          "score": 89.5,
          "unit": "%",
          "note": "Acc"
        },
        {
          "name": "GPQA-Diamond",
          "score": 75.1,
          "unit": "%",
          "note": "Avg@8"
        },
        {
          "name": "SuperGPQA",
          "score": 57.2,
          "unit": "%",
          "note": "Acc"
        },
        {
          "name": "Humanity's Last Exam",
          "score": 4.7,
          "unit": "%",
          "note": "Text Only"
        },
        {
          "name": "MMLU",
          "score": 89.5,
          "unit": "%",
          "note": "EM"
        },
        {
          "name": "MMLU-Redux",
          "score": 92.7,
          "unit": "%",
          "note": "EM"
        },
        {
          "name": "MMLU-Pro",
          "score": 81.1,
          "unit": "%",
          "note": "EM"
        },
        {
          "name": "IFEval",
          "score": 89.8,
          "unit": "%",
          "note": "Prompt Strict"
        },
        {
          "name": "Multi-Challenge",
          "score": 54.1,
          "unit": "%",
          "note": "Acc"
        },
        {
          "name": "SimpleQA",
          "score": 31.0,
          "unit": "%",
          "note": "Correct"
        },
        {
          "name": "Livebench",
          "score": 76.4,
          "unit": "%",
          "note": "Pass@1"
        }
      ],
      "headline": {
        "metric": "MATH-500",
        "score": 97.4
      },
      "summary": "K2 的后训练版（非长思考的 reflex 级模型），1T 总参/32B 激活 MoE，专为工具使用与自主问题求解优化。",
      "breakthrough": "开源 1T 参数级 agentic 模型：SWE-bench Verified 65.8%（agentic 单次）、Tau2/AceBench 等工具使用基准领先",
      "variants": [
        "Kimi-K2-Base",
        "Kimi-K2-Instruct-0905"
      ]
    },
    {
      "id": "kimi-k2-instruct-0905",
      "repo": "moonshotai/Kimi-K2-Instruct-0905",
      "org": "moonshotai",
      "name": "Kimi-K2-Instruct-0905",
      "family": "LLM",
      "date": "2025-09-03",
      "tier": "minor",
      "totalParams": "1T",
      "paramsSource": "card",
      "activatedParams": "32B",
      "contextLength": "256K",
      "license": "modified-mit",
      "downloads": 37788,
      "likes": 786,
      "storageBytes": 1029258547073,
      "storageLabel": "1.0 TB",
      "paramsB": 1000.0,
      "activeB": 32.0,
      "innovations": [
        "256K 长上下文(由128K扩展)",
        "Agentic coding 增强",
        "前端代码生成",
        "MoE 1T/32B 激活",
        "MLA"
      ],
      "benchmarks": [
        {
          "name": "SWE-Bench verified",
          "score": 69.2,
          "unit": "%",
          "note": "ACC, mean±0.63"
        },
        {
          "name": "SWE-Bench Multilingual",
          "score": 55.9,
          "unit": "%",
          "note": "ACC, mean±0.72"
        },
        {
          "name": "Multi-SWE-Bench",
          "score": 33.5,
          "unit": "%",
          "note": "ACC, mean±0.28"
        },
        {
          "name": "Terminal-Bench",
          "score": 44.5,
          "unit": "%",
          "note": "ACC, mean±2.03"
        },
        {
          "name": "SWE-Dev",
          "score": 66.6,
          "unit": "%",
          "note": "ACC, mean±0.72"
        }
      ],
      "headline": {
        "metric": "SWE-Bench verified",
        "score": 69.2
      },
      "summary": "Kimi K2 系列最新版指令模型，1T 总参/32B 激活，上下文由 128K 扩至 256K，主打 agentic coding。",
      "breakthrough": "上下文从 128K 提升到 256K，SWE-bench Verified 由 65.8 提升至 69.2",
      "variants": [
        "Kimi-K2-Instruct",
        "Kimi-K2-Base"
      ]
    },
    {
      "id": "kimi-linear-48b-a3b-instruct",
      "repo": "moonshotai/Kimi-Linear-48B-A3B-Instruct",
      "org": "moonshotai",
      "name": "Kimi-Linear-48B-A3B-Instruct",
      "family": "LLM",
      "date": "2025-10-30",
      "tier": "flagship",
      "totalParams": "48B",
      "paramsSource": "card",
      "activatedParams": "3B",
      "contextLength": "1M",
      "license": "mit",
      "downloads": 173293,
      "likes": 595,
      "storageBytes": 98270961861,
      "storageLabel": "98.3 GB",
      "paramsB": 48.0,
      "activeB": 3.0,
      "innovations": [
        "Kimi Delta Attention (KDA)",
        "3:1 KDA-to-global MLA 混合",
        "Gated DeltaNet 改进的门控",
        "开源 KDA kernel (FLA)",
        "KV cache 降低 75%"
      ],
      "benchmarks": [
        {
          "name": "MMLU-Pro",
          "score": 51.0,
          "unit": "%",
          "note": "4k 上下文"
        },
        {
          "name": "RULER",
          "score": 84.3,
          "unit": "%",
          "note": "128k 上下文, Pareto-optimal"
        }
      ],
      "headline": {
        "metric": "RULER",
        "score": 84.3
      },
      "summary": "混合线性注意力模型（KDA:MLA=3:1），5.7T token 训练，长上下文下相比全注意力最多 6x 解码吞吐提升。",
      "breakthrough": "KDA 混合线性注意力：1M 上下文解码吞吐最高 6x 提升、KV cache 需求降低最多 75%，RULER(128k) 84.3",
      "variants": [
        "Kimi-Linear-48B-A3B-Base"
      ]
    },
    {
      "id": "kimi-k2-thinking",
      "repo": "moonshotai/Kimi-K2-Thinking",
      "org": "moonshotai",
      "name": "Kimi-K2-Thinking",
      "family": "LLM",
      "date": "2025-11-04",
      "tier": "flagship",
      "totalParams": "1T",
      "paramsSource": "card",
      "activatedParams": "32B",
      "contextLength": "256K",
      "license": "modified-mit",
      "downloads": 51157,
      "likes": 1714,
      "storageBytes": 594283168582,
      "storageLabel": "594.3 GB",
      "paramsB": 1000.0,
      "activeB": 32.0,
      "innovations": [
        "原生 INT4 量化(QAT)",
        "交错思维链+工具调用",
        "200-300 步长程工具编排",
        "MoE 1T/32B 激活",
        "MLA"
      ],
      "benchmarks": [
        {
          "name": "HLE",
          "score": 23.9,
          "unit": "%",
          "note": "Text-only, no tools"
        },
        {
          "name": "HLE",
          "score": 44.9,
          "unit": "%",
          "note": "w/ tools"
        },
        {
          "name": "HLE",
          "score": 51.0,
          "unit": "%",
          "note": "heavy"
        },
        {
          "name": "AIME25",
          "score": 94.5,
          "unit": "%",
          "note": "no tools"
        },
        {
          "name": "AIME25",
          "score": 99.1,
          "unit": "%",
          "note": "w/ python"
        },
        {
          "name": "HMMT25",
          "score": 89.4,
          "unit": "%",
          "note": "no tools"
        },
        {
          "name": "HMMT25",
          "score": 95.1,
          "unit": "%",
          "note": "w/ python"
        },
        {
          "name": "IMO-AnswerBench",
          "score": 78.6,
          "unit": "%",
          "note": "no tools"
        },
        {
          "name": "GPQA",
          "score": 84.5,
          "unit": "%",
          "note": "no tools"
        },
        {
          "name": "MMLU-Pro",
          "score": 84.6,
          "unit": "%",
          "note": "no tools"
        },
        {
          "name": "MMLU-Redux",
          "score": 94.4,
          "unit": "%",
          "note": "no tools"
        },
        {
          "name": "Longform Writing",
          "score": 73.8,
          "unit": "%",
          "note": "no tools"
        },
        {
          "name": "HealthBench",
          "score": 58.0,
          "unit": "%",
          "note": "no tools"
        },
        {
          "name": "BrowseComp",
          "score": 60.2,
          "unit": "%",
          "note": "w/ tools"
        },
        {
          "name": "BrowseComp-ZH",
          "score": 62.3,
          "unit": "%",
          "note": "w/ tools"
        },
        {
          "name": "Seal-0",
          "score": 56.3,
          "unit": "%",
          "note": "w/ tools"
        },
        {
          "name": "FinSearchComp-T3",
          "score": 47.4,
          "unit": "%",
          "note": "w/ tools"
        },
        {
          "name": "Frames",
          "score": 87.0,
          "unit": "%",
          "note": "w/ tools"
        },
        {
          "name": "SWE-bench Verified",
          "score": 71.3,
          "unit": "%",
          "note": "w/ tools"
        },
        {
          "name": "SWE-bench Multilingual",
          "score": 61.1,
          "unit": "%",
          "note": "w/ tools"
        },
        {
          "name": "Multi-SWE-bench",
          "score": 41.9,
          "unit": "%",
          "note": "w/ tools"
        },
        {
          "name": "SciCode",
          "score": 44.8,
          "unit": "%",
          "note": "no tools"
        },
        {
          "name": "LiveCodeBenchV6",
          "score": 83.1,
          "unit": "%",
          "note": "no tools"
        },
        {
          "name": "OJ-Bench (cpp)",
          "score": 48.7,
          "unit": "%",
          "note": "no tools"
        },
        {
          "name": "Terminal-Bench",
          "score": 47.1,
          "unit": "%",
          "note": "w/ simulated tools (JSON)"
        }
      ],
      "headline": {
        "metric": "AIME25",
        "score": 94.5
      },
      "summary": "K2 的开源思考模型，边推理边动态调用工具，256K 上下文，采用 QAT 原生 INT4 量化。",
      "breakthrough": "QAT 原生 INT4 量化实现约 2x 生成加速且性能无损，并在 HLE/BrowseComp 等基准刷新 SOTA",
      "variants": [
        "Kimi-K2-Base",
        "Kimi-K2-Instruct",
        "Kimi-K2-Instruct-0905"
      ]
    },
    {
      "id": "kimi-k2-5",
      "repo": "moonshotai/Kimi-K2.5",
      "org": "moonshotai",
      "name": "Kimi K2.5",
      "family": "LLM",
      "date": "2026-01-01",
      "tier": "flagship",
      "totalParams": "1T",
      "paramsSource": "card",
      "activatedParams": "32B",
      "contextLength": "256K",
      "license": "modified-mit",
      "downloads": 380587,
      "likes": 2869,
      "storageBytes": 595246118966,
      "storageLabel": "595.2 GB",
      "paramsB": 1000.0,
      "activeB": 32.0,
      "innovations": [
        "原生多模态（约15T 图文 token 继续预训练）",
        "Agent Swarm 自协调并行子代理",
        "MoonViT 400M 视觉编码器",
        "原生 INT4 量化",
        "256K 上下文"
      ],
      "benchmarks": [
        {
          "name": "HLE-Full",
          "score": 30.1,
          "unit": "%",
          "note": "Thinking, no tools"
        },
        {
          "name": "HLE-Full",
          "score": 50.2,
          "unit": "%",
          "note": "w/ tools"
        },
        {
          "name": "AIME 2025",
          "score": 96.1,
          "unit": "%",
          "note": ""
        },
        {
          "name": "HMMT 2025 (Feb)",
          "score": 95.4,
          "unit": "%",
          "note": ""
        },
        {
          "name": "IMO-AnswerBench",
          "score": 81.8,
          "unit": "%",
          "note": ""
        },
        {
          "name": "GPQA-Diamond",
          "score": 87.6,
          "unit": "%",
          "note": ""
        },
        {
          "name": "MMLU-Pro",
          "score": 87.1,
          "unit": "%",
          "note": ""
        },
        {
          "name": "MMMU-Pro",
          "score": 78.5,
          "unit": "%",
          "note": ""
        },
        {
          "name": "CharXiv (RQ)",
          "score": 77.5,
          "unit": "%",
          "note": ""
        },
        {
          "name": "MathVision",
          "score": 84.2,
          "unit": "%",
          "note": ""
        },
        {
          "name": "MathVista (mini)",
          "score": 90.1,
          "unit": "%",
          "note": ""
        },
        {
          "name": "OCRBench",
          "score": 92.3,
          "unit": "%",
          "note": ""
        },
        {
          "name": "OmniDocBench 1.5",
          "score": 88.8,
          "unit": "%",
          "note": ""
        },
        {
          "name": "InfoVQA",
          "score": 92.6,
          "unit": "%",
          "note": ""
        },
        {
          "name": "SimpleVQA",
          "score": 71.2,
          "unit": "%",
          "note": ""
        },
        {
          "name": "WorldVQA",
          "score": 46.3,
          "unit": "%",
          "note": ""
        },
        {
          "name": "VideoMMMU",
          "score": 86.6,
          "unit": "%",
          "note": ""
        },
        {
          "name": "MMVU",
          "score": 80.4,
          "unit": "%",
          "note": ""
        },
        {
          "name": "MotionBench",
          "score": 70.4,
          "unit": "%",
          "note": ""
        },
        {
          "name": "VideoMME",
          "score": 87.4,
          "unit": "%",
          "note": ""
        },
        {
          "name": "LongVideoBench",
          "score": 79.8,
          "unit": "%",
          "note": ""
        },
        {
          "name": "LVBench",
          "score": 75.9,
          "unit": "%",
          "note": ""
        },
        {
          "name": "SWE-Bench Verified",
          "score": 76.8,
          "unit": "%",
          "note": ""
        },
        {
          "name": "SWE-Bench Pro",
          "score": 50.7,
          "unit": "%",
          "note": ""
        },
        {
          "name": "SWE-Bench Multilingual",
          "score": 73.0,
          "unit": "%",
          "note": ""
        },
        {
          "name": "Terminal Bench 2.0",
          "score": 50.8,
          "unit": "%",
          "note": ""
        },
        {
          "name": "PaperBench",
          "score": 63.5,
          "unit": "%",
          "note": ""
        },
        {
          "name": "CyberGym",
          "score": 41.3,
          "unit": "%",
          "note": ""
        },
        {
          "name": "SciCode",
          "score": 48.7,
          "unit": "%",
          "note": ""
        },
        {
          "name": "OJBench (cpp)",
          "score": 57.4,
          "unit": "%",
          "note": ""
        },
        {
          "name": "LiveCodeBench (v6)",
          "score": 85.0,
          "unit": "%",
          "note": ""
        },
        {
          "name": "Longbench v2",
          "score": 61.0,
          "unit": "%",
          "note": ""
        },
        {
          "name": "AA-LCR",
          "score": 70.0,
          "unit": "%",
          "note": ""
        },
        {
          "name": "BrowseComp",
          "score": 60.6,
          "unit": "%",
          "note": ""
        },
        {
          "name": "BrowseComp",
          "score": 74.9,
          "unit": "%",
          "note": "w/ ctx manage"
        },
        {
          "name": "BrowseComp",
          "score": 78.4,
          "unit": "%",
          "note": "Agent Swarm"
        },
        {
          "name": "WideSearch",
          "score": 72.7,
          "unit": "%",
          "note": "item-f1"
        },
        {
          "name": "WideSearch",
          "score": 79.0,
          "unit": "%",
          "note": "item-f1 Agent Swarm"
        },
        {
          "name": "DeepSearchQA",
          "score": 77.1,
          "unit": "%",
          "note": ""
        },
        {
          "name": "FinSearchCompT2&T3",
          "score": 67.8,
          "unit": "%",
          "note": ""
        },
        {
          "name": "Seal-0",
          "score": 57.4,
          "unit": "%",
          "note": ""
        },
        {
          "name": "ZeroBench",
          "score": 9.0,
          "unit": "%",
          "note": "no tools"
        },
        {
          "name": "ZeroBench",
          "score": 11.0,
          "unit": "%",
          "note": "w/ tools"
        }
      ],
      "headline": {
        "metric": "AIME 2025",
        "score": 96.1
      },
      "summary": "在 Kimi-K2-Base 上以约 15 万亿图文混合 token 继续预训练得到的原生多模态 agentic 模型，含 Instant/Thinking 双模式与 Agent Swarm。",
      "breakthrough": "原生多模态 + Agent Swarm：BrowseComp 由 60.6 提升到 74.9（上下文管理）、78.4（Agent Swarm）",
      "variants": [
        "Kimi-K2-Base",
        "Kimi-K2.6",
        "Kimi-K2.7-Code"
      ]
    },
    {
      "id": "kimi-k2-6",
      "repo": "moonshotai/Kimi-K2.6",
      "org": "moonshotai",
      "name": "Kimi K2.6",
      "family": "LLM",
      "date": "2026-04-14",
      "tier": "flagship",
      "totalParams": "1T",
      "paramsSource": "card",
      "activatedParams": "32B",
      "contextLength": "256K",
      "license": "modified-mit",
      "downloads": 535907,
      "likes": 1605,
      "storageBytes": 595263427116,
      "storageLabel": "595.3 GB",
      "paramsB": 1000.0,
      "activeB": 32.0,
      "innovations": [
        "Agent Swarm 扩展至 300 子代理/4000 步",
        "长程编码（Rust/Go/Python）",
        "编码驱动设计",
        "原生 INT4 量化",
        "原生多模态"
      ],
      "benchmarks": [
        {
          "name": "HLE-Full",
          "score": 34.7,
          "unit": "%",
          "note": "no tools"
        },
        {
          "name": "HLE-Full",
          "score": 54.0,
          "unit": "%",
          "note": "w/ tools"
        },
        {
          "name": "BrowseComp",
          "score": 83.2,
          "unit": "%",
          "note": ""
        },
        {
          "name": "BrowseComp",
          "score": 86.3,
          "unit": "%",
          "note": "Agent Swarm"
        },
        {
          "name": "DeepSearchQA",
          "score": 92.5,
          "unit": "%",
          "note": "f1-score"
        },
        {
          "name": "DeepSearchQA",
          "score": 83.0,
          "unit": "%",
          "note": "accuracy"
        },
        {
          "name": "WideSearch",
          "score": 80.8,
          "unit": "%",
          "note": "item-f1"
        },
        {
          "name": "Toolathlon",
          "score": 50.0,
          "unit": "%",
          "note": ""
        },
        {
          "name": "MCPMark",
          "score": 55.9,
          "unit": "%",
          "note": ""
        },
        {
          "name": "Claw Eval",
          "score": 62.3,
          "unit": "%",
          "note": "pass^3"
        },
        {
          "name": "Claw Eval",
          "score": 80.9,
          "unit": "%",
          "note": "pass@3"
        },
        {
          "name": "APEX-Agents",
          "score": 27.9,
          "unit": "%",
          "note": ""
        },
        {
          "name": "OSWorld-Verified",
          "score": 73.1,
          "unit": "%",
          "note": ""
        },
        {
          "name": "Terminal-Bench 2.0",
          "score": 66.7,
          "unit": "%",
          "note": "Terminus-2"
        },
        {
          "name": "SWE-Bench Pro",
          "score": 58.6,
          "unit": "%",
          "note": ""
        },
        {
          "name": "SWE-Bench Multilingual",
          "score": 76.7,
          "unit": "%",
          "note": ""
        },
        {
          "name": "SWE-Bench Verified",
          "score": 80.2,
          "unit": "%",
          "note": ""
        },
        {
          "name": "SciCode",
          "score": 52.2,
          "unit": "%",
          "note": ""
        },
        {
          "name": "OJBench (python)",
          "score": 60.6,
          "unit": "%",
          "note": ""
        },
        {
          "name": "LiveCodeBench (v6)",
          "score": 89.6,
          "unit": "%",
          "note": ""
        },
        {
          "name": "AIME 2026",
          "score": 96.4,
          "unit": "%",
          "note": ""
        },
        {
          "name": "HMMT 2026 (Feb)",
          "score": 92.7,
          "unit": "%",
          "note": ""
        },
        {
          "name": "IMO-AnswerBench",
          "score": 86.0,
          "unit": "%",
          "note": ""
        },
        {
          "name": "GPQA-Diamond",
          "score": 90.5,
          "unit": "%",
          "note": ""
        },
        {
          "name": "MMMU-Pro",
          "score": 79.4,
          "unit": "%",
          "note": ""
        },
        {
          "name": "MMMU-Pro",
          "score": 80.1,
          "unit": "%",
          "note": "w/ python"
        },
        {
          "name": "CharXiv (RQ)",
          "score": 80.4,
          "unit": "%",
          "note": ""
        },
        {
          "name": "CharXiv (RQ)",
          "score": 86.7,
          "unit": "%",
          "note": "w/ python"
        },
        {
          "name": "MathVision",
          "score": 87.4,
          "unit": "%",
          "note": ""
        },
        {
          "name": "MathVision",
          "score": 93.2,
          "unit": "%",
          "note": "w/ python"
        },
        {
          "name": "BabyVision",
          "score": 39.8,
          "unit": "%",
          "note": ""
        },
        {
          "name": "BabyVision",
          "score": 68.5,
          "unit": "%",
          "note": "w/ python"
        },
        {
          "name": "V*",
          "score": 96.9,
          "unit": "%",
          "note": "w/ python"
        }
      ],
      "headline": {
        "metric": "V*",
        "score": 96.9
      },
      "summary": "K2.5 的后继原生多模态 agentic 模型，强化长程编码、编码驱动设计与 300 子代理的 Agent Swarm 编排。",
      "breakthrough": "Agent Swarm 横向扩展到 300 个子代理、4000 步协同，BrowseComp(Agent Swarm) 86.3、SWE-Bench Verified 80.2",
      "variants": [
        "Kimi-K2.5",
        "Kimi-K2.7-Code"
      ]
    },
    {
      "id": "kimi-k2-7-code",
      "repo": "moonshotai/Kimi-K2.7-Code",
      "org": "moonshotai",
      "name": "Kimi K2.7 Code",
      "family": "Coder",
      "date": "2026-06-11",
      "tier": "major",
      "totalParams": "1T",
      "paramsSource": "card",
      "activatedParams": "32B",
      "contextLength": "256K",
      "license": "modified-mit",
      "downloads": 182708,
      "likes": 1387,
      "storageBytes": 595204651032,
      "storageLabel": "595.2 GB",
      "paramsB": 1000.0,
      "activeB": 32.0,
      "innovations": [
        "基于 K2.6 的编码专用 agentic 模型",
        "原生 INT4 量化",
        "强制 preserve_thinking",
        "thinking token 减少约 30%",
        "MoonViT 视觉编码器"
      ],
      "benchmarks": [
        {
          "name": "Kimi Code Bench v2",
          "score": 62.0,
          "unit": "%",
          "note": ""
        },
        {
          "name": "Program Bench",
          "score": 53.6,
          "unit": "%",
          "note": ""
        },
        {
          "name": "MLS Bench Lite",
          "score": 35.1,
          "unit": "%",
          "note": ""
        },
        {
          "name": "Kimi Claw 24/7 Bench",
          "score": 46.9,
          "unit": "%",
          "note": ""
        },
        {
          "name": "MCP Atlas",
          "score": 76.0,
          "unit": "%",
          "note": ""
        },
        {
          "name": "MCP Mark Verified",
          "score": 81.1,
          "unit": "%",
          "note": ""
        }
      ],
      "headline": {
        "metric": "MCP Mark Verified",
        "score": 81.1
      },
      "summary": "基于 Kimi K2.6 打造的编码专用 agentic 模型，强化长程工程任务端到端完成能力，并提升 token 效率。",
      "breakthrough": "相比 K2.6 思考 token 用量减少约 30%：Kimi Code Bench v2 50.9→62.0、MCP Mark Verified 72.8→81.1",
      "variants": [
        "Kimi-K2.6",
        "Kimi-K2.5"
      ]
    },
    {
      "id": "kimi-k3",
      "repo": "moonshotai/Kimi-K3",
      "org": "moonshotai",
      "name": "Kimi K3",
      "family": "LLM",
      "date": "2026-06-13",
      "tier": "flagship",
      "totalParams": "2.8T",
      "paramsSource": "card",
      "activatedParams": "104B",
      "contextLength": "1048576",
      "license": "kimi-k3",
      "downloads": 2277273,
      "likes": 11299,
      "storageBytes": 1561018243668,
      "storageLabel": "1.6 TB",
      "paramsB": 2800.0,
      "activeB": 104.0,
      "innovations": [
        "Kimi Delta Attention (KDA)",
        "Attention Residuals (AttnRes)",
        "Stable LatentMoE（896 专家激活 16）",
        "MXFP4权重/MXFP8激活 QAT",
        "百万 token 上下文"
      ],
      "benchmarks": [
        {
          "name": "GPQA Diamond",
          "score": 93.5,
          "unit": "%",
          "note": ""
        },
        {
          "name": "CritPt",
          "score": 23.4,
          "unit": "%",
          "note": ""
        },
        {
          "name": "AA-LCR",
          "score": 74.7,
          "unit": "%",
          "note": ""
        },
        {
          "name": "HLE-Full",
          "score": 43.5,
          "unit": "%",
          "note": "无工具；带工具 56.0"
        },
        {
          "name": "DeepSWE",
          "score": 67.5,
          "unit": "%",
          "note": ""
        },
        {
          "name": "ProgramBench",
          "score": 77.8,
          "unit": "%",
          "note": ""
        },
        {
          "name": "Terminal-Bench 2.1",
          "score": 88.3,
          "unit": "%",
          "note": ""
        },
        {
          "name": "FrontierSWE",
          "score": 81.2,
          "unit": "%",
          "note": ""
        },
        {
          "name": "SWE-Marathon",
          "score": 42.0,
          "unit": "%",
          "note": ""
        },
        {
          "name": "PostTrainBench",
          "score": 36.6,
          "unit": "%",
          "note": ""
        },
        {
          "name": "MLS-Bench-Lite",
          "score": 48.3,
          "unit": "%",
          "note": ""
        },
        {
          "name": "SciCode",
          "score": 58.7,
          "unit": "%",
          "note": ""
        },
        {
          "name": "Kimi Code Bench 2.0",
          "score": 72.9,
          "unit": "%",
          "note": ""
        },
        {
          "name": "BrowseComp",
          "score": 91.2,
          "unit": "%",
          "note": ""
        },
        {
          "name": "DeepSearchQA",
          "score": 95.0,
          "unit": "%",
          "note": "F1"
        },
        {
          "name": "ResearchRubrics",
          "score": 76.2,
          "unit": "%",
          "note": ""
        },
        {
          "name": "GDPval-AA v2",
          "score": 1686.0,
          "unit": "%",
          "note": "Elo"
        },
        {
          "name": "Toolathlon-Verified",
          "score": 76.5,
          "unit": "%",
          "note": ""
        },
        {
          "name": "MCPMark-Verified",
          "score": 94.5,
          "unit": "%",
          "note": ""
        },
        {
          "name": "MCP-Atlas",
          "score": 84.2,
          "unit": "%",
          "note": ""
        },
        {
          "name": "AutomationBench",
          "score": 30.8,
          "unit": "%",
          "note": ""
        },
        {
          "name": "JobBench",
          "score": 54.3,
          "unit": "%",
          "note": ""
        },
        {
          "name": "AA-Briefcase",
          "score": 1548.0,
          "unit": "%",
          "note": "Elo"
        },
        {
          "name": "Agents' Last Exam",
          "score": 28.3,
          "unit": "%",
          "note": ""
        },
        {
          "name": "APEX-Agents",
          "score": 41.0,
          "unit": "%",
          "note": ""
        },
        {
          "name": "OfficeQA Pro",
          "score": 63.3,
          "unit": "%",
          "note": ""
        },
        {
          "name": "SpreadsheetBench 2",
          "score": 34.8,
          "unit": "%",
          "note": ""
        },
        {
          "name": "OSWorld-Verified",
          "score": 84.8,
          "unit": "%",
          "note": ""
        },
        {
          "name": "OSWorld 2.0",
          "score": 58.3,
          "unit": "%",
          "note": ""
        },
        {
          "name": "SaaS-Bench",
          "score": 60.1,
          "unit": "%",
          "note": ""
        },
        {
          "name": "τ³-Banking",
          "score": 33.4,
          "unit": "%",
          "note": ""
        },
        {
          "name": "Harvey Lab-AA",
          "score": 94.6,
          "unit": "%",
          "note": ""
        },
        {
          "name": "CorpFin v2",
          "score": 71.6,
          "unit": "%",
          "note": ""
        },
        {
          "name": "Finance Agent v2",
          "score": 54.4,
          "unit": "%",
          "note": ""
        },
        {
          "name": "Legal Research Bench",
          "score": 44.2,
          "unit": "%",
          "note": ""
        },
        {
          "name": "WorldVQA ForceAnswer",
          "score": 51.0,
          "unit": "%",
          "note": ""
        },
        {
          "name": "OmniDocBench",
          "score": 91.1,
          "unit": "%",
          "note": ""
        },
        {
          "name": "PerceptionBench",
          "score": 58.5,
          "unit": "%",
          "note": ""
        },
        {
          "name": "Video-MME",
          "score": 90.0,
          "unit": "%",
          "note": "w. sub"
        },
        {
          "name": "MMVU",
          "score": 82.1,
          "unit": "%",
          "note": ""
        },
        {
          "name": "BabyVision",
          "score": 85.7,
          "unit": "%",
          "note": "w/ python"
        },
        {
          "name": "MMMU-Pro",
          "score": 81.6,
          "unit": "%",
          "note": "无工具；带工具 83.4"
        },
        {
          "name": "CharXiv (RQ)",
          "score": 84.8,
          "unit": "%",
          "note": "无工具；带工具 91.3"
        },
        {
          "name": "MathVision",
          "score": 94.3,
          "unit": "%",
          "note": "无工具；带工具 97.8"
        },
        {
          "name": "ZeroBench",
          "score": 23.0,
          "unit": "%",
          "note": "pass@5，无工具；带工具 41.0"
        }
      ],
      "headline": {
        "metric": "GDPval-AA v2",
        "score": 1686.0
      },
      "summary": "全球首个开源的 3T 级模型：2.8T 总参/104B 激活，基于 KDA + AttnRes + Stable LatentMoE，原生多模态，1M token 上下文（模型卡写作 1048576）。",
      "breakthrough": "以 KDA+Attention Residuals+Stable LatentMoE（896 专家激活 16）把 MoE 稀疏度推高，整体扩展效率较 Kimi K2 提升约 2.5x",
      "variants": [
        "Kimi-K2",
        "Kimi-K2.5",
        "Kimi-K2.6",
        "Kimi-K2.7-Code"
      ]
    }
  ],
  "breakthroughs": [
    {
      "id": "kimi-moonlight-16b-a3b-instruct",
      "date": "2025-02-22",
      "label": "Muon",
      "name": "首次证明 Muon 优化器可用于大规模 LL",
      "releaseId": "moonlight-16b-a3b-instruct",
      "lane": "训练",
      "mechanism": "首次证明 Muon 优化器可用于大规模 LLM 训练：约 2x 样本效率、约 52% 训练 FLOPs 达到 AdamW 同等性能",
      "impact": "用 Muon 优化器训练的 3B/16B MoE 模型，5.7T token 预训练，验证了 Muon 在大规模训练上的可扩展性。",
      "magnitude": "上下文 8K"
    },
    {
      "id": "kimi-kimi-vl-a3b-instruct",
      "date": "2025-04-09",
      "label": "MoE",
      "name": "以 2.8B+0.4B 激活参数在 Scre",
      "releaseId": "kimi-vl-a3b-instruct",
      "lane": "多模态",
      "mechanism": "以 2.8B+0.4B 激活参数在 ScreenSpot-V2(92.8)、OSWorld(8.22) 等 GUI Agent 任务上超过 GPT-4o",
      "impact": "激活仅 2.8B 参数的高效 MoE VLM（16B 总参/3B 激活），128K 上下文，具备长视频/长文档与 OS Agent 能力。",
      "magnitude": "上下文 128K"
    },
    {
      "id": "kimi-kimi-dev-72b",
      "date": "2025-06-16",
      "label": "Docker",
      "name": "SWE-bench Verified 达 6",
      "releaseId": "kimi-dev-72b",
      "lane": "后训练",
      "mechanism": "SWE-bench Verified 达 60.4%，刷新开源模型 SOTA",
      "impact": "面向软件工程问题解决的编码 LLM（base_model 为 Qwen/Qwen2.5-72B）；模型卡未印参数量，故参数字段为 null。",
      "magnitude": "见模型卡"
    },
    {
      "id": "kimi-kimi-vl-a3b-thinking-2506",
      "date": "2025-06-21",
      "label": "think",
      "name": "多模态推理大幅提升并降低 20% 思维长度",
      "releaseId": "kimi-vl-a3b-thinking-2506",
      "lane": "多模态",
      "mechanism": "多模态推理大幅提升并降低 20% 思维长度：MathVision 36.8→56.9，单图支持 3.2M 像素（4x）",
      "impact": "Kimi-VL-A3B-Thinking 的升级版：base_model 指向 Kimi-VL-A3B-Instruct（同代 16B 总参/3B 激活），上下文长度按卡内 VLLM 示例 max_model_len=131072(=128K) 记为 128K；本卡未印参数量表，参数与上下文档为同代推断。",
      "magnitude": "上下文 128K"
    },
    {
      "id": "kimi-kimi-k2-base",
      "date": "2025-07-03",
      "label": "MuonClip",
      "name": "MuonClip 优化器把 Muon 首次扩",
      "releaseId": "kimi-k2-base",
      "lane": "训练",
      "mechanism": "MuonClip 优化器把 Muon 首次扩展到 1T 参数 MoE 规模，实现 15.5T token 零训练不稳定",
      "impact": "Kimi K2 的基座模型：1T 总参/32B 激活的 MoE，用 Muon 优化器在 15.5T token 上预训练且训练全程无失稳。",
      "magnitude": "上下文 128K"
    },
    {
      "id": "kimi-kimi-k2-instruct",
      "date": "2025-07-11",
      "label": "MuonClip",
      "name": "开源 1T 参数级 agentic 模型",
      "releaseId": "kimi-k2-instruct",
      "lane": "训练",
      "mechanism": "开源 1T 参数级 agentic 模型：SWE-bench Verified 65.8%（agentic 单次）、Tau2/AceBench 等工具使用基准领先",
      "impact": "K2 的后训练版（非长思考的 reflex 级模型），1T 总参/32B 激活 MoE，专为工具使用与自主问题求解优化。",
      "magnitude": "上下文 128K"
    },
    {
      "id": "kimi-kimi-linear-48b-a3b-instruct",
      "date": "2025-10-30",
      "label": "Kimi",
      "name": "KDA 混合线性注意力",
      "releaseId": "kimi-linear-48b-a3b-instruct",
      "lane": "推理",
      "mechanism": "KDA 混合线性注意力：1M 上下文解码吞吐最高 6x 提升、KV cache 需求降低最多 75%，RULER(128k) 84.3",
      "impact": "混合线性注意力模型（KDA:MLA=3:1），5.7T token 训练，长上下文下相比全注意力最多 6x 解码吞吐提升。",
      "magnitude": "上下文 1M"
    },
    {
      "id": "kimi-kimi-k2-thinking",
      "date": "2025-11-04",
      "label": "INT4",
      "name": "QAT 原生 INT4 量化实现约 2x 生",
      "releaseId": "kimi-k2-thinking",
      "lane": "推理",
      "mechanism": "QAT 原生 INT4 量化实现约 2x 生成加速且性能无损，并在 HLE/BrowseComp 等基准刷新 SOTA",
      "impact": "K2 的开源思考模型，边推理边动态调用工具，256K 上下文，采用 QAT 原生 INT4 量化。",
      "magnitude": "上下文 256K"
    },
    {
      "id": "kimi-kimi-k2-5",
      "date": "2026-01-01",
      "label": "token",
      "name": "原生多模态 + Agent Swarm",
      "releaseId": "kimi-k2-5",
      "lane": "多模态",
      "mechanism": "原生多模态 + Agent Swarm：BrowseComp 由 60.6 提升到 74.9（上下文管理）、78.4（Agent Swarm）",
      "impact": "在 Kimi-K2-Base 上以约 15 万亿图文混合 token 继续预训练得到的原生多模态 agentic 模型，含 Instant/Thinking 双模式与 Agent Swarm。",
      "magnitude": "上下文 256K"
    },
    {
      "id": "kimi-kimi-k2-6",
      "date": "2026-04-14",
      "label": "Agent",
      "name": "Agent Swarm 横向扩展到 300 ",
      "releaseId": "kimi-k2-6",
      "lane": "后训练",
      "mechanism": "Agent Swarm 横向扩展到 300 个子代理、4000 步协同，BrowseComp(Agent Swarm) 86.3、SWE-Bench Verified 80.2",
      "impact": "K2.5 的后继原生多模态 agentic 模型，强化长程编码、编码驱动设计与 300 子代理的 Agent Swarm 编排。",
      "magnitude": "上下文 256K"
    },
    {
      "id": "kimi-kimi-k2-7-code",
      "date": "2026-06-11",
      "label": "K2.6",
      "name": "相比 K2.6 思考 token 用量减少约",
      "releaseId": "kimi-k2-7-code",
      "lane": "训练",
      "mechanism": "相比 K2.6 思考 token 用量减少约 30%：Kimi Code Bench v2 50.9→62.0、MCP Mark Verified 72.8→81.1",
      "impact": "基于 Kimi K2.6 打造的编码专用 agentic 模型，强化长程工程任务端到端完成能力，并提升 token 效率。",
      "magnitude": "上下文 256K"
    },
    {
      "id": "kimi-kimi-k3",
      "date": "2026-06-13",
      "label": "Kimi",
      "name": "以 KDA+Attention Residu",
      "releaseId": "kimi-k3",
      "lane": "推理",
      "mechanism": "以 KDA+Attention Residuals+Stable LatentMoE（896 专家激活 16）把 MoE 稀疏度推高，整体扩展效率较 Kimi K2 提升约 2.5x",
      "impact": "全球首个开源的 3T 级模型：2.8T 总参/104B 激活，基于 KDA + AttnRes + Stable LatentMoE，原生多模态，1M token 上下文（模型卡写作 1048576）。",
      "magnitude": "上下文 1048576"
    }
  ]
} as Dataset
