/* Generated by scripts/gen_orgs.py — do not edit by hand. */
import type { Dataset } from './types'

export const dataset: Dataset = {
  "org": "zai-org",
  "orgName": "智谱 GLM",
  "snapshot": "2026-09-13",
  "repoCount": 154,
  "releases": [
    {
      "id": "chatglm-6b",
      "repo": "zai-org/chatglm-6b",
      "org": "zai-org",
      "name": "ChatGLM-6B",
      "family": "LLM",
      "date": "2023-03-13",
      "tier": "flagship",
      "totalParams": "62 亿",
      "paramsSource": "card",
      "activatedParams": null,
      "contextLength": null,
      "license": "Apache-2.0（代码）/ Model License（模型权重）",
      "downloads": 3070,
      "likes": 2916,
      "storageBytes": 47452655921,
      "storageLabel": "47.5 GB",
      "paramsB": null,
      "activeB": null,
      "innovations": [
        "GLM 架构（General Language Model）",
        "中英双语对话",
        "监督微调 + 反馈自助 + 人类反馈强化学习(RLHF)",
        "INT4 量化 6GB 显存消费级部署",
        "约 1T 中英双语 token 预训练"
      ],
      "benchmarks": [],
      "headline": null,
      "summary": "智谱开源系列的第一代中英双语对话模型，62 亿参数、GLM 架构，可在消费级显卡本地部署，是整个 ChatGLM/GLM 开源谱系的起点。",
      "breakthrough": "以 62 亿参数配合 INT4 量化，把中文对话大模型拉到 6GB 显存的消费级显卡上运行。",
      "variants": []
    },
    {
      "id": "chatglm2-6b",
      "repo": "zai-org/chatglm2-6b",
      "org": "zai-org",
      "name": "ChatGLM2-6B",
      "family": "LLM",
      "date": "2023-06-24",
      "tier": "flagship",
      "totalParams": "6B",
      "paramsSource": "card",
      "activatedParams": null,
      "contextLength": "32K",
      "license": "Apache-2.0（代码）/ Model License（模型权重）",
      "downloads": 442087,
      "likes": 2056,
      "storageBytes": 49949968758,
      "storageLabel": "49.9 GB",
      "paramsB": 6.0,
      "activeB": null,
      "innovations": [
        "FlashAttention",
        "Multi-Query Attention",
        "上下文 2K→32K",
        "GLM 混合目标函数",
        "1.4T 中英双语 token 预训练"
      ],
      "benchmarks": [
        {
          "name": "MMLU",
          "score": 23.0,
          "unit": "%",
          "note": "相较初代 ChatGLM-6B 的相对提升（+23%），非绝对分数"
        },
        {
          "name": "C-Eval",
          "score": 33.0,
          "unit": "%",
          "note": "相较初代 ChatGLM-6B 的相对提升（+33%），非绝对分数"
        },
        {
          "name": "GSM8K",
          "score": 571.0,
          "unit": "%",
          "note": "相较初代 ChatGLM-6B 的相对提升（+571%），非绝对分数"
        },
        {
          "name": "BBH",
          "score": 60.0,
          "unit": "%",
          "note": "相较初代 ChatGLM-6B 的相对提升（+60%），非绝对分数"
        },
        {
          "name": "推理速度",
          "score": 42.0,
          "unit": "%",
          "note": "相较初代 ChatGLM-6B 的提升（+42%），官方实现下"
        }
      ],
      "headline": {
        "metric": "GSM8K",
        "score": 571.0
      },
      "summary": "ChatGLM-6B 的第二代版本，借 FlashAttention 与 Multi-Query Attention 把上下文从 2K 提到 32K、推理提速 42%，同尺寸开源模型中竞争力显著增强。",
      "breakthrough": "上下文长度由初代的 2K 扩展至 32K（对话 8K 训练），同时推理速度提升 42%、INT4 下 6G 显存支持对话长度由 1K 提升到 8K。",
      "variants": []
    },
    {
      "id": "codegeex2-6b",
      "repo": "zai-org/codegeex2-6b",
      "org": "zai-org",
      "name": "CodeGeeX2-6B",
      "family": "Coder",
      "date": "2023-07-19",
      "tier": "major",
      "totalParams": "60 亿",
      "paramsSource": "card",
      "activatedParams": null,
      "contextLength": "8K",
      "license": "Apache-2.0（代码）/ Model License（模型权重）",
      "downloads": 322,
      "likes": 258,
      "storageBytes": 24975458200,
      "storageLabel": "25.0 GB",
      "paramsB": null,
      "activeB": null,
      "innovations": [
        "基于 ChatGLM2-6B 架构",
        "600B 代码数据预训练",
        "多语言代码生成（插件支持 100+ 语言）",
        "8192 序列长度",
        "INT4 量化后仅需 6GB 显存"
      ],
      "benchmarks": [
        {
          "name": "HumanEval-X (Python) Pass@1",
          "score": 35.9,
          "unit": "%",
          "note": "卡内原文：“在Python上达到 35.9% 的 Pass@1 一次通过率”"
        },
        {
          "name": "HumanEval-X Python",
          "score": 57.0,
          "unit": "%",
          "note": "相较一代 CodeGeeX 的相对提升（+57%），非绝对分数"
        },
        {
          "name": "HumanEval-X C++",
          "score": 71.0,
          "unit": "%",
          "note": "相较一代 CodeGeeX 的相对提升（+71%），非绝对分数"
        },
        {
          "name": "HumanEval-X Java",
          "score": 54.0,
          "unit": "%",
          "note": "相较一代 CodeGeeX 的相对提升（+54%），非绝对分数"
        },
        {
          "name": "HumanEval-X JavaScript",
          "score": 83.0,
          "unit": "%",
          "note": "相较一代 CodeGeeX 的相对提升（+83%），非绝对分数"
        },
        {
          "name": "HumanEval-X Go",
          "score": 56.0,
          "unit": "%",
          "note": "相较一代 CodeGeeX 的相对提升（+56%），非绝对分数"
        },
        {
          "name": "HumanEval-X Rust",
          "score": 321.0,
          "unit": "%",
          "note": "相较一代 CodeGeeX 的相对提升（+321%），非绝对分数"
        },
        {
          "name": "整体代码能力",
          "score": 107.0,
          "unit": "%",
          "note": "卡内原文“+107% > CodeGeeX”，相对提升，非绝对分数"
        }
      ],
      "headline": {
        "metric": "HumanEval-X Rust",
        "score": 321.0
      },
      "summary": "CodeGeeX2-6B 是基于 ChatGLM2-6B 架构、经 600B 代码 token 预训练的多语言代码生成模型，Python HumanEval-X Pass@1 达 35.9%，用 6B 参数超过 15B 的 StarCoder-15B。",
      "breakthrough": "仅 60 亿参数即在 HumanEval-X 上超越 150 亿参数的 StarCoder-15B（Python Pass@1 35.9%）。",
      "variants": [
        "THUDM/codegeex2-6b-int4"
      ]
    },
    {
      "id": "chatglm3-6b",
      "repo": "zai-org/chatglm3-6b",
      "org": "zai-org",
      "name": "ChatGLM3-6B",
      "family": "LLM",
      "date": "2023-10-25",
      "tier": "flagship",
      "totalParams": "6B",
      "paramsSource": "card",
      "activatedParams": null,
      "contextLength": null,
      "license": "Apache-2.0（代码）/ Model License（模型权重）",
      "downloads": 61785,
      "likes": 1166,
      "storageBytes": 37462649896,
      "storageLabel": "37.5 GB",
      "paramsB": 6.0,
      "activeB": null,
      "innovations": [
        "全新设计的 Prompt 格式",
        "原生工具调用（Function Call）",
        "代码执行（Code Interpreter）",
        "Agent 任务支持",
        "10B 以下最强预训练基座（自述，无数字）"
      ],
      "benchmarks": [],
      "headline": null,
      "summary": "ChatGLM 系列第三代的对话模型，最大变化是采用全新 Prompt 格式并原生支持 Function Call、Code Interpreter 与 Agent 场景，同时开源 Base 与 32K 长文本版本。",
      "breakthrough": "原生支持工具调用（Function Call）与代码执行，从纯对话模型转向可执行任务的 Agent 形态。",
      "variants": [
        "THUDM/chatglm3-6b-base（卡内写作 ChatGLM-6B-Base）",
        "THUDM/chatglm3-6b-32k"
      ]
    },
    {
      "id": "cogvlm-chat-hf",
      "repo": "zai-org/cogvlm-chat-hf",
      "org": "zai-org",
      "name": "CogVLM-17B",
      "family": "VL",
      "date": "2023-11-16",
      "tier": "major",
      "totalParams": "17B",
      "paramsSource": "card",
      "activatedParams": null,
      "contextLength": null,
      "license": "Apache-2.0（代码）/ Model License（模型权重）",
      "downloads": 790,
      "likes": 199,
      "storageBytes": 70559058896,
      "storageLabel": "70.6 GB",
      "paramsB": 17.0,
      "activeB": null,
      "innovations": [
        "视觉专家模块（Visual Expert）",
        "ViT 编码器 + MLP 适配器 + 预训练 LLM 四组件",
        "跨模态对话与视觉 grounding",
        "超越或持平 PaLI-X 55B（自述，无数字）"
      ],
      "benchmarks": [],
      "headline": null,
      "summary": "CogVLM-17B 是开源视觉语言模型，由 10B 视觉参数与 7B 语言参数组成，在 10 个跨模态基准上自称 SOTA，并在 VQAv2/OKVQA/TextVQA/COCO captioning 上排名第二。",
      "breakthrough": "视觉专家模块（Visual Expert）：在预训练语言模型的每一层引入视觉专家，使 VLM 效果超越或持平 PaLI-X 55B（自述）。",
      "variants": []
    },
    {
      "id": "cogagent-chat-hf",
      "repo": "zai-org/cogagent-chat-hf",
      "org": "zai-org",
      "name": "CogAgent-18B",
      "family": "Agent",
      "date": "2023-12-15",
      "tier": "major",
      "totalParams": "18B",
      "paramsSource": "card",
      "activatedParams": null,
      "contextLength": null,
      "license": "Apache-2.0（代码）/ Model License（模型权重）",
      "downloads": 488,
      "likes": 68,
      "storageBytes": 66442208168,
      "storageLabel": "66.4 GB",
      "paramsB": 18.0,
      "activeB": null,
      "innovations": [
        "高分辨率视觉输入 1120x1120",
        "GUI Agent：输出计划/下一步动作/坐标",
        "GUI 问答（网页、PC 应用、移动应用）",
        "OCR 相关任务增强",
        "继承 CogVLM 视觉多轮对话与 grounding"
      ],
      "benchmarks": [],
      "headline": null,
      "summary": "CogAgent-18B 是在 CogVLM 基础上改进的视觉语言模型（11B 视觉 + 7B 语言），主打 GUI Agent、高分辨率图像理解与 OCR 增强，是 cogagent-chat 版本权重。",
      "breakthrough": "首个把 VLM 用作 GUI Agent：对任意 GUI 截图直接返回任务计划、下一步动作与操作坐标，并支持 1120x1120 超高清输入。",
      "variants": [
        "THUDM/cogagent-vqa-hf",
        "THUDM/cogagent-9b-20241220"
      ]
    },
    {
      "id": "cogvlm2-llama3-chat-19b",
      "repo": "zai-org/cogvlm2-llama3-chat-19B",
      "org": "zai-org",
      "name": "CogVLM2-LLaMA3-Chat-19B",
      "family": "VL",
      "date": "2024-05-16",
      "tier": "major",
      "totalParams": "19B",
      "paramsSource": "card",
      "activatedParams": null,
      "contextLength": "8K",
      "license": "CogVLM2 LICENSE（other），基于 Meta Llama 3 需同时遵守 LLAMA3_LICENSE",
      "downloads": 10263,
      "likes": 220,
      "storageBytes": 39006373728,
      "storageLabel": "39.0 GB",
      "paramsB": 19.0,
      "activeB": null,
      "innovations": [
        "Meta-Llama-3-8B-Instruct 基座",
        "8K 文本长度",
        "图像分辨率 1344 * 1344",
        "中英双语版本（chinese-chat-19B）",
        "TextVQA/DocVQA 比上一代大幅提升"
      ],
      "benchmarks": [
        {
          "name": "TextVQA",
          "score": 84.2,
          "unit": "%",
          "note": "卡内 CogVLM2-LLaMA3 行，pixel only 无外部 OCR"
        },
        {
          "name": "DocVQA",
          "score": 92.3,
          "unit": "%",
          "note": "卡内 CogVLM2-LLaMA3 行，pixel only 无外部 OCR"
        },
        {
          "name": "ChartQA",
          "score": 81.0,
          "unit": "%",
          "note": "卡内 CogVLM2-LLaMA3 行"
        },
        {
          "name": "OCRBench",
          "score": 756.0,
          "unit": "score",
          "note": "卡内 CogVLM2-LLaMA3 行"
        },
        {
          "name": "VCR_EASY",
          "score": 83.3,
          "unit": "%",
          "note": "卡内 CogVLM2-LLaMA3 行"
        },
        {
          "name": "VCR_HARD",
          "score": 38.0,
          "unit": "%",
          "note": "卡内 CogVLM2-LLaMA3 行"
        },
        {
          "name": "MMMU",
          "score": 44.3,
          "unit": "%",
          "note": "卡内 CogVLM2-LLaMA3 行"
        },
        {
          "name": "MMVet",
          "score": 60.4,
          "unit": "%",
          "note": "卡内 CogVLM2-LLaMA3 行"
        },
        {
          "name": "MMBench",
          "score": 80.5,
          "unit": "%",
          "note": "卡内 CogVLM2-LLaMA3 行"
        }
      ],
      "headline": {
        "metric": "OCRBench",
        "score": 756.0
      },
      "summary": "CogVLM2 系列基于 Meta-Llama-3-8B-Instruct 构建的 19B 视觉语言模型，支持 8K 文本与 1344×1344 图像输入，DocVQA 92.3、TextVQA 84.2。",
      "breakthrough": "图文文档理解大幅跃升：DocVQA 92.3 超过 GPT-4V(88.4)、OCRBench 756 超过 GPT-4V(656)，且全程不使用外部 OCR 工具。",
      "variants": [
        "THUDM/cogvlm2-llama3-chinese-chat-19B"
      ]
    },
    {
      "id": "glm-4-9b-chat",
      "repo": "zai-org/glm-4-9b-chat",
      "org": "zai-org",
      "name": "GLM-4-9B-Chat",
      "family": "LLM",
      "date": "2024-06-04",
      "tier": "flagship",
      "totalParams": "9B",
      "paramsSource": "card",
      "activatedParams": null,
      "contextLength": "128K",
      "license": "GLM-4 License（other）",
      "downloads": 87488,
      "likes": 708,
      "storageBytes": 56422422209,
      "storageLabel": "56.4 GB",
      "paramsB": 9.0,
      "activeB": null,
      "innovations": [
        "128K 上下文",
        "26 种语言多语言支持",
        "Function Call 自定义工具调用",
        "网页浏览 + 代码执行",
        "长文本推理（1M 上下文版本 / 大海捞针实验）"
      ],
      "benchmarks": [
        {
          "name": "AlignBench-v2",
          "score": 6.61,
          "unit": "score",
          "note": "本模型行"
        },
        {
          "name": "MT-Bench",
          "score": 8.35,
          "unit": "score",
          "note": "本模型行"
        },
        {
          "name": "IFEval",
          "score": 69.0,
          "unit": "%",
          "note": "本模型行"
        },
        {
          "name": "MMLU",
          "score": 72.4,
          "unit": "%",
          "note": "本模型行"
        },
        {
          "name": "C-Eval",
          "score": 75.6,
          "unit": "%",
          "note": "本模型行"
        },
        {
          "name": "GSM8K",
          "score": 79.6,
          "unit": "%",
          "note": "本模型行"
        },
        {
          "name": "MATH",
          "score": 50.6,
          "unit": "%",
          "note": "本模型行"
        },
        {
          "name": "HumanEval",
          "score": 71.8,
          "unit": "%",
          "note": "本模型行"
        },
        {
          "name": "NCB",
          "score": 32.2,
          "unit": "%",
          "note": "本模型行"
        },
        {
          "name": "M-MMLU",
          "score": 56.6,
          "unit": "%",
          "note": "多语言评测表，本模型行"
        },
        {
          "name": "FLORES",
          "score": 28.8,
          "unit": "%",
          "note": "多语言评测表，本模型行"
        },
        {
          "name": "MGSM",
          "score": 65.3,
          "unit": "%",
          "note": "多语言评测表，本模型行"
        },
        {
          "name": "XWinograd",
          "score": 73.1,
          "unit": "%",
          "note": "多语言评测表，本模型行"
        },
        {
          "name": "XStoryCloze",
          "score": 90.7,
          "unit": "%",
          "note": "多语言评测表，本模型行"
        },
        {
          "name": "XCOPA",
          "score": 80.1,
          "unit": "%",
          "note": "多语言评测表，本模型行"
        },
        {
          "name": "BFCL Overall Acc.",
          "score": 81.0,
          "unit": "%",
          "note": "Berkeley Function Calling Leaderboard，本模型行"
        },
        {
          "name": "BFCL AST Summary",
          "score": 80.26,
          "unit": "%",
          "note": "Berkeley Function Calling Leaderboard，本模型行"
        },
        {
          "name": "BFCL Exec Summary",
          "score": 84.4,
          "unit": "%",
          "note": "Berkeley Function Calling Leaderboard，本模型行"
        },
        {
          "name": "BFCL Relevance",
          "score": 87.92,
          "unit": "%",
          "note": "Berkeley Function Calling Leaderboard，本模型行"
        }
      ],
      "headline": {
        "metric": "XStoryCloze",
        "score": 90.7
      },
      "summary": "GLM-4 系列的开源对话模型 GLM-4-9B-Chat，支持 128K 上下文、26 种语言、网页浏览与工具调用，是同代 9B 级开源模型的主力版本。",
      "breakthrough": "把 128K 长上下文、26 种多语言与 Function Call 工具调用同时下放到 9B 开源模型（BFCL Overall Acc. 81.00，逼近 gpt-4-turbo 的 81.24）。",
      "variants": [
        "THUDM/glm-4-9b-chat-hf",
        "THUDM/GLM-4-9B-Chat-1M"
      ]
    },
    {
      "id": "glm-4v-9b",
      "repo": "zai-org/glm-4v-9b",
      "org": "zai-org",
      "name": "GLM-4V-9B",
      "family": "VL",
      "date": "2024-06-04",
      "tier": "major",
      "totalParams": "9B",
      "paramsSource": "card",
      "activatedParams": null,
      "contextLength": "8K",
      "license": "GLM-4 License（other）",
      "downloads": 20715,
      "likes": 268,
      "storageBytes": 27815409466,
      "storageLabel": "27.8 GB",
      "paramsB": 9.0,
      "activeB": null,
      "innovations": [
        "1120 * 1120 高分辨率输入",
        "中英双语多轮对话",
        "文字识别能力（OCRBench 786）",
        "图表理解（AI2D 81.1）",
        "8K 上下文"
      ],
      "benchmarks": [
        {
          "name": "MMBench-EN-Test",
          "score": 81.1,
          "unit": "%",
          "note": "本模型行（英文综合）"
        },
        {
          "name": "MMBench-CN-Test",
          "score": 79.4,
          "unit": "%",
          "note": "本模型行（中文综合）"
        },
        {
          "name": "SEEDBench_IMG",
          "score": 76.8,
          "unit": "%",
          "note": "本模型行（综合能力）"
        },
        {
          "name": "MMStar",
          "score": 58.7,
          "unit": "%",
          "note": "本模型行"
        },
        {
          "name": "MMMU",
          "score": 47.2,
          "unit": "%",
          "note": "本模型行（学科综合）"
        },
        {
          "name": "MME",
          "score": 2163.8,
          "unit": "score",
          "note": "本模型行（感知推理）"
        },
        {
          "name": "HallusionBench",
          "score": 46.6,
          "unit": "%",
          "note": "本模型行（幻觉性）"
        },
        {
          "name": "AI2D",
          "score": 81.1,
          "unit": "%",
          "note": "本模型行（图表理解）"
        },
        {
          "name": "OCRBench",
          "score": 786.0,
          "unit": "score",
          "note": "本模型行（文字识别）"
        }
      ],
      "headline": {
        "metric": "MME",
        "score": 2163.8
      },
      "summary": "GLM-4 系列的开源多模态版本，具备 1120×1120 高分辨率中英双语多轮对话能力，卡内表格自述在中英文综合、感知推理、文字识别、图表理解上超越 GPT-4-turbo-2024-04-09、Gemini 1.0 Pro、Qwen-VL-Max 与 Claude 3 Opus。",
      "breakthrough": "高分辨率文字识别反超闭源旗舰：OCRBench 786 为卡内同表最高（GPT-4o 736、GPT-4v 656），MMBench-EN 81.1 接近 GPT-4o 的 83.4。",
      "variants": []
    },
    {
      "id": "cogvideox-2b",
      "repo": "zai-org/CogVideoX-2b",
      "org": "zai-org",
      "name": "CogVideoX-2B",
      "family": "Video",
      "date": "2024-08-05",
      "tier": "major",
      "totalParams": "2B",
      "paramsSource": "card",
      "activatedParams": null,
      "contextLength": null,
      "license": "Apache-2.0",
      "downloads": 22018,
      "likes": 371,
      "storageBytes": 14206699570,
      "storageLabel": "14.2 GB",
      "paramsB": 2.0,
      "activeB": null,
      "innovations": [
        "Expert Transformer（论文标题）",
        "3d_sincos_pos_embed 位置编码",
        "FP16 训练精度",
        "diffusers FP16 最低 4GB 显存推理",
        "720 x 480 / 6 秒 / 8 fps 视频"
      ],
      "benchmarks": [],
      "headline": null,
      "summary": "CogVideoX 开源文生视频模型的入门版本（2B，FP16 训练），输出 720×480、6 秒、8 fps 视频，主打低成本推理与二次开发。",
      "breakthrough": "把文生视频门槛压到消费级：diffusers FP16 最低 4GB、INT8(torchao) 3.6GB 显存即可推理（推理速度 A100 约 90 秒/50 步）。",
      "variants": [
        "THUDM/CogVideoX-5B"
      ]
    },
    {
      "id": "cogvideox-5b",
      "repo": "zai-org/CogVideoX-5b",
      "org": "zai-org",
      "name": "CogVideoX-5B",
      "family": "Video",
      "date": "2024-08-17",
      "tier": "flagship",
      "totalParams": "5B",
      "paramsSource": "card",
      "activatedParams": null,
      "contextLength": null,
      "license": "CogVideoX LICENSE（other）",
      "downloads": 15371,
      "likes": 688,
      "storageBytes": 21960222900,
      "storageLabel": "22.0 GB",
      "paramsB": 5.0,
      "activeB": null,
      "innovations": [
        "3d_rope_pos_embed 位置编码",
        "BF16 训练精度",
        "更高视频生成质量与视觉特效（自述）",
        "diffusers BF16 最低 5GB 显存推理",
        "支持 INT8 / FP8 量化"
      ],
      "benchmarks": [],
      "headline": null,
      "summary": "CogVideoX 开源文生视频模型的较大规模版本（5B，BF16 训练），相比 2B 版本提供更高的视频生成质量与视觉效果。",
      "breakthrough": "用 3d_rope_pos_embed 替换 3d_sincos_pos_embed 以提升生成质量，推理显存最低 5GB（多卡 15GB，A100 约 180 秒/50 步）。",
      "variants": []
    },
    {
      "id": "glm-4-voice-9b",
      "repo": "zai-org/glm-4-voice-9b",
      "org": "zai-org",
      "name": "GLM-4-Voice-9B",
      "family": "Audio",
      "date": "2024-10-24",
      "tier": "major",
      "totalParams": "9B",
      "paramsSource": "card",
      "activatedParams": null,
      "contextLength": null,
      "license": null,
      "downloads": 8548,
      "likes": 120,
      "storageBytes": 19087777498,
      "storageLabel": "19.1 GB",
      "paramsB": 9.0,
      "activeB": null,
      "innovations": [
        "端到端语音理解与生成",
        "离散化语音 token 的生成与理解",
        "实时语音对话",
        "情感/语调/语速/方言可控",
        "基于 GLM-4-9B 做语音模态预训练与对齐"
      ],
      "benchmarks": [],
      "headline": null,
      "summary": "GLM-4-Voice 端到端语音模型的 LLM 部分：在 GLM-4-9B 基础上做语音模态预训练与对齐，可直接理解和生成中英文离散化语音并实时对话。",
      "breakthrough": "端到端语音对话并可按指令改变情感、语调、语速与方言，无需级联 ASR+TTS。",
      "variants": []
    },
    {
      "id": "cogvideox1-5-5b",
      "repo": "zai-org/CogVideoX1.5-5B",
      "org": "zai-org",
      "name": "CogVideoX1.5-5B",
      "family": "Video",
      "date": "2024-11-02",
      "tier": "major",
      "totalParams": "5B",
      "paramsSource": "card",
      "activatedParams": null,
      "contextLength": null,
      "license": "CogVideoX LICENSE（other）",
      "downloads": 2986,
      "likes": 77,
      "storageBytes": 31053918980,
      "storageLabel": "31.1 GB",
      "paramsB": 5.0,
      "activeB": null,
      "innovations": [
        "分辨率提升至 1360 * 768",
        "支持 5 秒或 10 秒视频",
        "16 frames/second",
        "帧数须为 16N+1（N<=10，默认 81）",
        "BF16 精度 + INT8/FP8 量化"
      ],
      "benchmarks": [],
      "headline": null,
      "summary": "CogVideoX 的 1.5 代 5B 文生/图生视频模型（模型卡标注发布日 2024-11-08），分辨率升到 1360×768、帧率 16 fps、支持 5 秒或 10 秒视频。",
      "breakthrough": "分辨率从 720×480 提升到 1360×768、帧率 8→16 fps，视频时长由 6 秒扩展到 5/10 秒（A100 约 1000 秒/50 步）。",
      "variants": [
        "THUDM/CogVideoX1.5-5B-I2V",
        "THUDM/CogVideoX1.5-5b-SAT"
      ]
    },
    {
      "id": "cogview4-6b",
      "repo": "zai-org/CogView4-6B",
      "org": "zai-org",
      "name": "CogView4-6B",
      "family": "Image",
      "date": "2025-03-03",
      "tier": "minor",
      "totalParams": "6B",
      "paramsSource": "card",
      "activatedParams": null,
      "contextLength": null,
      "license": "Apache-2.0",
      "downloads": 6190,
      "likes": 257,
      "storageBytes": 31128922533,
      "storageLabel": "31.1 GB",
      "paramsB": 6.0,
      "activeB": null,
      "innovations": [
        "中英双语文生图（含中文文字渲染）",
        "DPG-Bench Overall 85.13 超 SDXL/Flux.1-dev/DALL-E 3（卡内表格）",
        "分辨率 512–2048、可被 32 整除、最大 2^21 px",
        "基于 GLM-4-9B（base_model）",
        "BF16/FP32 精度（FP16 不支持，会溢出黑图）"
      ],
      "benchmarks": [
        {
          "name": "DPG-Bench Overall",
          "score": 85.13,
          "unit": "score",
          "note": "本模型行"
        },
        {
          "name": "DPG-Bench Global",
          "score": 83.85,
          "unit": "score",
          "note": "本模型行"
        },
        {
          "name": "DPG-Bench Entity",
          "score": 90.35,
          "unit": "score",
          "note": "本模型行"
        },
        {
          "name": "DPG-Bench Attribute",
          "score": 91.17,
          "unit": "score",
          "note": "本模型行"
        },
        {
          "name": "DPG-Bench Relation",
          "score": 91.14,
          "unit": "score",
          "note": "本模型行"
        },
        {
          "name": "DPG-Bench Other",
          "score": 87.29,
          "unit": "score",
          "note": "本模型行"
        },
        {
          "name": "GenEval Overall",
          "score": 0.73,
          "unit": "ratio",
          "note": "本模型行"
        },
        {
          "name": "GenEval Single Obj.",
          "score": 0.99,
          "unit": "ratio",
          "note": "本模型行"
        },
        {
          "name": "GenEval Two Obj.",
          "score": 0.86,
          "unit": "ratio",
          "note": "本模型行"
        },
        {
          "name": "GenEval Counting",
          "score": 0.66,
          "unit": "ratio",
          "note": "本模型行"
        },
        {
          "name": "GenEval Colors",
          "score": 0.79,
          "unit": "ratio",
          "note": "本模型行"
        },
        {
          "name": "GenEval Position",
          "score": 0.48,
          "unit": "ratio",
          "note": "本模型行"
        },
        {
          "name": "GenEval Color attribution",
          "score": 0.58,
          "unit": "ratio",
          "note": "本模型行"
        },
        {
          "name": "T2I-CompBench Color",
          "score": 0.7786,
          "unit": "ratio",
          "note": "本模型行"
        },
        {
          "name": "T2I-CompBench Shape",
          "score": 0.588,
          "unit": "ratio",
          "note": "本模型行"
        },
        {
          "name": "T2I-CompBench Texture",
          "score": 0.6983,
          "unit": "ratio",
          "note": "本模型行"
        },
        {
          "name": "T2I-CompBench 2D-Spatial",
          "score": 0.3075,
          "unit": "ratio",
          "note": "本模型行"
        },
        {
          "name": "T2I-CompBench 3D-Spatial",
          "score": 0.3708,
          "unit": "ratio",
          "note": "本模型行"
        },
        {
          "name": "T2I-CompBench Numeracy",
          "score": 0.6626,
          "unit": "ratio",
          "note": "本模型行"
        },
        {
          "name": "T2I-CompBench Non-spatial Clip",
          "score": 0.3056,
          "unit": "ratio",
          "note": "本模型行"
        },
        {
          "name": "T2I-CompBench Complex 3-in-1",
          "score": 0.3869,
          "unit": "ratio",
          "note": "本模型行"
        },
        {
          "name": "Chinese Text Accuracy Precision",
          "score": 0.6969,
          "unit": "ratio",
          "note": "中文文字准确率评测，本模型行"
        },
        {
          "name": "Chinese Text Accuracy Recall",
          "score": 0.5532,
          "unit": "ratio",
          "note": "中文文字准确率评测，本模型行"
        },
        {
          "name": "Chinese Text Accuracy F1",
          "score": 0.6168,
          "unit": "ratio",
          "note": "中文文字准确率评测，本模型行"
        },
        {
          "name": "Chinese Text Accuracy Pick@4",
          "score": 0.3265,
          "unit": "ratio",
          "note": "中文文字准确率评测，本模型行"
        }
      ],
      "headline": {
        "metric": "DPG-Bench Attribute",
        "score": 91.17
      },
      "summary": "CogView4-6B 是基于 GLM-4-9B 的中英双语文生图模型（Apache-2.0），卡内 DPG-Bench Overall 85.13 超过 SDXL、Flux.1-dev 与 DALL-E 3，并单独评测了中文文字准确率。",
      "breakthrough": "开源文生图首次把中文文字渲染做成主打能力：中文文字 F1 0.6168 / Pick@4 0.3265，DPG-Bench Overall 85.13 领先同表所有对比模型。",
      "variants": []
    },
    {
      "id": "glm-4-9b-0414",
      "repo": "zai-org/GLM-4-9B-0414",
      "org": "zai-org",
      "name": "GLM-4-9B-0414",
      "family": "LLM",
      "date": "2025-04-07",
      "tier": "major",
      "totalParams": "9B",
      "paramsSource": "card",
      "activatedParams": null,
      "contextLength": null,
      "license": "MIT",
      "downloads": 20652,
      "likes": 111,
      "storageBytes": 18820584952,
      "storageLabel": "18.8 GB",
      "paramsB": 9.0,
      "activeB": null,
      "innovations": [
        "GLM-4-0414 系列 9B 稠密版本",
        "Function Call（JSON 格式工具调用）",
        "MIT 开源许可",
        "轻量本地部署定位"
      ],
      "benchmarks": [],
      "headline": null,
      "summary": "GLM-4-0414 系列的 9B 稠密模型（2025-04 发布，MIT 许可），与 32B 版本共用同一份模型卡文案，卡内评测表只印了 32B 的数据。",
      "breakthrough": null,
      "variants": []
    },
    {
      "id": "glm-4-32b-0414",
      "repo": "zai-org/GLM-4-32B-0414",
      "org": "zai-org",
      "name": "GLM-4-32B-0414",
      "family": "LLM",
      "date": "2025-04-07",
      "tier": "flagship",
      "totalParams": "32B",
      "paramsSource": "card",
      "activatedParams": null,
      "contextLength": null,
      "license": "MIT",
      "downloads": 4342,
      "likes": 489,
      "storageBytes": 65152201576,
      "storageLabel": "65.2 GB",
      "paramsB": 32.0,
      "activeB": null,
      "innovations": [
        "15T 高质量数据预训练（含大量推理型合成数据）",
        "拒绝采样 + 强化学习后训练",
        "工程代码与 Artifact 生成",
        "Function Call / agent 原子能力强化",
        "SWE-bench 多框架评测（Moatless/Agentless/OpenHands）"
      ],
      "benchmarks": [
        {
          "name": "IFEval",
          "score": 87.6,
          "unit": "%",
          "note": "GLM-4-0414 系列表，GLM-4-32B-0414 行"
        },
        {
          "name": "BFCL-v3 (Overall)",
          "score": 69.6,
          "unit": "%",
          "note": "GLM-4-0414 系列表，GLM-4-32B-0414 行"
        },
        {
          "name": "BFCL-v3 (MultiTurn)",
          "score": 41.5,
          "unit": "%",
          "note": "GLM-4-0414 系列表，GLM-4-32B-0414 行"
        },
        {
          "name": "TAU-Bench (Retail)",
          "score": 68.7,
          "unit": "%",
          "note": "GLM-4-0414 系列表，GLM-4-32B-0414 行"
        },
        {
          "name": "TAU-Bench (Airline)",
          "score": 51.2,
          "unit": "%",
          "note": "GLM-4-0414 系列表，GLM-4-32B-0414 行"
        },
        {
          "name": "SimpleQA",
          "score": 88.1,
          "unit": "%",
          "note": "GLM-4-0414 系列表，500 例、带 search/click 工具、3 次平均"
        },
        {
          "name": "HotpotQA",
          "score": 63.8,
          "unit": "%",
          "note": "GLM-4-0414 系列表，500 例、带 search/click 工具、3 次平均"
        },
        {
          "name": "SWE-bench Verified",
          "score": 33.8,
          "unit": "%",
          "note": "框架 Moatless"
        },
        {
          "name": "SWE-bench Verified mini",
          "score": 38.0,
          "unit": "%",
          "note": "框架 Moatless"
        },
        {
          "name": "SWE-bench Verified",
          "score": 30.7,
          "unit": "%",
          "note": "框架 Agentless"
        },
        {
          "name": "SWE-bench Verified mini",
          "score": 34.0,
          "unit": "%",
          "note": "框架 Agentless"
        },
        {
          "name": "SWE-bench Verified",
          "score": 27.2,
          "unit": "%",
          "note": "框架 OpenHands"
        },
        {
          "name": "SWE-bench Verified mini",
          "score": 28.0,
          "unit": "%",
          "note": "框架 OpenHands"
        }
      ],
      "headline": {
        "metric": "SimpleQA",
        "score": 88.1
      },
      "summary": "GLM-4-0414 系列的主力 32B 稠密模型（2025-04 发布，MIT 许可），基座 GLM-4-32B-Base-0414 用 15T 数据预训练，卡内自述在多项基准上对标 GPT-4o 与 DeepSeek-V3-0324(671B)。",
      "breakthrough": "32B 稠密模型在 IFEval(87.6)、BFCL-v3(69.6)、TAU-Bench Retail(68.7)、SimpleQA(88.1) 上追平乃至超过 GPT-4o-1120 与 671B 的 DeepSeek-V3-0324，并以 MIT 许可开源。",
      "variants": []
    },
    {
      "id": "glm-z1-32b-0414",
      "repo": "zai-org/GLM-Z1-32B-0414",
      "org": "zai-org",
      "name": "GLM-Z1-32B-0414",
      "family": "Reasoning",
      "date": "2025-04-08",
      "tier": "flagship",
      "totalParams": "32B",
      "paramsSource": "card",
      "activatedParams": null,
      "contextLength": "32K",
      "license": "mit",
      "downloads": 50636,
      "likes": 196,
      "storageBytes": 65156412214,
      "storageLabel": "65.2 GB",
      "paramsB": 32.0,
      "activeB": null,
      "innovations": [
        "冷启动 + 扩展强化学习",
        "数学/代码/逻辑专项训练",
        "基于成对排序反馈的通用 RL",
        "YaRN 长上下文外推（factor 4.0）",
        "强制思考 <think> 对话模板"
      ],
      "benchmarks": [],
      "headline": null,
      "summary": "基于 GLM-4-32B-0414 经冷启动与扩展强化学习打造的 32B 深度思考推理模型。",
      "breakthrough": "在 32B 开源规模上做出对标 DeepSeek V3/R1 的深度推理能力，数学与复杂任务较底座显著提升。",
      "variants": []
    },
    {
      "id": "glm-z1-rumination-32b-0414",
      "repo": "zai-org/GLM-Z1-Rumination-32B-0414",
      "org": "zai-org",
      "name": "GLM-Z1-Rumination-32B-0414",
      "family": "Reasoning",
      "date": "2025-04-13",
      "tier": "minor",
      "totalParams": "32B",
      "paramsSource": "card",
      "activatedParams": null,
      "contextLength": null,
      "license": "mit",
      "downloads": 625,
      "likes": 119,
      "storageBytes": 66303538176,
      "storageLabel": "66.3 GB",
      "paramsB": 32.0,
      "activeB": null,
      "innovations": [
        "Rumination 沉思式长思考",
        "深度思考中集成搜索工具",
        "多规则奖励端到端 RL",
        "研究型写作与复杂检索",
        "内置 search/click/open/finish 函数调用"
      ],
      "benchmarks": [],
      "headline": null,
      "summary": "对标 OpenAI Deep Research 的沉思式深度推理模型，在长思考过程中调用搜索工具解决开放复杂问题。",
      "breakthrough": "把「长时间深度思考 + 边想边搜索」训成一体能力，研究型写作与复杂检索任务显著提升。",
      "variants": []
    },
    {
      "id": "glm-4-1v-9b-thinking",
      "repo": "zai-org/GLM-4.1V-9B-Thinking",
      "org": "zai-org",
      "name": "GLM-4.1V-9B-Thinking",
      "family": "VL",
      "date": "2025-06-28",
      "tier": "major",
      "totalParams": "9B",
      "paramsSource": "card",
      "activatedParams": null,
      "contextLength": "64k",
      "license": "mit",
      "downloads": 177072,
      "likes": 788,
      "storageBytes": 20605610600,
      "storageLabel": "20.6 GB",
      "paramsB": 9.0,
      "activeB": null,
      "innovations": [
        "Thinking 推理范式 + RL",
        "RLCS 课程采样强化学习",
        "任意宽高比 / 最高 4K 图像输入",
        "64k 上下文",
        "开源 VLM Reward System"
      ],
      "benchmarks": [],
      "headline": null,
      "summary": "基于 GLM-4-9B-0414 的 9B 视觉语言推理模型，在 10B 级 VLM 中取得 SOTA。",
      "breakthrough": "首个以「思考范式 + 强化学习」训练的 GLM-V 模型，在 28 项基准中 23 项为 10B 级最佳、18 项超越 Qwen-2.5-VL-72B。",
      "variants": [
        "zai-org/GLM-4.1V-9B-Base"
      ]
    },
    {
      "id": "glm-4-5",
      "repo": "zai-org/GLM-4.5",
      "org": "zai-org",
      "name": "GLM-4.5",
      "family": "LLM",
      "date": "2025-07-20",
      "tier": "flagship",
      "totalParams": "355B",
      "paramsSource": "card",
      "activatedParams": "32B",
      "contextLength": "128K",
      "license": "mit",
      "downloads": 80489,
      "likes": 1411,
      "storageBytes": 716701364832,
      "storageLabel": "716.7 GB",
      "paramsB": 355.0,
      "activeB": 32.0,
      "innovations": [
        "355B-A32B MoE 架构",
        "混合推理（thinking / non-thinking）",
        "统一推理、编码与 Agent 能力",
        "MTP 层 + EAGLE 投机解码",
        "Base 与 FP8 版同步开源"
      ],
      "benchmarks": [
        {
          "name": "12 项行业标准基准综合平均分",
          "score": 63.2,
          "unit": "score",
          "note": "全部专有与开源模型中排名第 3"
        }
      ],
      "headline": {
        "metric": "12 项行业标准基准综合平均分",
        "score": 63.2
      },
      "summary": "面向智能体的 355B-A32B MoE 基础模型，统一推理、编码与智能体能力，支持思考/非思考双模式。",
      "breakthrough": "以 355B-A32B 规模在 12 项标准基准上取得 63.2 的综合分，位列所有专有与开源模型第 3。",
      "variants": [
        "zai-org/GLM-4.5-FP8",
        "zai-org/GLM-4.5-Base"
      ]
    },
    {
      "id": "glm-4-5-air",
      "repo": "zai-org/GLM-4.5-Air",
      "org": "zai-org",
      "name": "GLM-4.5-Air",
      "family": "LLM",
      "date": "2025-07-20",
      "tier": "major",
      "totalParams": "106B",
      "paramsSource": "card",
      "activatedParams": "12B",
      "contextLength": "128K",
      "license": "mit",
      "downloads": 101674,
      "likes": 635,
      "storageBytes": 220959914155,
      "storageLabel": "221.0 GB",
      "paramsB": 106.0,
      "activeB": 12.0,
      "innovations": [
        "106B-A12B 紧凑 MoE",
        "混合推理（thinking / non-thinking）",
        "高效轻量部署",
        "MTP 层 + EAGLE 投机解码",
        "Base 与 FP8 版同步开源"
      ],
      "benchmarks": [
        {
          "name": "12 项行业标准基准综合平均分",
          "score": 59.8,
          "unit": "score",
          "note": "同 GLM-4.5 的 12 项行业标准基准"
        }
      ],
      "headline": {
        "metric": "12 项行业标准基准综合平均分",
        "score": 59.8
      },
      "summary": "GLM-4.5 系列中更紧凑高效的 106B-A12B MoE 版本，兼顾性能与部署效率。",
      "breakthrough": "以 106B-A12B 的紧凑设计拿到 59.8 的综合分，接近 355B 旗舰而推理成本大幅降低。",
      "variants": [
        "zai-org/GLM-4.5-Air-FP8",
        "zai-org/GLM-4.5-Air-Base"
      ]
    },
    {
      "id": "glm-4-5v",
      "repo": "zai-org/GLM-4.5V",
      "org": "zai-org",
      "name": "GLM-4.5V",
      "family": "VL",
      "date": "2025-08-10",
      "tier": "flagship",
      "totalParams": "106B",
      "paramsSource": "card",
      "activatedParams": "12B",
      "contextLength": null,
      "license": "mit",
      "downloads": 45375,
      "likes": 722,
      "storageBytes": 215444371315,
      "storageLabel": "215.4 GB",
      "paramsB": 106.0,
      "activeB": 12.0,
      "innovations": [
        "基于 GLM-4.5-Air 的 MoE 视觉语言模型",
        "42 项视觉语言基准同规模 SOTA",
        "Thinking 模式开关",
        "精确 Grounding（bbox）",
        "GUI / 桌面助手 Agent"
      ],
      "benchmarks": [],
      "headline": null,
      "summary": "以 GLM-4.5-Air（106B-12B active）为底座的旗舰视觉语言模型，覆盖图像、视频、文档理解与 GUI 操作。",
      "breakthrough": "在 42 项公开视觉语言基准上取得同规模 SOTA，并把 Grounding 与 GUI Agent 能力做进模型。",
      "variants": []
    },
    {
      "id": "glm-4-6",
      "repo": "zai-org/GLM-4.6",
      "org": "zai-org",
      "name": "GLM-4.6",
      "family": "LLM",
      "date": "2025-09-29",
      "tier": "flagship",
      "totalParams": null,
      "paramsSource": null,
      "activatedParams": null,
      "contextLength": "200K",
      "license": "mit",
      "downloads": 18342,
      "likes": 1235,
      "storageBytes": 713597382171,
      "storageLabel": "713.6 GB",
      "paramsB": null,
      "activeB": null,
      "innovations": [
        "上下文窗口 128K → 200K",
        "推理中工具调用（TIR）",
        "搜索 Agent 专用轨迹格式",
        "更强的 agentic coding",
        "写作与角色扮演优化"
      ],
      "benchmarks": [],
      "headline": null,
      "summary": "在 GLM-4.5 基础上把上下文扩到 200K 并全面强化编码、推理、工具与写作的迭代版本。",
      "breakthrough": "上下文从 128K 扩到 200K 以支撑更复杂 Agent 任务，在 8 项公开基准上对 GLM-4.5 全面提分。",
      "variants": []
    },
    {
      "id": "glyph",
      "repo": "zai-org/Glyph",
      "org": "zai-org",
      "name": "Glyph",
      "family": "VL",
      "date": "2025-10-25",
      "tier": "minor",
      "totalParams": null,
      "paramsSource": null,
      "activatedParams": null,
      "contextLength": null,
      "license": "mit",
      "downloads": 305,
      "likes": 74,
      "storageBytes": 20605614803,
      "storageLabel": "20.6 GB",
      "paramsB": null,
      "activeB": null,
      "innovations": [
        "视觉-文本压缩扩展上下文",
        "长文本渲染为图像 + VLM 处理",
        "基于 GLM-4.1V-9B-Base",
        "把长上下文建模转为多模态问题",
        "大幅降低计算与显存开销"
      ],
      "benchmarks": [],
      "headline": null,
      "summary": "把长文本渲染成图像、交由视觉语言模型处理的上下文扩展框架。",
      "breakthrough": "不改 token 级上下文窗口，而是把长上下文转成视觉压缩问题，在保留语义的同时大幅降低计算与显存成本。",
      "variants": []
    },
    {
      "id": "glm-4-6v-flash",
      "repo": "zai-org/GLM-4.6V-Flash",
      "org": "zai-org",
      "name": "GLM-4.6V-Flash",
      "family": "VL",
      "date": "2025-12-07",
      "tier": "flagship",
      "totalParams": "9B",
      "paramsSource": "card",
      "activatedParams": null,
      "contextLength": "128k",
      "license": "mit",
      "downloads": 78394,
      "likes": 628,
      "storageBytes": 20605614747,
      "storageLabel": "20.6 GB",
      "paramsB": 9.0,
      "activeB": null,
      "innovations": [
        "原生多模态 Function Calling",
        "图文交错内容生成",
        "128k 多文档/长文档理解",
        "前端截图还原 HTML/CSS",
        "GLM-V 系列 9B 轻量版"
      ],
      "benchmarks": [],
      "headline": null,
      "summary": "GLM-4.6V 系列的 9B 轻量多模态模型，面向本地部署与低延迟场景。",
      "breakthrough": "首次在 GLM-V 系列引入原生 Function Calling，把「视觉感知」直接接到「可执行动作」。",
      "variants": []
    },
    {
      "id": "autoglm-phone-9b",
      "repo": "zai-org/AutoGLM-Phone-9B",
      "org": "zai-org",
      "name": "AutoGLM-Phone-9B",
      "family": "Agent",
      "date": "2025-12-08",
      "tier": "major",
      "totalParams": "9B",
      "paramsSource": "card",
      "activatedParams": null,
      "contextLength": null,
      "license": "mit",
      "downloads": 2563,
      "likes": 444,
      "storageBytes": 20605612288,
      "storageLabel": "20.6 GB",
      "paramsB": 9.0,
      "activeB": null,
      "innovations": [
        "手机 GUI Agent 模型",
        "多模态屏幕理解 + 智能规划",
        "ADB 远程控制设备",
        "敏感操作确认 / 人工兜底",
        "MobileRL 在线智能体强化学习"
      ],
      "benchmarks": [],
      "headline": null,
      "summary": "AutoGLM 手机智能助手框架中的开源模型，理解手机屏幕并自动完成跨 App 操作任务。",
      "breakthrough": "把视觉语言模型直接接进真实手机 GUI：自然语言下达任务即可自动解析意图、规划并执行操作。",
      "variants": []
    },
    {
      "id": "glm-asr-nano-2512",
      "repo": "zai-org/GLM-ASR-Nano-2512",
      "org": "zai-org",
      "name": "GLM-ASR-Nano-2512",
      "family": "Audio",
      "date": "2025-12-09",
      "tier": "major",
      "totalParams": "1.5B",
      "paramsSource": "card",
      "activatedParams": null,
      "contextLength": null,
      "license": "mit",
      "downloads": 56071,
      "likes": 389,
      "storageBytes": 9040649552,
      "storageLabel": "9.0 GB",
      "paramsB": 1.5,
      "activeB": null,
      "innovations": [
        "1.5B 语音识别模型",
        "粤语等方言优化",
        "低音量/耳语语音鲁棒性",
        "中文基准领先（Wenet Meeting、Aishell-1）",
        "支持 transformers / vLLM / SGLang"
      ],
      "benchmarks": [
        {
          "name": "Average error rate",
          "score": 4.1,
          "unit": "%",
          "note": "同类开源模型中平均错误率最低（Wenet Meeting、Aishell-1 等中文基准优势明显）"
        }
      ],
      "headline": {
        "metric": "Average error rate",
        "score": 4.1
      },
      "summary": "1.5B 的开源语音识别模型，重点优化方言与低音量场景。",
      "breakthrough": "以 1.5B 规模取得同类开源模型最低平均错误率 4.10，并在多基准上超过 OpenAI Whisper V3。",
      "variants": []
    },
    {
      "id": "glm-4-7",
      "repo": "zai-org/GLM-4.7",
      "org": "zai-org",
      "name": "GLM-4.7",
      "family": "LLM",
      "date": "2025-12-22",
      "tier": "flagship",
      "totalParams": null,
      "paramsSource": null,
      "activatedParams": null,
      "contextLength": null,
      "license": "mit",
      "downloads": 75379,
      "likes": 2054,
      "storageBytes": 716701167491,
      "storageLabel": "716.7 GB",
      "paramsB": null,
      "activeB": null,
      "innovations": [
        "Interleaved Thinking",
        "Preserved Thinking（跨轮保留思考块）",
        "Turn-level Thinking（逐轮思考开关）",
        "多语言 agentic coding",
        "工具使用（τ²-Bench / BrowseComp）"
      ],
      "benchmarks": [
        {
          "name": "MMLU-Pro",
          "score": 84.3,
          "unit": "%",
          "note": ""
        },
        {
          "name": "GPQA-Diamond",
          "score": 85.7,
          "unit": "%",
          "note": ""
        },
        {
          "name": "HLE",
          "score": 24.8,
          "unit": "%",
          "note": ""
        },
        {
          "name": "HLE (w/ Tools)",
          "score": 42.8,
          "unit": "%",
          "note": "较 GLM-4.6 提升 12.4"
        },
        {
          "name": "AIME 2025",
          "score": 95.7,
          "unit": "%",
          "note": ""
        },
        {
          "name": "HMMT Feb. 2025",
          "score": 97.1,
          "unit": "%",
          "note": ""
        },
        {
          "name": "HMMT Nov. 2025",
          "score": 93.5,
          "unit": "%",
          "note": ""
        },
        {
          "name": "IMOAnswerBench",
          "score": 82.0,
          "unit": "%",
          "note": ""
        },
        {
          "name": "LiveCodeBench-v6",
          "score": 84.9,
          "unit": "%",
          "note": ""
        },
        {
          "name": "SWE-bench Verified",
          "score": 73.8,
          "unit": "%",
          "note": "较 GLM-4.6 提升 5.8"
        },
        {
          "name": "SWE-bench Multilingual",
          "score": 66.7,
          "unit": "%",
          "note": "较 GLM-4.6 提升 12.9"
        },
        {
          "name": "Terminal Bench Hard",
          "score": 33.3,
          "unit": "%",
          "note": ""
        },
        {
          "name": "Terminal Bench 2.0",
          "score": 41.0,
          "unit": "%",
          "note": "较 GLM-4.6 提升 16.5"
        },
        {
          "name": "BrowseComp",
          "score": 52.0,
          "unit": "%",
          "note": ""
        },
        {
          "name": "BrowseComp (w/ Context Manage)",
          "score": 67.5,
          "unit": "%",
          "note": ""
        },
        {
          "name": "BrowseComp-Zh",
          "score": 66.6,
          "unit": "%",
          "note": ""
        },
        {
          "name": "τ²-Bench",
          "score": 87.4,
          "unit": "%",
          "note": ""
        }
      ],
      "headline": {
        "metric": "HMMT Feb. 2025",
        "score": 97.1
      },
      "summary": "面向编码与 Agent 的旗舰模型，强化 UI/Vibe Coding、工具使用与复杂推理能力。",
      "breakthrough": "SWE-bench Verified 73.8%（+5.8）、Terminal Bench 2.0 41.0%（+16.5）、HLE w/ Tools 42.8%（+12.4）较 GLM-4.6 大幅提升，并新增 Preserved Thinking。",
      "variants": [
        "zai-org/GLM-4.7-FP8"
      ]
    },
    {
      "id": "glm-image",
      "repo": "zai-org/GLM-Image",
      "org": "zai-org",
      "name": "GLM-Image",
      "family": "Image",
      "date": "2026-01-08",
      "tier": "major",
      "totalParams": null,
      "paramsSource": null,
      "activatedParams": null,
      "contextLength": null,
      "license": "mit",
      "downloads": 10117,
      "likes": 1107,
      "storageBytes": 35790534671,
      "storageLabel": "35.8 GB",
      "paramsB": null,
      "activeB": null,
      "innovations": [
        "自回归 + 扩散混合解码器架构",
        "9B 自回归生成器（GLM-4-9B-0414 初始化）",
        "7B 单流 DiT 扩散解码器",
        "Glyph Encoder 文本渲染模块",
        "解耦式 GRPO 后训练"
      ],
      "benchmarks": [
        {
          "name": "CVTG-2K Word Accuracy",
          "score": 0.9116,
          "unit": "raw",
          "note": ""
        },
        {
          "name": "CVTG-2K NED",
          "score": 0.9557,
          "unit": "raw",
          "note": ""
        },
        {
          "name": "CVTG-2K CLIPScore",
          "score": 0.7877,
          "unit": "raw",
          "note": ""
        },
        {
          "name": "LongText-Bench AVG",
          "score": 0.966,
          "unit": "raw",
          "note": ""
        },
        {
          "name": "LongText-Bench EN",
          "score": 0.952,
          "unit": "raw",
          "note": ""
        },
        {
          "name": "LongText-Bench ZH",
          "score": 0.979,
          "unit": "raw",
          "note": ""
        },
        {
          "name": "OneIG-Bench EN",
          "score": 0.528,
          "unit": "raw",
          "note": ""
        },
        {
          "name": "OneIG-Bench ZH",
          "score": 0.511,
          "unit": "raw",
          "note": ""
        },
        {
          "name": "TIIF-Bench short",
          "score": 81.01,
          "unit": "raw",
          "note": ""
        },
        {
          "name": "TIIF-Bench long",
          "score": 81.02,
          "unit": "raw",
          "note": ""
        },
        {
          "name": "DPG-Bench",
          "score": 84.78,
          "unit": "raw",
          "note": ""
        }
      ],
      "headline": null,
      "summary": "混合自回归 + 扩散解码器的图像生成模型，在文本渲染与知识密集型生成上优势明显。",
      "breakthrough": "CVTG-2K 词准确率 0.9116 / NED 0.9557、LongText-Bench ZH 0.979，文本渲染能力显著领先同表开源与闭源模型。",
      "variants": []
    },
    {
      "id": "glm-4-7-flash",
      "repo": "zai-org/GLM-4.7-Flash",
      "org": "zai-org",
      "name": "GLM-4.7-Flash",
      "family": "LLM",
      "date": "2026-01-19",
      "tier": "flagship",
      "totalParams": "30B",
      "paramsSource": "card",
      "activatedParams": "3B",
      "contextLength": null,
      "license": "mit",
      "downloads": 1882455,
      "likes": 1838,
      "storageBytes": 62937229623,
      "storageLabel": "62.9 GB",
      "paramsB": 30.0,
      "activeB": 3.0,
      "innovations": [
        "30B-A3B MoE 架构",
        "30B 级最强（模型卡自述）",
        "Preserved Thinking",
        "MTP 投机解码",
        "轻量部署（vLLM / SGLang）"
      ],
      "benchmarks": [
        {
          "name": "AIME 25",
          "score": 91.6,
          "unit": "%",
          "note": ""
        },
        {
          "name": "GPQA",
          "score": 75.2,
          "unit": "%",
          "note": ""
        },
        {
          "name": "LCB v6",
          "score": 64.0,
          "unit": "%",
          "note": ""
        },
        {
          "name": "HLE",
          "score": 14.4,
          "unit": "%",
          "note": ""
        },
        {
          "name": "SWE-bench Verified",
          "score": 59.2,
          "unit": "%",
          "note": ""
        },
        {
          "name": "τ²-Bench",
          "score": 79.5,
          "unit": "%",
          "note": ""
        },
        {
          "name": "BrowseComp",
          "score": 42.8,
          "unit": "%",
          "note": ""
        }
      ],
      "headline": {
        "metric": "AIME 25",
        "score": 91.6
      },
      "summary": "30B-A3B 的 MoE 轻量模型，主打 30B 级别性能与效率平衡。",
      "breakthrough": "以 30B-A3B 在 SWE-bench Verified 59.2、τ²-Bench 79.5 上大幅领先同量级 Qwen3-30B-A3B-Thinking-2507 与 GPT-OSS-20B。",
      "variants": []
    },
    {
      "id": "glm-ocr",
      "repo": "zai-org/GLM-OCR",
      "org": "zai-org",
      "name": "GLM-OCR",
      "family": "OCR",
      "date": "2026-01-30",
      "tier": "flagship",
      "totalParams": "0.9B",
      "paramsSource": "card",
      "activatedParams": null,
      "contextLength": null,
      "license": "mit",
      "downloads": 1889384,
      "likes": 2032,
      "storageBytes": 2650754336,
      "storageLabel": "2.7 GB",
      "paramsB": 0.9,
      "activeB": null,
      "innovations": [
        "Multi-Token Prediction (MTP) loss",
        "全任务稳定强化学习",
        "CogViT 视觉编码器",
        "GLM-0.5B 语言解码器 + 轻量跨模态连接器",
        "PP-DocLayout-V3 布局分析 + 并行识别两阶段流水线"
      ],
      "benchmarks": [
        {
          "name": "OmniDocBench V1.5",
          "score": 94.62,
          "unit": "score",
          "note": "排名 #1 overall"
        }
      ],
      "headline": {
        "metric": "OmniDocBench V1.5",
        "score": 94.62
      },
      "summary": "0.9B 参数的多模态 OCR 模型，面向复杂文档解析与结构化信息抽取。",
      "breakthrough": "以 0.9B 规模在 OmniDocBench V1.5 取得 94.62 分排名第一，并可在 vLLM/SGLang/Ollama 上高并发部署。",
      "variants": []
    },
    {
      "id": "glm-5",
      "repo": "zai-org/GLM-5",
      "org": "zai-org",
      "name": "GLM-5",
      "family": "LLM",
      "date": "2026-02-11",
      "tier": "flagship",
      "totalParams": "744B",
      "paramsSource": "card",
      "activatedParams": "40B",
      "contextLength": "200K",
      "license": "mit",
      "downloads": 58754,
      "likes": 2119,
      "storageBytes": 1507756766358,
      "storageLabel": "1.5 TB",
      "paramsB": 744.0,
      "activeB": 40.0,
      "innovations": [
        "744B-A40B MoE",
        "DeepSeek Sparse Attention (DSA)",
        "slime 异步 RL 基础设施",
        "预训练数据 23T → 28.5T tokens",
        "MTP 投机解码（num_speculative_tokens 3）"
      ],
      "benchmarks": [
        {
          "name": "HLE",
          "score": 30.5,
          "unit": "%",
          "note": ""
        },
        {
          "name": "HLE (w/ Tools)",
          "score": 50.4,
          "unit": "%",
          "note": ""
        },
        {
          "name": "AIME 2026 I",
          "score": 92.7,
          "unit": "%",
          "note": ""
        },
        {
          "name": "HMMT Nov. 2025",
          "score": 96.9,
          "unit": "%",
          "note": ""
        },
        {
          "name": "IMOAnswerBench",
          "score": 82.5,
          "unit": "%",
          "note": ""
        },
        {
          "name": "GPQA-Diamond",
          "score": 86.0,
          "unit": "%",
          "note": ""
        },
        {
          "name": "SWE-bench Verified",
          "score": 77.8,
          "unit": "%",
          "note": ""
        },
        {
          "name": "SWE-bench Multilingual",
          "score": 73.3,
          "unit": "%",
          "note": ""
        },
        {
          "name": "Terminal-Bench 2.0 (Terminus 2)",
          "score": 56.2,
          "unit": "%",
          "note": "模型卡写作 56.2 / 60.7 †（† 为修正版 Terminal-Bench 2.0）"
        },
        {
          "name": "Terminal-Bench 2.0 (Claude Code)",
          "score": 56.2,
          "unit": "%",
          "note": "模型卡写作 56.2 / 61.1 †"
        },
        {
          "name": "CyberGym",
          "score": 43.2,
          "unit": "%",
          "note": ""
        },
        {
          "name": "BrowseComp",
          "score": 62.0,
          "unit": "%",
          "note": ""
        },
        {
          "name": "BrowseComp (w/ Context Manage)",
          "score": 75.9,
          "unit": "%",
          "note": ""
        },
        {
          "name": "BrowseComp-Zh",
          "score": 72.7,
          "unit": "%",
          "note": ""
        },
        {
          "name": "τ²-Bench",
          "score": 89.7,
          "unit": "%",
          "note": ""
        },
        {
          "name": "MCP-Atlas (Public Set)",
          "score": 67.8,
          "unit": "%",
          "note": ""
        },
        {
          "name": "Tool-Decathlon",
          "score": 38.0,
          "unit": "%",
          "note": ""
        },
        {
          "name": "Vending Bench 2",
          "score": 4432.12,
          "unit": "$",
          "note": ""
        }
      ],
      "headline": {
        "metric": "HMMT Nov. 2025",
        "score": 96.9
      },
      "summary": "面向复杂系统工程与长程 Agent 任务的 744B-A40B 开源旗舰模型。",
      "breakthrough": "从 GLM-4.5 的 355B-A32B 扩到 744B-A40B、预训练数据从 23T 增到 28.5T，并在推理/编码/Agent 上取得全球开源最佳，逼近前沿闭源模型。",
      "variants": []
    },
    {
      "id": "glm-5-1",
      "repo": "zai-org/GLM-5.1",
      "org": "zai-org",
      "name": "GLM-5.1",
      "family": "LLM",
      "date": "2026-04-03",
      "tier": "major",
      "totalParams": null,
      "paramsSource": null,
      "activatedParams": null,
      "contextLength": null,
      "license": "mit",
      "downloads": 82309,
      "likes": 1841,
      "storageBytes": 1507756036618,
      "storageLabel": "1.5 TB",
      "paramsB": null,
      "activeB": null,
      "innovations": [
        "长程 agentic 工程能力",
        "SWE-Bench Pro 领先",
        "数百轮迭代持续优化",
        "数千次工具调用不退化",
        "SGLang/vLLM/xLLM/KTransformers 多框架支持"
      ],
      "benchmarks": [
        {
          "name": "HLE",
          "score": 31.0,
          "unit": "%",
          "note": ""
        },
        {
          "name": "HLE (w/ Tools)",
          "score": 52.3,
          "unit": "%",
          "note": ""
        },
        {
          "name": "AIME 2026",
          "score": 95.3,
          "unit": "%",
          "note": ""
        },
        {
          "name": "HMMT Nov. 2025",
          "score": 94.0,
          "unit": "%",
          "note": ""
        },
        {
          "name": "HMMT Feb. 2026",
          "score": 82.6,
          "unit": "%",
          "note": ""
        },
        {
          "name": "IMOAnswerBench",
          "score": 83.8,
          "unit": "%",
          "note": ""
        },
        {
          "name": "GPQA-Diamond",
          "score": 86.2,
          "unit": "%",
          "note": ""
        },
        {
          "name": "SWE-Bench Pro",
          "score": 58.4,
          "unit": "%",
          "note": "表中加粗，为该列最佳"
        },
        {
          "name": "NL2Repo",
          "score": 42.7,
          "unit": "%",
          "note": ""
        },
        {
          "name": "Terminal-Bench 2.0 (Terminus-2)",
          "score": 63.5,
          "unit": "%",
          "note": ""
        },
        {
          "name": "Terminal-Bench 2.0 (Best self-reported)",
          "score": 69.0,
          "unit": "%",
          "note": "模型卡标注 Claude Code"
        },
        {
          "name": "CyberGym",
          "score": 68.7,
          "unit": "%",
          "note": "表中加粗，为该列最佳"
        },
        {
          "name": "BrowseComp",
          "score": 68.0,
          "unit": "%",
          "note": "表中加粗，为该列最佳"
        },
        {
          "name": "BrowseComp (w/ Context Manage)",
          "score": 79.3,
          "unit": "%",
          "note": ""
        },
        {
          "name": "τ³-Bench",
          "score": 70.6,
          "unit": "%",
          "note": ""
        },
        {
          "name": "MCP-Atlas (Public Set)",
          "score": 71.8,
          "unit": "%",
          "note": ""
        },
        {
          "name": "Tool-Decathlon",
          "score": 40.7,
          "unit": "%",
          "note": ""
        },
        {
          "name": "Vending Bench 2",
          "score": 5634.41,
          "unit": "$",
          "note": ""
        }
      ],
      "headline": {
        "metric": "AIME 2026",
        "score": 95.3
      },
      "summary": "面向 agentic 工程的下一代旗舰模型，重点提升长程任务中的持续优化能力。",
      "breakthrough": "在长程任务上可维持数百轮优化、数千次工具调用持续提分（SWE-Bench Pro 58.4 领先 GLM-5、Terminal-Bench 2.0 63.5 vs GLM-5 的 56.2）。",
      "variants": []
    },
    {
      "id": "scail-2",
      "repo": "zai-org/SCAIL-2",
      "org": "zai-org",
      "name": "SCAIL-2",
      "family": "Video",
      "date": "2026-06-09",
      "tier": "minor",
      "totalParams": null,
      "paramsSource": null,
      "activatedParams": null,
      "contextLength": null,
      "license": "mit",
      "downloads": 6445,
      "likes": 333,
      "storageBytes": 82457219401,
      "storageLabel": "82.5 GB",
      "paramsB": null,
      "activeB": null,
      "innovations": [
        "端到端受控角色动画（无中间姿态表征）",
        "Unified Motion Transfer Interface + 专用掩码通道与 RoPE",
        "6 万 motion pairs 合成数据训练",
        "反向驱动训练配方",
        "跨身份换人 / 动物驱动 / SAM3D-Body 零样本"
      ],
      "benchmarks": [],
      "headline": null,
      "summary": "端到端受控角色动画模型，用驱动视频直接驱动参考角色，不依赖骨架或掩码等中间表征。",
      "breakthrough": "去掉骨架/掩码中间表示实现端到端驱动，并涌现出跨身份换人、动物驱动、多角色与 SAM3D-Body 零样本控制等能力。",
      "variants": []
    },
    {
      "id": "glm-5-2",
      "repo": "zai-org/GLM-5.2",
      "org": "zai-org",
      "name": "GLM-5.2",
      "family": "LLM",
      "date": "2026-06-16",
      "tier": "flagship",
      "totalParams": null,
      "paramsSource": null,
      "activatedParams": null,
      "contextLength": "1M",
      "license": "mit",
      "downloads": 932248,
      "likes": 5084,
      "storageBytes": 1506689458421,
      "storageLabel": "1.5 TB",
      "paramsB": null,
      "activeB": null,
      "innovations": [
        "solid 1M token 上下文",
        "IndexShare（每 4 层稀疏注意力复用同一 indexer）",
        "每 token FLOPs 降低 2.9×",
        "MTP 层改进，接受长度最高 +20%",
        "思考强度（effort）分级"
      ],
      "benchmarks": [
        {
          "name": "HLE",
          "score": 40.5,
          "unit": "%",
          "note": ""
        },
        {
          "name": "HLE (w/ Tools)",
          "score": 54.7,
          "unit": "%",
          "note": ""
        },
        {
          "name": "CritPt",
          "score": 20.9,
          "unit": "%",
          "note": ""
        },
        {
          "name": "AIME 2026",
          "score": 99.2,
          "unit": "%",
          "note": ""
        },
        {
          "name": "HMMT Nov. 2025",
          "score": 94.4,
          "unit": "%",
          "note": ""
        },
        {
          "name": "HMMT Feb. 2026",
          "score": 92.5,
          "unit": "%",
          "note": ""
        },
        {
          "name": "IMOAnswerBench",
          "score": 91.0,
          "unit": "%",
          "note": ""
        },
        {
          "name": "GPQA-Diamond",
          "score": 91.2,
          "unit": "%",
          "note": ""
        },
        {
          "name": "SWE-bench Pro",
          "score": 62.1,
          "unit": "%",
          "note": ""
        },
        {
          "name": "NL2Repo",
          "score": 48.9,
          "unit": "%",
          "note": ""
        },
        {
          "name": "DeepSWE",
          "score": 46.2,
          "unit": "%",
          "note": ""
        },
        {
          "name": "ProgramBench",
          "score": 63.7,
          "unit": "%",
          "note": ""
        },
        {
          "name": "Terminal Bench 2.1 (Terminus-2)",
          "score": 81.0,
          "unit": "%",
          "note": ""
        },
        {
          "name": "Terminal Bench 2.1 (Best Reported Harness)",
          "score": 82.7,
          "unit": "%",
          "note": ""
        },
        {
          "name": "FrontierSWE (Dominance)",
          "score": 74.4,
          "unit": "%",
          "note": ""
        },
        {
          "name": "PostTrainBench",
          "score": 34.3,
          "unit": "%",
          "note": ""
        },
        {
          "name": "SWE-Marathon",
          "score": 13.0,
          "unit": "%",
          "note": ""
        },
        {
          "name": "MCP-Atlas (Public Set)",
          "score": 76.8,
          "unit": "%",
          "note": ""
        },
        {
          "name": "Tool-Decathlon",
          "score": 48.2,
          "unit": "%",
          "note": ""
        }
      ],
      "headline": {
        "metric": "AIME 2026",
        "score": 99.2
      },
      "summary": "首个能在 1M token 上下文上稳定支撑长程任务的旗舰模型，并提出 IndexShare 稀疏注意力。",
      "breakthrough": "solid 1M 上下文 + IndexShare 使 1M 长度下每 token FLOPs 降 2.9×，HLE 40.5、AIME 2026 99.2 大幅超越 GLM-5.1。",
      "variants": [
        "zai-org/GLM-5.3-BF16"
      ]
    },
    {
      "id": "glm-5-3",
      "repo": "zai-org/GLM-5.3",
      "org": "zai-org",
      "name": "GLM-5.3",
      "family": "LLM",
      "date": "2026-08-25",
      "tier": "flagship",
      "totalParams": null,
      "paramsSource": null,
      "activatedParams": null,
      "contextLength": "1M",
      "license": "other (glm-5.3)",
      "downloads": 635504,
      "likes": 1811,
      "storageBytes": 755681496428,
      "storageLabel": "755.7 GB",
      "paramsB": null,
      "activeB": null,
      "innovations": [
        "与 GLM-5.2 同基座，增益全部来自后训练",
        "Z.ai Code Bench 较 GLM-5.2 提升 50%",
        "Terminal Bench 3.0 / Agents' Last Exam 开源 SOTA",
        "涌现网络攻防能力（CyberGym / ExploitGym）",
        "reasoning_effort 三档思考预算（low/high/max）"
      ],
      "benchmarks": [
        {
          "name": "Terminal Bench 2.1",
          "score": 88.2,
          "unit": "%",
          "note": ""
        },
        {
          "name": "Terminal Bench 3.0",
          "score": 28.3,
          "unit": "%",
          "note": ""
        },
        {
          "name": "DeepSWE (v1.1)",
          "score": 66.9,
          "unit": "%",
          "note": ""
        },
        {
          "name": "NL2Repo",
          "score": 58.0,
          "unit": "%",
          "note": ""
        },
        {
          "name": "ProgramBench (Almost Solved)",
          "score": 19.0,
          "unit": "%",
          "note": ""
        },
        {
          "name": "FrontierSWE",
          "score": 78.1,
          "unit": "%",
          "note": ""
        },
        {
          "name": "SWE-Marathon (v1.1)",
          "score": 42.5,
          "unit": "%",
          "note": ""
        },
        {
          "name": "PostTrainBench",
          "score": 39.8,
          "unit": "%",
          "note": ""
        },
        {
          "name": "CyberGym",
          "score": 84.5,
          "unit": "%",
          "note": "表中加粗，为该列最佳"
        },
        {
          "name": "ExploitBench",
          "score": 54.4,
          "unit": "%",
          "note": ""
        },
        {
          "name": "Toolathlon Verified",
          "score": 73.0,
          "unit": "%",
          "note": ""
        },
        {
          "name": "AutomationBench (v1.0.6)",
          "score": 48.2,
          "unit": "%",
          "note": "表中加粗，为该列最佳"
        },
        {
          "name": "Agents' Last Exam (ALE-CLI)",
          "score": 28.5,
          "unit": "%",
          "note": ""
        },
        {
          "name": "HLE w/ Tools",
          "score": 62.5,
          "unit": "%",
          "note": ""
        },
        {
          "name": "GDPval-AA v2",
          "score": 1769.0,
          "unit": "score",
          "note": "表中加粗，为该列最佳"
        }
      ],
      "headline": {
        "metric": "GDPval-AA v2",
        "score": 1769.0
      },
      "summary": "与 GLM-5.2 共用基座、所有提升来自后训练的编码与长程任务强化版。",
      "breakthrough": "编码能力较 GLM-5.2 提升 50%（自研 Z.ai Code Bench），CyberGym 84.5 居 SOTA，ExploitGym 2h/6h 达 105/130（GLM-5.2 为 29/39）。",
      "variants": []
    },
    {
      "id": "glm-5-3-flash",
      "repo": "zai-org/GLM-5.3-Flash",
      "org": "zai-org",
      "name": "GLM-5.3-Flash",
      "family": "LLM",
      "date": "2026-08-25",
      "tier": "flagship",
      "totalParams": "320B",
      "paramsSource": "card",
      "activatedParams": "18B",
      "contextLength": null,
      "license": "mit",
      "downloads": 1333574,
      "likes": 2269,
      "storageBytes": 656694018754,
      "storageLabel": "656.7 GB",
      "paramsB": 320.0,
      "activeB": 18.0,
      "innovations": [
        "GLM-5 系列首个原生多模态模型",
        "稀疏 + 线性注意力混合架构",
        "Manifold-Constrained Hyper-Connections (mHC)",
        "30T token 多模态预训练语料",
        "价格约为 GLM-5.2 的十分之一"
      ],
      "benchmarks": [],
      "headline": null,
      "summary": "GLM-5 系列首个原生多模态模型，320B-A18B，主打低成本高性能。",
      "breakthrough": "首次在 GLM 系列引入稀疏+线性混合注意力与 mHC 超连接，320B-18B 以十分之一价格超过 GLM-5.2 并逼近 Claude Opus 4.8 的编码/Agent 水平。",
      "variants": []
    }
  ],
  "breakthroughs": [
    {
      "id": "glm-chatglm-6b",
      "date": "2023-03-13",
      "label": "GLM",
      "name": "以 62 亿参数配合 INT4 量化",
      "releaseId": "chatglm-6b",
      "lane": "推理",
      "mechanism": "以 62 亿参数配合 INT4 量化，把中文对话大模型拉到 6GB 显存的消费级显卡上运行。",
      "impact": "智谱开源系列的第一代中英双语对话模型，62 亿参数、GLM 架构，可在消费级显卡本地部署，是整个 ChatGLM/GLM 开源谱系的起点。",
      "magnitude": "总参 62 亿"
    },
    {
      "id": "glm-chatglm2-6b",
      "date": "2023-06-24",
      "label": "FlashAttention",
      "name": "上下文长度由初代的 2K 扩展至 32K",
      "releaseId": "chatglm2-6b",
      "lane": "训练",
      "mechanism": "上下文长度由初代的 2K 扩展至 32K（对话 8K 训练），同时推理速度提升 42%、INT4 下 6G 显存支持对话长度由 1K 提升到 8K。",
      "impact": "ChatGLM-6B 的第二代版本，借 FlashAttention 与 Multi-Query Attention 把上下文从 2K 提到 32K、推理提速 42%，同尺寸开源模型中竞争力显著增强。",
      "magnitude": "上下文 32K"
    },
    {
      "id": "glm-codegeex2-6b",
      "date": "2023-07-19",
      "label": "ChatGLM2-6B",
      "name": "仅 60 亿参数即在 HumanEval-X",
      "releaseId": "codegeex2-6b",
      "lane": "训练",
      "mechanism": "仅 60 亿参数即在 HumanEval-X 上超越 150 亿参数的 StarCoder-15B（Python Pass@1 35.9%）。",
      "impact": "CodeGeeX2-6B 是基于 ChatGLM2-6B 架构、经 600B 代码 token 预训练的多语言代码生成模型，Python HumanEval-X Pass@1 达 35.9%，用 6B 参数超过 15B 的 StarCoder-15B。",
      "magnitude": "上下文 8K"
    },
    {
      "id": "glm-chatglm3-6b",
      "date": "2023-10-25",
      "label": "Prompt",
      "name": "原生支持工具调用",
      "releaseId": "chatglm3-6b",
      "lane": "后训练",
      "mechanism": "原生支持工具调用（Function Call）与代码执行，从纯对话模型转向可执行任务的 Agent 形态。",
      "impact": "ChatGLM 系列第三代的对话模型，最大变化是采用全新 Prompt 格式并原生支持 Function Call、Code Interpreter 与 Agent 场景，同时开源 Base 与 32K 长文本版本。",
      "magnitude": "总参 6B"
    },
    {
      "id": "glm-cogvlm-chat-hf",
      "date": "2023-11-16",
      "label": "Visual",
      "name": "视觉专家模块",
      "releaseId": "cogvlm-chat-hf",
      "lane": "多模态",
      "mechanism": "视觉专家模块（Visual Expert）：在预训练语言模型的每一层引入视觉专家，使 VLM 效果超越或持平 PaLI-X 55B（自述）。",
      "impact": "CogVLM-17B 是开源视觉语言模型，由 10B 视觉参数与 7B 语言参数组成，在 10 个跨模态基准上自称 SOTA，并在 VQAv2/OKVQA/TextVQA/COCO captioning 上排名第二。",
      "magnitude": "总参 17B"
    },
    {
      "id": "glm-cogagent-chat-hf",
      "date": "2023-12-15",
      "label": "x1120",
      "name": "首个把 VLM 用作 GUI Agent",
      "releaseId": "cogagent-chat-hf",
      "lane": "多模态",
      "mechanism": "首个把 VLM 用作 GUI Agent：对任意 GUI 截图直接返回任务计划、下一步动作与操作坐标，并支持 1120x1120 超高清输入。",
      "impact": "CogAgent-18B 是在 CogVLM 基础上改进的视觉语言模型（11B 视觉 + 7B 语言），主打 GUI Agent、高分辨率图像理解与 OCR 增强，是 cogagent-chat 版本权重。",
      "magnitude": "总参 18B"
    },
    {
      "id": "glm-cogvlm2-llama3-chat-19b",
      "date": "2024-05-16",
      "label": "Meta-Llama-3-8B-",
      "name": "图文文档理解大幅跃升",
      "releaseId": "cogvlm2-llama3-chat-19b",
      "lane": "多模态",
      "mechanism": "图文文档理解大幅跃升：DocVQA 92.3 超过 GPT-4V(88.4)、OCRBench 756 超过 GPT-4V(656)，且全程不使用外部 OCR 工具。",
      "impact": "CogVLM2 系列基于 Meta-Llama-3-8B-Instruct 构建的 19B 视觉语言模型，支持 8K 文本与 1344×1344 图像输入，DocVQA 92.3、TextVQA 84.2。",
      "magnitude": "上下文 8K"
    },
    {
      "id": "glm-glm-4-9b-chat",
      "date": "2024-06-04",
      "label": "Function",
      "name": "把 128K 长上下文、26 种多语言与 F",
      "releaseId": "glm-4-9b-chat",
      "lane": "推理",
      "mechanism": "把 128K 长上下文、26 种多语言与 Function Call 工具调用同时下放到 9B 开源模型（BFCL Overall Acc. 81.00，逼近 gpt-4-turbo 的 81.24）。",
      "impact": "GLM-4 系列的开源对话模型 GLM-4-9B-Chat，支持 128K 上下文、26 种语言、网页浏览与工具调用，是同代 9B 级开源模型的主力版本。",
      "magnitude": "上下文 128K"
    },
    {
      "id": "glm-glm-4v-9b",
      "date": "2024-06-04",
      "label": "OCRBench",
      "name": "高分辨率文字识别反超闭源旗舰",
      "releaseId": "glm-4v-9b",
      "lane": "多模态",
      "mechanism": "高分辨率文字识别反超闭源旗舰：OCRBench 786 为卡内同表最高（GPT-4o 736、GPT-4v 656），MMBench-EN 81.1 接近 GPT-4o 的 83.4。",
      "impact": "GLM-4 系列的开源多模态版本，具备 1120×1120 高分辨率中英双语多轮对话能力，卡内表格自述在中英文综合、感知推理、文字识别、图表理解上超越 GPT-4-turbo-2024-04-09、Gemini 1.0 Pro、Qwen-VL-Max 与 Claude 3 Opus。",
      "magnitude": "上下文 8K"
    },
    {
      "id": "glm-cogvideox-2b",
      "date": "2024-08-05",
      "label": "Expert",
      "name": "把文生视频门槛压到消费级",
      "releaseId": "cogvideox-2b",
      "lane": "多模态",
      "mechanism": "把文生视频门槛压到消费级：diffusers FP16 最低 4GB、INT8(torchao) 3.6GB 显存即可推理（推理速度 A100 约 90 秒/50 步）。",
      "impact": "CogVideoX 开源文生视频模型的入门版本（2B，FP16 训练），输出 720×480、6 秒、8 fps 视频，主打低成本推理与二次开发。",
      "magnitude": "总参 2B"
    },
    {
      "id": "glm-cogvideox-5b",
      "date": "2024-08-17",
      "label": "rope",
      "name": "用 3d_rope_pos_embed 替换",
      "releaseId": "cogvideox-5b",
      "lane": "多模态",
      "mechanism": "用 3d_rope_pos_embed 替换 3d_sincos_pos_embed 以提升生成质量，推理显存最低 5GB（多卡 15GB，A100 约 180 秒/50 步）。",
      "impact": "CogVideoX 开源文生视频模型的较大规模版本（5B，BF16 训练），相比 2B 版本提供更高的视频生成质量与视觉效果。",
      "magnitude": "总参 5B"
    },
    {
      "id": "glm-glm-4-voice-9b",
      "date": "2024-10-24",
      "label": "token",
      "name": "端到端语音对话并可按指令改变情感、语调、语速",
      "releaseId": "glm-4-voice-9b",
      "lane": "多模态",
      "mechanism": "端到端语音对话并可按指令改变情感、语调、语速与方言，无需级联 ASR+TTS。",
      "impact": "GLM-4-Voice 端到端语音模型的 LLM 部分：在 GLM-4-9B 基础上做语音模态预训练与对齐，可直接理解和生成中英文离散化语音并实时对话。",
      "magnitude": "总参 9B"
    },
    {
      "id": "glm-cogvideox1-5-5b",
      "date": "2024-11-02",
      "label": "frames",
      "name": "分辨率从 720×480 提升到 1360×",
      "releaseId": "cogvideox1-5-5b",
      "lane": "多模态",
      "mechanism": "分辨率从 720×480 提升到 1360×768、帧率 8→16 fps，视频时长由 6 秒扩展到 5/10 秒（A100 约 1000 秒/50 步）。",
      "impact": "CogVideoX 的 1.5 代 5B 文生/图生视频模型（模型卡标注发布日 2024-11-08），分辨率升到 1360×768、帧率 16 fps、支持 5 秒或 10 秒视频。",
      "magnitude": "总参 5B"
    },
    {
      "id": "glm-glm-4-32b-0414",
      "date": "2025-04-07",
      "label": "Artifact",
      "name": "32B 稠密模型在 IFEval",
      "releaseId": "glm-4-32b-0414",
      "lane": "训练",
      "mechanism": "32B 稠密模型在 IFEval(87.6)、BFCL-v3(69.6)、TAU-Bench Retail(68.7)、SimpleQA(88.1) 上追平乃至超过 GPT-4o-1120 与 671B 的 DeepSeek-V3-0324，并以 MIT 许可开源。",
      "impact": "GLM-4-0414 系列的主力 32B 稠密模型（2025-04 发布，MIT 许可），基座 GLM-4-32B-Base-0414 用 15T 数据预训练，卡内自述在多项基准上对标 GPT-4o 与 DeepSeek-V3-0324(671B)。",
      "magnitude": "总参 32B"
    },
    {
      "id": "glm-glm-z1-32b-0414",
      "date": "2025-04-08",
      "label": "RL",
      "name": "在 32B 开源规模上做出对标 DeepSe",
      "releaseId": "glm-z1-32b-0414",
      "lane": "训练",
      "mechanism": "在 32B 开源规模上做出对标 DeepSeek V3/R1 的深度推理能力，数学与复杂任务较底座显著提升。",
      "impact": "基于 GLM-4-32B-0414 经冷启动与扩展强化学习打造的 32B 深度思考推理模型。",
      "magnitude": "上下文 32K"
    },
    {
      "id": "glm-glm-4-1v-9b-thinking",
      "date": "2025-06-28",
      "label": "Thinking",
      "name": "首个以「思考范式 + 强化学习」训练的 GL",
      "releaseId": "glm-4-1v-9b-thinking",
      "lane": "多模态",
      "mechanism": "首个以「思考范式 + 强化学习」训练的 GLM-V 模型，在 28 项基准中 23 项为 10B 级最佳、18 项超越 Qwen-2.5-VL-72B。",
      "impact": "基于 GLM-4-9B-0414 的 9B 视觉语言推理模型，在 10B 级 VLM 中取得 SOTA。",
      "magnitude": "上下文 64k"
    },
    {
      "id": "glm-glm-4-5",
      "date": "2025-07-20",
      "label": "B-A32B",
      "name": "以 355B-A32B 规模在 12 项标准",
      "releaseId": "glm-4-5",
      "lane": "推理",
      "mechanism": "以 355B-A32B 规模在 12 项标准基准上取得 63.2 的综合分，位列所有专有与开源模型第 3。",
      "impact": "面向智能体的 355B-A32B MoE 基础模型，统一推理、编码与智能体能力，支持思考/非思考双模式。",
      "magnitude": "上下文 128K"
    },
    {
      "id": "glm-glm-4-5-air",
      "date": "2025-07-20",
      "label": "B-A12B",
      "name": "以 106B-A12B 的紧凑设计拿到 59",
      "releaseId": "glm-4-5-air",
      "lane": "推理",
      "mechanism": "以 106B-A12B 的紧凑设计拿到 59.8 的综合分，接近 355B 旗舰而推理成本大幅降低。",
      "impact": "GLM-4.5 系列中更紧凑高效的 106B-A12B MoE 版本，兼顾性能与部署效率。",
      "magnitude": "上下文 128K"
    },
    {
      "id": "glm-glm-4-5v",
      "date": "2025-08-10",
      "label": "GLM-4.5-Air",
      "name": "在 42 项公开视觉语言基准上取得同规模 S",
      "releaseId": "glm-4-5v",
      "lane": "多模态",
      "mechanism": "在 42 项公开视觉语言基准上取得同规模 SOTA，并把 Grounding 与 GUI Agent 能力做进模型。",
      "impact": "以 GLM-4.5-Air（106B-12B active）为底座的旗舰视觉语言模型，覆盖图像、视频、文档理解与 GUI 操作。",
      "magnitude": "激活 12B"
    },
    {
      "id": "glm-glm-4-6",
      "date": "2025-09-29",
      "label": "TIR",
      "name": "上下文从 128K 扩到 200K 以支撑更",
      "releaseId": "glm-4-6",
      "lane": "推理",
      "mechanism": "上下文从 128K 扩到 200K 以支撑更复杂 Agent 任务，在 8 项公开基准上对 GLM-4.5 全面提分。",
      "impact": "在 GLM-4.5 基础上把上下文扩到 200K 并全面强化编码、推理、工具与写作的迭代版本。",
      "magnitude": "上下文 200K"
    },
    {
      "id": "glm-glm-4-6v-flash",
      "date": "2025-12-07",
      "label": "Function",
      "name": "首次在 GLM-V 系列引入原生 Funct",
      "releaseId": "glm-4-6v-flash",
      "lane": "多模态",
      "mechanism": "首次在 GLM-V 系列引入原生 Function Calling，把「视觉感知」直接接到「可执行动作」。",
      "impact": "GLM-4.6V 系列的 9B 轻量多模态模型，面向本地部署与低延迟场景。",
      "magnitude": "上下文 128k"
    },
    {
      "id": "glm-autoglm-phone-9b",
      "date": "2025-12-08",
      "label": "GUI",
      "name": "把视觉语言模型直接接进真实手机 GUI",
      "releaseId": "autoglm-phone-9b",
      "lane": "多模态",
      "mechanism": "把视觉语言模型直接接进真实手机 GUI：自然语言下达任务即可自动解析意图、规划并执行操作。",
      "impact": "AutoGLM 手机智能助手框架中的开源模型，理解手机屏幕并自动完成跨 App 操作任务。",
      "magnitude": "总参 9B"
    },
    {
      "id": "glm-glm-asr-nano-2512",
      "date": "2025-12-09",
      "label": "Wenet",
      "name": "以 1.5B 规模取得同类开源模型最低平均错",
      "releaseId": "glm-asr-nano-2512",
      "lane": "多模态",
      "mechanism": "以 1.5B 规模取得同类开源模型最低平均错误率 4.10，并在多基准上超过 OpenAI Whisper V3。",
      "impact": "1.5B 的开源语音识别模型，重点优化方言与低音量场景。",
      "magnitude": "总参 1.5B"
    },
    {
      "id": "glm-glm-4-7",
      "date": "2025-12-22",
      "label": "Interleaved",
      "name": "SWE-bench Verified 73.",
      "releaseId": "glm-4-7",
      "lane": "后训练",
      "mechanism": "SWE-bench Verified 73.8%（+5.8）、Terminal Bench 2.0 41.0%（+16.5）、HLE w/ Tools 42.8%（+12.4）较 GLM-4.6 大幅提升，并新增 Preserved Thinking。",
      "impact": "面向编码与 Agent 的旗舰模型，强化 UI/Vibe Coding、工具使用与复杂推理能力。",
      "magnitude": "见模型卡"
    },
    {
      "id": "glm-glm-image",
      "date": "2026-01-08",
      "label": "GLM-4-9B-0414",
      "name": "CVTG-2K 词准确率 0.9116 / ",
      "releaseId": "glm-image",
      "lane": "多模态",
      "mechanism": "CVTG-2K 词准确率 0.9116 / NED 0.9557、LongText-Bench ZH 0.979，文本渲染能力显著领先同表开源与闭源模型。",
      "impact": "混合自回归 + 扩散解码器的图像生成模型，在文本渲染与知识密集型生成上优势明显。",
      "magnitude": "见模型卡"
    },
    {
      "id": "glm-glm-4-7-flash",
      "date": "2026-01-19",
      "label": "B-A3B",
      "name": "以 30B-A3B 在 SWE-bench ",
      "releaseId": "glm-4-7-flash",
      "lane": "架构",
      "mechanism": "以 30B-A3B 在 SWE-bench Verified 59.2、τ²-Bench 79.5 上大幅领先同量级 Qwen3-30B-A3B-Thinking-2507 与 GPT-OSS-20B。",
      "impact": "30B-A3B 的 MoE 轻量模型，主打 30B 级别性能与效率平衡。",
      "magnitude": "激活 3B"
    },
    {
      "id": "glm-glm-ocr",
      "date": "2026-01-30",
      "label": "Multi-Token",
      "name": "以 0.9B 规模在 OmniDocBenc",
      "releaseId": "glm-ocr",
      "lane": "多模态",
      "mechanism": "以 0.9B 规模在 OmniDocBench V1.5 取得 94.62 分排名第一，并可在 vLLM/SGLang/Ollama 上高并发部署。",
      "impact": "0.9B 参数的多模态 OCR 模型，面向复杂文档解析与结构化信息抽取。",
      "magnitude": "总参 0.9B"
    },
    {
      "id": "glm-glm-5",
      "date": "2026-02-11",
      "label": "B-A40B",
      "name": "从 GLM-4.5 的 355B-A32B ",
      "releaseId": "glm-5",
      "lane": "训练",
      "mechanism": "从 GLM-4.5 的 355B-A32B 扩到 744B-A40B、预训练数据从 23T 增到 28.5T，并在推理/编码/Agent 上取得全球开源最佳，逼近前沿闭源模型。",
      "impact": "面向复杂系统工程与长程 Agent 任务的 744B-A40B 开源旗舰模型。",
      "magnitude": "上下文 200K"
    },
    {
      "id": "glm-glm-5-1",
      "date": "2026-04-03",
      "label": "agentic",
      "name": "在长程任务上可维持数百轮优化、数千次工具调用",
      "releaseId": "glm-5-1",
      "lane": "后训练",
      "mechanism": "在长程任务上可维持数百轮优化、数千次工具调用持续提分（SWE-Bench Pro 58.4 领先 GLM-5、Terminal-Bench 2.0 63.5 vs GLM-5 的 56.2）。",
      "impact": "面向 agentic 工程的下一代旗舰模型，重点提升长程任务中的持续优化能力。",
      "magnitude": "见模型卡"
    },
    {
      "id": "glm-glm-5-2",
      "date": "2026-06-16",
      "label": "solid",
      "name": "solid 1M 上下文 + IndexSh",
      "releaseId": "glm-5-2",
      "lane": "训练",
      "mechanism": "solid 1M 上下文 + IndexShare 使 1M 长度下每 token FLOPs 降 2.9×，HLE 40.5、AIME 2026 99.2 大幅超越 GLM-5.1。",
      "impact": "首个能在 1M token 上下文上稳定支撑长程任务的旗舰模型，并提出 IndexShare 稀疏注意力。",
      "magnitude": "上下文 1M"
    },
    {
      "id": "glm-glm-5-3",
      "date": "2026-08-25",
      "label": "GLM-5.2",
      "name": "编码能力较 GLM-5.2 提升 50%",
      "releaseId": "glm-5-3",
      "lane": "训练",
      "mechanism": "编码能力较 GLM-5.2 提升 50%（自研 Z.ai Code Bench），CyberGym 84.5 居 SOTA，ExploitGym 2h/6h 达 105/130（GLM-5.2 为 29/39）。",
      "impact": "与 GLM-5.2 共用基座、所有提升来自后训练的编码与长程任务强化版。",
      "magnitude": "上下文 1M"
    },
    {
      "id": "glm-glm-5-3-flash",
      "date": "2026-08-25",
      "label": "GLM-5",
      "name": "首次在 GLM 系列引入稀疏+线性混合注意力",
      "releaseId": "glm-5-3-flash",
      "lane": "多模态",
      "mechanism": "首次在 GLM 系列引入稀疏+线性混合注意力与 mHC 超连接，320B-18B 以十分之一价格超过 GLM-5.2 并逼近 Claude Opus 4.8 的编码/Agent 水平。",
      "impact": "GLM-5 系列首个原生多模态模型，320B-A18B，主打低成本高性能。",
      "magnitude": "激活 18B"
    }
  ]
} as Dataset
